### ISSUE TITLE
Update project "sites" tab: no sites

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1127]
Include language in Project View, Empty Sites List to instruct user on how to populate sites

## How to find screen
1. Create a new project (no sites)
2. Go to the empty sites tab
3. See sheet

## Design
[Design Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=138-13384&mode=design&t=580ptJMKveswYvCR-0)
<img width="329" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/10799815/3eac0846-62eb-48c0-9e4d-e7d24b5df9cb">

## Acceptance Criteria
- [ ] Empty site tab contains instructions on how to create a site
- [ ] Retain includes instructions to transfer a site (not shown in design) beneath site creation instructions

**Comment by CourtneyLee333** [comment]
The description of this issue is very confusing, and incorrect I believe, but implementation now matches the [intended design as seen here in Figma. ](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=2910-15613&t=Esm9mQnDuie9QHKp-1)
