### ISSUE TITLE
Update Soil Color Guide with R symbol

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1154]
Add  :registered: symbol to Soil Color Guide Info Sheet. See parent task for details.

## Designs 
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=6168-21898&mode=design&t=3XXCUsJRxLmrQY78-0)
![image](https://github.com/techmatters/terraso-product/assets/10799815/2bd101e5-237f-4b99-8625-66c0bceb5f6b)

## Acceptance Criteria
- [ ] add ®️ symbol after the first use of Post-It notes

**Comment by knipec** [comment]
Assigning to Paul to clarify if and where we want this. 

It's very easy from an engineering perspective; literally all we have to do is add ® to the string(s) in en.json.
