### ISSUE TITLE
Implement US Location Soil ID Page

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1155]
Implement Soil ID page for Location. 

[Design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-15872&mode=design&t=lT8XcLFVNEzeCw43-0)

<img width="445" alt="image" src="https://github.com/techmatters/terraso-product/assets/10799815/e339c78c-07ec-4e0a-ad65-e50674af2e7a">

## Acceptance Critera
- [ ]

**Comment by CourtneyLee333** [comment]
@DerekCaelin Is this the one we're calling "temporary location"?

**Comment by DerekCaelin** [comment]
This is now a duplicate issue. Actual implementation is reflected in #666
