### ISSUE TITLE
Build Soil ID Soil Info page - Location info, match percentage, and site creation

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1156]
As a user, I want to use the Site Soil ID Soil Info Sheet to learn about and act on the soil ID I selected for my location:
- An information readout about the selected soil
- The match percentage of the soil that I selected to open this screen
- The ability to initiate the site creation process on the Location Soil Info page, using the location's latitude and longitude coordinates as a location

See parent tasks for more details.

Note: Many components built for this module are used both in the **Site Soil ID Soil Info** page and the **Location Soil ID Soil Info** page. 

## How to find the screen 
1. From home screen, select a point on the map
2. Select "Explore the data" on the Soil ID Tile
3. Select a soil from the ranked soil list

## Design

[Design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-12771&mode=design&t=JRM18JIKT7aMSjgO-0)

## Acceptance Criteria
- [x]  As a viewer, I see a page that describes, for a given soil...
    - [x] Soil Series Name
    - [x] Soil Component Name
    - [x] Soil Description
    - [x] Ecological Site Name
    - [x] Ecological Site ID
 - [x] Information about the soil match I selected...
    - [x] Info box containing help text 
    - [x] Display percentage likliehood that the soil is a match for the site (relies on soilID algorithm)
    - [x] Button to view location on Soil Web (External Link) `(https://casoilresource.lawr.ucdavis.edu/gmap/?loc={latitude},{longitude})`
 - [x] (temporary location only) And a button which opens the standard "create site" workflow for the location I selected.

**Comment by DerekCaelin** [comment]
This passes "functional" review in that the page exists and has dummy content displayed correctly, and that different elements appear depending on whether the location is temporary or not. I expect we'll look again once we hook it up to soil ID data with [653](https://github.com/techmatters/terraso-product/issues/653). Over to @CourtneyLee333 for her review

**Comment by CourtneyLee333** [comment]
- I notice that under LCC, there is a second "Ecological Site Name" which should be "Data Source" before  SSURGO/STATSGO.

**Comment by DerekCaelin** [comment]
Pulling this issue into the June sprint, with the expectation that there is a low-effort improvement to be made

**Comment by DerekCaelin** [comment]
Pulling into June for Ruxandra to address in the sprint.

**Comment by tm-ruxandra** [comment]
@CourtneyLee333 I can quickly fix the first and third issues there -- thanks for the catches.
