### ISSUE TITLE
Build Location Soil Info page - Integrate Soil Properties component

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1158]
As a Manager or a Contributor, I want see the soil properties of a given soil, so I know more about the characteristics of a soil that may be at this location. 

Build a module for SoilID Info page that adapts the selected location soil ID's soil data properties using the standard soil properties chart/visualization components, so that a user can learn more about a potential soil for a location. See parent task for more details.

## How to find the screen
1. From home screen, select a location on a map
2. In the resulting popover, select "Learn more" 
3. Select "Explore the data" on the soilID Tile
4. Select a soil from the ranked soil list

## References
[SoilID Help Text](https://docs.google.com/document/d/1qRvfXfjKkoKAXl3jGeDwlRMXw3rYbvJc5ciY06Ehbqw/edit)

## Design
- [Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-15906&mode=design&t=6V7vK4lZXKKsrz3b-0)

### Dependencies
- https://github.com/techmatters/terraso-product/issues/653

## Acceptance Criteria
- [x] As a Manager or a Contributor, I want see the soil properties of a given soil, so I know more about the characteristics of a soil that may be at this location. 
  - [x] Texture
  - [ ] Color
  - [ ] Rock Fragmentation

## Additional Context
- At launch, display blank values for the site's pH and Electrical Conductivity, since we won't be tracking that.

**Comment by DerekCaelin** [comment]
@tm-ruxandra this is in QA, but I assume I should hold off on reviewing until https://github.com/techmatters/terraso-product/issues/653 is implemented, is that right?

**Comment by tm-ruxandra** [comment]
@DerekCaelin Technically you can review it now / whenever the next build goes out, but it will only be displaying dummy data.

**Comment by DerekCaelin** [comment]
This passes "functional" review in that the page exists and has dummy content displayed correctly, and that different elements appear depending on whether the location is temporary or not. I expect we'll look again once we hook it up to soil ID data with [653](https://github.com/techmatters/terraso-product/issues/653). Over to @CourtneyLee333 for her review

**Comment by CourtneyLee333** [comment]
Woohoo! Looking good! 

Some design observations:
- LocationScoreInfoSheet and PropertiesScoreInfoSheet cover the app bar. They should, instead, open to the proper height. 
- BigCloseButton on LocationScoreInfoSheet and PropertiesScoreInfoSheet  do not function. It does nothing when tapped. 
- Same comment about the table cell width that I had on the main Soil ID screen - the cells should be wider to better accommodate the content.

**Comment by CourtneyLee333** [comment]
@DerekCaelin

**Comment by DerekCaelin** [comment]
Pulling into June.

**Comment by DerekCaelin** [comment]
This works!  I understand that as of 141, it is actually using dummy data, but the client is actually calling information from the backend. We'll separately test the "real data with soil ID" aspect when that is resolved.
