### ISSUE TITLE
Capri settings menu

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1163]
Do the client side work to allow the user to access the menu and perform various experiences critical for Capri launch

## How to find this screen
1. Open LandPKS
2. Select the "Settings" button in the footer

## Design
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-13101&mode=design&t=3XXCUsJRxLmrQY78-0)
#### Design as of 4/22/2024, please view Figma for most up-to-date version
![Image](https://github.com/techmatters/terraso-product/assets/10799815/0f5b7ce2-5c15-49e7-8972-3bc48d66f87c)

## Acceptance Criteria
- [x] As a logged-in user, I want to be able to access a settings screen where I can
   - [x] see the account I am logged in with
   - [x] See button log out of my own account (tying it to API will be part of https://github.com/techmatters/terraso-product/issues/418)

**Comment by DerekCaelin** [comment]
Reopening this issue real quick for QA by courtney and me.

**Comment by DerekCaelin** [comment]
@tm-ruxandra thank you for this. I can see my account, I can successfully log out of my account, and I see a button to start the account deletion process.

Not explicitly named in the acceptance criteria was the addition of a UI element displaying the version number of the app. I see a partially complete version of this. There is text where the design calls for the version number to be displayed, but it reads `(Untagged application version)`. Is that expected, and should I submit a separate request to display the version number? I would like to know how much effort it would be to add. 

@CourtneyLee333 available for your review.

**Comment by tm-ruxandra** [comment]
@DerekCaelin That sounds like the application version isn't getting picked up as expected in application releases. I feel that this should be filed as a bug, since the screen behaves as expected (this is its default behavior if it can't find the version number). The bug would be to fix the version not being accessible to the application configuration system.

**Comment by CourtneyLee333** [comment]
This passes my review. Thanks!

**Comment by DerekCaelin** [comment]
At Ruxandra's suggestion I've filed this as a bug: https://github.com/techmatters/terraso-mobile-client/issues/1286

I've ranked it as P2 since QA testers need a way to tell us their version number, but there is a workaround by looking at test flight or looking at app details. 

Everything else is great! Thanks for the swift turnaround on this. Closing issue.
