### ISSUE TITLE
BulletList inside a Text component fails to wrap text on Android

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#1173]
On Android, on Soil Texture screen, text in bullet points should wrap.

Ultimately this seems to be a problem with the following nesting:
```
<Text>
  <Column>
    <Text> this text won't wrap </Text>
  </Column> 
</Text>
```

Solution options:
1. Paul suggested looking into: https://github.com/jsamr/react-native-li ([slack](https://tech-matters.slack.com/archives/C0376RCCXD2/p1714138248278829))
2. A workaround could be to just stop using the BulletList as an item within the components prop to the <Trans> component -- because the <Trans> component requires being wrapped by \<Text>. 

![Image](https://github.com/techmatters/terraso-mobile-client/assets/5590815/403726a9-fbb7-4bc2-a628-73a56656ffca)

**Comment by knipec** [comment]
@tm-ruxandra @CourtneyLee333 I'm guessing not but just in case... Do you consider this part of the components work?

**Comment by tm-ruxandra** [comment]
@knipec I think it is -- we already have work for typography components, could handle this by making bulleted lists as another one. (I think that would be a good idea regardless since bulleted lists need to be their own component regardless).

**Comment by CourtneyLee333** [comment]
Ah, okay, I didn't realize we need a component for lists. I'll make an issue for bulleted and numbered lists.

**Comment by CourtneyLee333** [comment]
Closing as this will be done in the component work. [Here's the design issue for it](https://github.com/techmatters/terraso-product/issues/991)
