### ISSUE TITLE
Client work - update experience for transferring unaffiliated site to project

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1177]
Do client-side work to allow a user to transfer a site to a project. This work primarily happens on the site settings screen. Please see parent task for details

## Steps to get to this screen
1. Be a manager of an unaffiliated site
2. Go to the setting screen
3. See screen

## Designs
- [Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-13330&mode=design&t=v87rayE2eXDGQRO0-0)

#### Design as of 4/22/24, please see figma for most up-to-date design
![image](https://github.com/techmatters/terraso-product/assets/10799815/f130d2f5-993b-41c7-acce-a8c1f66a2807)

## Acceptance Criteria 
- [x] Remove help popover for transfer site button
- [x] As the manager of a site, I want to see a dropdown menu that shows the list of all projects in which I am a contributor or manager
- [ ] After starting the transfer of my site to a project, I want to see a confirmation dialog informing me of the consequences of transferring my site, so I am am sure I've made the right decision.

**Comment by paulschreiber** [comment]
Confirmation was https://github.com/techmatters/terraso-mobile-client/pull/1612
Popover was https://github.com/techmatters/terraso-mobile-client/pull/1851
