### ISSUE TITLE
Update delete account button for users who have already requested deletion

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1179]
In the settings menu, signify to the user that their request to delete their account has been received and that they don't need to request it again. Please see parent issue for details.

Dependent on: https://github.com/techmatters/terraso-backend/issues/1112

## Designs
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=6995-35081&mode=design&t=EvCSFQJWglFzt9sI-0)

## Acceptance Criteria
- [ ] Greyed out, unclickable delete button on the Settings menu. ("Pending") signifier
- [ ] As a user, I want to know that my request to delete my account has been received and that I can't submit another request.

**Comment by DerekCaelin** [comment]
Ruxandra expressed an interest

**Comment by CourtneyLee333** [comment]
I don't see this happening in v144 on Android or iOS.

**Comment by CourtneyLee333** [comment]
Still waiting on v145 for iOS, but on Android when I press the Delete button it doesn't do an action. I see the button state change, but I remain on the Delete Account screen, get no confirmation message, and see no sign of "pending" status.

**Comment by CourtneyLee333** [comment]
It's working now and looks good!

**Comment by paulschreiber** [comment]
Closing this as done.
