### ISSUE TITLE
Soil ID - "Explore the data" button opens new Soil ID sheet

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1196]
Clicking “Explore the data” button from Soil ID tile takes me to Location Soil ID sheet. This task covers creating the screen, the static content and universal elements. See parent task for context and related tasks. 

### Soil ID Tile 
**Tapping the button in the tile...**
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-15842&mode=design&t=bn4bR0g90ayypnJZ-0) - Temporary 
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-13455&mode=design&t=bn4bR0g90ayypnJZ-0) - Site

### Soil ID screen
**... leads me to a Soil ID Screen...**
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-15872&mode=design&t=bn4bR0g90ayypnJZ-0) - Temporary
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-14751&mode=design&t=bn4bR0g90ayypnJZ-0) - Site

**...With these basic elements:**
## Acceptance Criteria:
- [x] If user presses "Explore the data" from a Temporary Location OR a Site view, they see this page (Eng note: we'll want separate components for Temporary Location and Site, but they should share much of their content)
- [x] Screen has correct static text content (Site Name, Soil ID header+text, Top Soil Matches header+"i" button)
- [x] Pressing the "i" icon opens the informational overlay sheet
- [x] Pressing the back arrow returns to the Location Dashboard
- [x] (Temporary Location) Screen has a button to create site, that navigates to the “Create Site” page 

**Non-goals**
- [ ] Sheet does not yet have soil match tiles
- [ ] Top Soil Matches section doesn't yet have content under the header
- [ ] Site Data section does not yet exist

## FYI
Most other stories of "parent" story https://github.com/techmatters/terraso-product/issues/666 depend on this

**Comment by knipec** [comment]
This should be in the next build (v124) to verify.

**Comment by DerekCaelin** [comment]
Thanks @knipec! @CourtneyLee333 this looks fine to me, over to you for review. I see a very slight difference in language between what's in Figma now and what was implemented on the Info Sheet for the Temporary Pin. Up to you if we should revise. 

Implemented text
`Create a site here and enter the recommended data to improve accuracy of the match scores. `

[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7198-33953&t=NIbwlk7npsQE2hUP-0):
`Create a site at this location to see which slope and soil data will improve accuracy of the match scores. `

**Comment by CourtneyLee333** [comment]
Oh hooray! Carissa used the text I had previously written, which got overwritten in my Figma design last week. I like the previous text better, so I have updated Figma with what has been implemented. No changes needed. 

Everything looks good to me!
