### ISSUE TITLE
Soil ID - "Top Soil Matches" module

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1197]
As a user on the Soil ID page, see Top Soil Matches tiles component shows up to 12 soils. See parent task for context and related issues.

## References
[Carissa's implementation notes](https://docs.google.com/document/d/1Jae9g-OpKADlKiviZ_a-DO4Egrdhq3_n__lF1jrMQH4/edit)
Carissa: Nice if it comes after user story #[617](https://github.com/techmatters/terraso-product/issues/617), but not necessary (would just want the data in the same format that would be returned by the API)
The expanded view ("See more matches") is covered by #1198. 

## Designs
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-12771&mode=design&t=bn4bR0g90ayypnJZ-0) (Site and Location visual appearance are identical) 
#### Design as of 4/29/2024, please see Figma for most recent version
![image](https://github.com/techmatters/terraso-mobile-client/assets/10799815/279b0802-acf8-47fc-9e30-ab1fa79a4c39)

## Acceptance Criteria
- [x] List displays properly for different numbers of soil matches (0, 1, 12) under "Top Soil Matches" header
- [x] Tiles look reasonable if the soil name is really long
- [x] Visible for Temporary Location and Site
- [x] Ideally: Use API that Paul made for dummy data

**Non-goal**
- [ ] Reference dummy data until Soil ID returns real info
- [ ] Pressing a soil match will not yet do anything
- [ ] Users won't yet have the option to "see fewer soil matches" to hide the matches below the top 4.

**Comment by knipec** [comment]
@DerekCaelin FYI I moved "See fewer soil matches" to a non-goal for this story, so it will be part of #1198.

**Comment by DerekCaelin** [comment]
@knipec exciting to test this. Is there a way to have the dummy API return 12 responses so we can check, and to return a "really long" response so we can see the wrapping (or did we decide that was unlikely)?

**Comment by knipec** [comment]
@DerekCaelin Great questions. 
- 12 responses: I'll look into this when I get a chance.
- Wrapping: I showed Courtney the wrapping behavior for long soil names, but she said it's unlikely to go over two lines. I'll get a pic for you though when I get a chance.

**Comment by CourtneyLee333** [comment]
Carissa and I talked about this but I can't remember if it is supposed to have been fixed already: 100% rank wraps on my Android phone and my iPad. While I don't expect a soil to ever attain 100% match, I suppose it is possible.
![Screenshot_20240614-085147](https://github.com/techmatters/terraso-mobile-client/assets/8915145/db93ad22-403b-4702-ab36-96f5dc6de0f0)

The sizing is a little weird on tablet size, but let's save that for later when we attend to responsive sizing, large fonts, etc...

**Comment by DerekCaelin** [comment]
@knipec I assume it would it be trivial to address this issue? (On my Pixel 7, on a temporary site, "100%" does not wrap. )

**Comment by knipec** [comment]
The short answer is: ehh, kinda -- there's not a great way that we could think of to say "on a device of arbitrary size, guarantee the text won't wrap" and also "all the corresponding elements (like match percent, soil name, and '>') line up vertically across each soil match tile". 

I would have thought a fixed width would work out because our font sizes are also fixed (as I understand), but I don't have in-depth knowledge of the relationship between pixels and font sizes on a phone yet so not sure why it doesn't work. I upped the fixed width a bit, and seems like not a huge priority for capri, but maybe we want something in the backlog to reflect figuring out responsive layout kinda stuff?

**Comment by knipec** [comment]
Most recent change is in v147

**Comment by CourtneyLee333** [comment]
@knipec the 100% still wraps on my ipad. But I think we've given this issue enough time for now.

**Comment by knipec** [comment]
Gonna call this done, but created a low pri bug about it: https://github.com/techmatters/terraso-mobile-client/issues/1635 
(FYI @CourtneyLee333 @DerekCaelin)
