### ISSUE TITLE
Soil ID (Site) - Implement "Land Slope" module

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1200]
Implement the "Land Slope" module on the Soil ID screen for Site locations. See parent issue for context and related issues. 

## Design
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-14752&mode=design&t=bn4bR0g90ayypnJZ-0)
<img width="311" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/10799815/0b5488a2-b664-43b6-aa7c-34c5006b5115">
<img width="311" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/10799815/ddf22166-586a-4b11-8386-052ab8e9e887">

## Acceptance Criteria
- [x] Land Slope text correctly reflects my site data
    - [x] If the user selected an image for Slope Steepness, show the image in the box as well as its accompanying text.
    - [x] If the user did manual entry or slope meter, keep the box empty and just display the text.
    - [x] The text should display the entry, whether a picture is chosen or not
    - [x] Image is an empty square if there is no data
- [x] Button to “Add slope” navigates to the site’s “Slope” input tab. Button is only visible to Managers and Contributors.

**Comment by DerekCaelin** [comment]
This passes my functional review! @CourtneyLee333 please take a look. I reviewed:

## Acceptance Criteria
- [ ] Land Slope text correctly reflects my site data
    - [ ] If the user selected an image for Slope Steepness, show the image in the box as well as its accompanying text.
    - [ ] If the user did manual entry or slope meter, keep the box empty and just display the text.
    - [ ] The text should display the entry, whether a picture is chosen or not
    - [ ] Image is an empty square if there is no data
- [ ] Button to “Add slope” navigates to the site’s “Slope” input tab. Button is only visible to Managers and Contributors.

**Comment by CourtneyLee333** [comment]
Woohoo! Fast and smoth. Some design comments:

- It is weird to have the box empty and display the degree beside it. Would it be a heavy lift to display the number inside the box if an image has not been chosen? Or to hid the box and put the number in its place?
- I think the button should lead to the Slope Steepness screen. And perhaps this means the heading on the Site Dashboard should be Slope Steepness as well, since it is steepness we are specifically referencing and what the algorithm needs.

**Comment by CourtneyLee333** [comment]
@DerekCaelin ☝️

**Comment by knipec** [comment]
@CourtneyLee333 Those should be doable! 
1. Box: There should still be an empty box if there is no site data at all, right?
2. Box: It's easy to do either, and fairly easy to put the number wherever within or outside of the box (see following images for a couple options). Lmk where is best!
Option 1:
![Image](https://github.com/techmatters/terraso-mobile-client/assets/5590815/50790040-5781-4c80-88d4-6441ae376947)
Option 2: 
![Image](https://github.com/techmatters/terraso-mobile-client/assets/5590815/f8ff2181-f2e7-41ea-b549-7ba52d6ff4cb)
3. Button: Yup, can do. Can also update the heading: 
![Image](https://github.com/techmatters/terraso-mobile-client/assets/5590815/cd108dbf-6879-4b09-bceb-56f3f4c8edd8)

**Comment by CourtneyLee333** [comment]
Hooray! I like the number inside the box. And yes, the empty box should still display when there is no data entered. Slope Steepness heading is perfect.

**Comment by DerekCaelin** [comment]
Number inside the box was implemented (and looks really nifty)!  Calling this issue closed.
