### ISSUE TITLE
Soil ID - Use real data for "Top Soil Matches" and "See More Soil Matches"

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1205]
Update the soil match list with real data from the Soil ID algorithm rather than dummy data.

## References
Dependent on https://github.com/techmatters/terraso-mobile-client/issues/1197
Carissa:  (Hopefully is no work besides confirming it looks good, if other stories build upon techmatters/terraso-product#617)
Dependent on user story #[1251](https://github.com/techmatters/terraso-backend/issues/1251)

## Design
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-14833&mode=design&t=bn4bR0g90ayypnJZ-0)

## Acceptance Criteria
- [ ] Ranked soil match shows information from the Soil ID algorithm

**Comment by paulschreiber** [comment]
@knipec this looks to be working. Please confirm.

**Comment by knipec** [comment]
Yup! Closing because there should be no additional work to what has already been done to integrate soil id into the app.
