### ISSUE TITLE
Use real data with Soil ID tile

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1206]
Update the Soil ID tile to display data from the SoilID Algorithm.

## Dependencies
- [x] https://github.com/techmatters/terraso-backend/issues/1270

## Acceptance Criteria
- [ ] I want to see a site with `Soil Prediction` and `Ecological site name` pulled from the Soil ID algorithm 
- [ ] If there is no available match, I want to see "no matches" for the soil prediction and ecological site name
- [ ] I want the option to "Explore the Data" that will allow me to https://github.com/techmatters/terraso-product/issues/660

**Comment by paulschreiber** [comment]
This is addressed by https://github.com/techmatters/terraso-mobile-client/pull/1446.

**Comment by paulschreiber** [comment]
Assigned this to Ruxandra, since she did the work to implement this.

**Comment by paulschreiber** [comment]
This issue seems like a duplicate of #653.

**Comment by DerekCaelin** [comment]
Closing as addressed by above issues
