### ISSUE TITLE
Build loading indicator for login sync

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1223]
Implement a loading indicator while the app communicates with the server for the log in experience. See parent task for details/related issues.

This would help to address: While logging in, there is typically a 3-5 second delay: https://github.com/techmatters/terraso-mobile-client/issues/435.

## References
https://mui.com/material-ui/react-progress/ 

## Acceptance criteria
- [ ] as a user who is logging in to LandPKS I want to see a loading indicator.

**Comment by shrouxm** [comment]
will be available for QA in builds 170 and up

**Comment by DerekCaelin** [comment]
Lovely. Over to @CourtneyLee333 for her review.

**Comment by CourtneyLee333** [comment]
Much better!
