### ISSUE TITLE
Rename "Home" to "Sites" and Remove "Sign out" option from current bottom navbar

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1224]
Remove "sign out" option from the bottom navbar, because the Capri settings menu (https://github.com/techmatters/terraso-mobile-client/issues/1163) provides a sign out option. Rename "Home" to "Sites".

## Design
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-13162&mode=design&t=zyJpaZLo9E7hxgix-0)

![Image](https://github.com/techmatters/terraso-mobile-client/assets/10799815/facbe082-9fbe-4c34-b909-dab19cc2b824)

## Acceptance critera
- [x] sign out button is removed from bottom nav bar
- [x] home is renamed "Sites"

**Comment by DerekCaelin** [comment]
@tm-ruxandra Note the update to this issue. Very slight addition - change the word "Home" to "Sites". I thought it was trivial enough not to create a new issue.

**Comment by DerekCaelin** [comment]
Reopening briefly for QA by Courtney and me. This passes my expectations - Over to you @CourtneyLee333.

**Comment by CourtneyLee333** [comment]
@DerekCaelin This is fine for now, but I would like a backlog task to space them out more evenly across the navbar.

**Comment by DerekCaelin** [comment]
As @CourtneyLee333 requested I've added this item to the backlog: https://github.com/techmatters/terraso-product/issues/769. Closing, and thank you!
