### ISSUE TITLE
Soil ID - Show "Soil map data not published" (NOTPUB) message

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#1228]
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=6687-36761&mode=design&t=qMvkI8ko5ybPSsWn-0)
![image](https://github.com/techmatters/terraso-mobile-client/assets/5590815/2dd168ae-a05b-4e47-9447-f549d8735d41)

## References:
This is an example NOTCOM location: 35.81690,-111.77010
This is an example NOTPUB location: 43.16850,-78.94876

## Acceptance Criteria
- [x] If there is no soil map data for this location because the data doesn't exist or it is not complete (NOTCOM), then user sees "No soil map data" message instead of soil matches 
(This case is when the API returns [[??]])
- [ ] If soil map data can't be displayed because the data is not published (NOTPUB), then user sees "Soil map data not published" message instead of soil matches 
(This case is when the API returns [[??]])
- [x] This should be the same behavior for Site and Temporary Location

**Comment by knipec** [comment]
@paulschreiber @CourtneyLee333 Could you help fill in the Acceptance criteria where I have "??"s? Thanks! :)

**Comment by knipec** [comment]
@DerekCaelin FYI added this -- it had just been a tasklist item on User Story 666

**Comment by CourtneyLee333** [comment]
I added some detail to the acceptance criteria, but how these scenarios are displayed in the API will need to be written by @shrouxm I think.

**Comment by knipec** [comment]
@DerekCaelin Based on Courtney's proposal yesterday, this should be moved to high priority post-Capri, right?

**Comment by DerekCaelin** [comment]
Jon says that API Should return a response in most scenarios, if blank, fall back to "no soil available at this location". API should also include a response explaining why this is happening.

I suspect that we're fine with the current error warning, which occurs whenever Soil ID does not return a result because there is no soil map data. @CourtneyLee333 do you think we should file a separate enhancement to distinguish between NONCOM and NONPUB scenarios?

**Comment by CourtneyLee333** [comment]
Yes, I think any time we have a reason why there is no soil data we should tell the user that reason.

**Comment by DerekCaelin** [comment]
@knipec can you confirm how our current implementation works? Is it the case that all scenarios where the API returns `""` receive the "No soil map data" message?

**Comment by shrouxm** [comment]
currently the algorithm is not returning whether it's a NOTCOM or NOTPUB situation, just that there's no data available. i don't see an easy change to the soil ID code we could make to return this data

**Comment by knipec** [comment]
I'm not sure exactly what you mean by `""`, but currently the soil ID API can return: 
- soil matches (I think someone told me the algorithm will never return an empty list of soil matches, but if this happens I think we'd just show an empty space instead of the soil tiles or the top match)
- "DATA_UNAVAILABLE", in which case we will show the "No soil map data" message on the soil id sheet and "No matches" elsewhere --> I think this is the case you're referring to?
- "ALGORITHM_FAILURE", in which case we will show the "Can't fetch soil map" message on the soil id sheet and "ERROR" elsewhere

**Comment by DerekCaelin** [comment]
@jjmaynard how much effort would it be to change the algorithm to signal when a location is NOTPUB?

It seems like there are NOTPUB sites that still return soil profiles, like `43.16850,-78.94876`. SoilWeb calls it NOTPUB
![Image](https://github.com/user-attachments/assets/cedb4c7e-f401-420d-aad8-04c6f57ad24f) but the algorithm falls back to STATSGO.

**Comment by DerekCaelin** [comment]
What is an example point where the user should see the Soil Map Not Published Message? (known NOTPUB sites just fall back to STATSGO)

**Comment by DerekCaelin** [comment]
STATSGO has complete coverage, only would show if statsgo failed.

**Comment by DerekCaelin** [comment]
Won't pursue because STATSGO has complete coverage, so this scenario wouldn't arrive.
