### ISSUE TITLE
Soil ID (Site) - Soil Properties Module - table version - no data

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1230]
Provide a blank, table-based version of the soil properties module. 

## References
MVP-izes this isse: https://github.com/techmatters/terraso-mobile-client/issues/1201

## Design
[Figma Playground](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=6856%3A33767&mode=design&t=wi4I6AH7WinjE5Hn-1)

## Acceptance Criteria
- [x] Soil Properties header exists
- [x] Button to “Add soil data” navigates to the site’s “Soil” tab
- [x] Button does not appear for Viewer role
- [x] I see empty rows for 4 columns: Depth (cm), Texture, Color, % Rock Fragments, for each expected depth
- [x] Table can scroll horizontally

**Comment by knipec** [comment]
QA note: May be worth playing around with the site navigation behavior now that the "Add soil data" button is introduced, since it pushes a new sheet onto the navigation stack. For example:
- Site tab > press Explore (goes to Soil ID) > press Button (goes to Soil tab) > go to Site tab > press Explore (screen gets pushed from the left, indicating we're going back to a previous screen on the navigation stack)

I think this is reasonable, and wouldn't suggest changes. Just wanted to note it.

**Comment by DerekCaelin** [comment]
This passed my functional review. @CourtneyLee333 over to you for QA.

Recommend looking at a site called "Airbnb headquarters" to see an empty site in a project with depth requirements as a viewer.

**Comment by CourtneyLee333** [comment]
This passes my functional review as well. My two design concerns:

- The table cells are not wide enough. This shows in the "no data" context as the 100-200 depth wrapping to a second line. 
- When "None Specified" is chosen for a project, should the empty table default to at least one row until a depth is created? Currently, if there is no data, the Soil Properties table shows as just a one pixel line. This could be confusing.

**Comment by CourtneyLee333** [comment]
I have one nitpick here: the table cells need to be wider. In the blank

**Comment by knipec** [comment]
1. Width: I believe this was done by Ruxandra's [PR 1475](https://github.com/techmatters/terraso-mobile-client/pull/1475/files) -- though the emulator I'm using didn't show it wrapping, and I'm not sure how to guarantee that it will work on every possible device :\
2. "None Specified": Done!
![Image](https://github.com/techmatters/terraso-mobile-client/assets/5590815/670bfb27-01b2-4c22-acfd-428b85976cba)

**Comment by CourtneyLee333** [comment]
Regarding the width of the cells, if we can get the specified bits not wrapping on the devices we have available to our team, I'm good with that.

**Comment by DerekCaelin** [comment]
These changes appear to be addressed in v141.
