### ISSUE TITLE
Soil ID (Site) - Soil properties module - table version - color, rock framentation, texture

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1231]
Update soil properties table that was implemented in https://github.com/techmatters/terraso-mobile-client/issues/1230 with data. In the Site context, show user-collected data. 

## Designs
TBD

## Acceptance Criteria
- [x] (Site context) If I have collected data, I see real data reflected in the Texture visualization
- [x] (Site context) If I have collected data, I see real data reflected in the Color visualization
- [x] (Site context) If I have collected data, I see real data reflected in the Rock Fragmentation visualization

## Notes
- For color: there is [a function for that](https://github.com/techmatters/terraso-mobile-client/blob/ada733f533d008d1b02738aaa26cba949556be63/dev-client/src/screens/SoilScreen/ColorScreen/utils/munsellConversions.ts#L201-L215) and [a longer explanation](https://github.com/techmatters/terraso-mobile-client/blob/ada733f533d008d1b02738aaa26cba949556be63/dev-client/src/screens/SoilScreen/ColorScreen/utils/munsellConversions.ts#L18-L42) in the file munsellConversions.ts

**Comment by DerekCaelin** [comment]
This passes my review. @CourtneyLee333 you can use site `PMC 1` as an example of what a fully filled out data table looks like

**Comment by CourtneyLee333** [comment]
This passes my review, with the comments already made about the cells of the table needing to be wider to accommodate without wrapping:
- 100-200 depth label
- Sandy Loam, Loamy Sand, etc.. texture (a 3-word texture is fine to wrap)
- Full Munsell value

**Comment by DerekCaelin** [comment]
wrapping (and other qualities @CourtneyLee333 highlighted) are addressed so I'm going to call this done. Thank you!
