### ISSUE TITLE
Horizontal Icon Button doesn't have consistent hover/tap styling behavior

### ISSUE THREAD

**Issue by tm-ruxandra** [techmatters/terraso-mobile-client#1233]
### App Version

118

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

The "Horizontal Icon Button" is used in several locations. When the user "hovers" (taps but does not release) on the icon, it displays a background color that does not extend to the text. This causes a confusing user experience, because the text is also clickable.

![Screenshot_1714690457](https://github.com/techmatters/terraso-mobile-client/assets/161085305/d73a0884-6ff3-426f-a1c9-1f950a2b7a19)

### Steps to Reproduce

1) Navigate to an occurrence of this button (e.g.: the "delete" prompt for pinned notes, or the privacy links in a project's privacy info page).
2) Press down on the icon without releasing, and observe that the background color only extends to the icon.
3) Click on the text and observe that it is clickable despite the affordance implied by the icon's background color.

### Expected behavior

The clickable area is consistent with the area that receives a background color when the user presses on the button.

### Actual behavior

The background area does not reflect the actual clickable area.

**Comment by knipec** [comment]
Going thru bugs and wondering, do you consider this part of the components library work? @tm-ruxandra @CourtneyLee333

**Comment by tm-ruxandra** [comment]
@knipec I think this ticket will be obviated once we have finalized designs for the button components.

**Comment by knipec** [comment]
Closing, as Ruxandra and Courtney will be addressing this with the components library work
