### ISSUE TITLE
Design updates to Edit Site Settings from should match other similar forms

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#1234]
## Issue
Implement the same changes for the Site settings form as in Create Site, Create Project, and Edit Project after [#534](https://github.com/techmatters/terraso-mobile-client/issues/534):
- [ ] Site Name field needs `required` indicator when it is empty
- [ ] Site Name field indicates you need more than 3 characters
- [ ] Set maximum character length for Site Name to 50 characters
- [ ] Save button should be disabled until required field (Site Name) is completed. 
- [ ] I imagine we'd want to use Formik (as we do in the other 3 forms) to do this.

### (but make a separate tech debt issue if it's not easy to do this as part of this Issue):
- Refactor: Make and use a reusable component for the save button
- Fix (minor): Standardize the positioning of the save button
- Refactor: Confirm that + make it clear that SiteSettingsScreen doesn't need to handle Viewer/Contributor permissions because the screen itself is inaccessible to non-Managers (or unify with ProjectSettingsScreen, which does have userRole logic but it's kinda redundant. Should we remove the userRole logic from EditProjectForm?)
- Refactor: Unify how the 4 different forms treat the FormikProps 
- Refactor: Rename and move files of components to refer to the same concepts in the same hierarchy across Project/Site and Create/Edit.
Like, it's weird that in the hierarchy below, it's "CreateSiteView > Formik > CreateSiteForm" but "CreateProjectForm > Formik > FormContainer" 

## Misc brain dump 
- Here are the 4 related component hierarchies (roughly):
  - **CreateProjectScreen** > CreateProjectForm > Formik > FormContainer > Button + ProjectForm > various form fields
  - **ProjectSettingsScreen** > EditProjectForm > Formik > FormRadioGroup + Button + SharedFormComponents > FormInput + FormTextArea
  - **CreateSiteScreen** > CreateSiteView > Formik > CreateSiteForm > Button
  - **SiteSettingsScreen** > Button + this doesn’t even use Formik

**Comment by knipec** [comment]
Do you consider this part of the components library work? If so, can we close this? @tm-ruxandra @CourtneyLee333

**Comment by CourtneyLee333** [comment]
Yes.

**Comment by knipec** [comment]
Great, closiiiiing :)
