### ISSUE TITLE
Build account deletion screen

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1263]
Create new screen to inform user of the consequences of account deletion.

## Design
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=6995-35053&mode=design&t=WGxtTpDKGGOpReFy-0)

## Acceptance Criteria
- [x] new page for the deletion experience
- [x] text field to enter email account
- [x] hook up confirmation button to Hubspot service built in: https://github.com/techmatters/terraso-backend/issues/1112
- [x] confirmation button is disabled until email account entered matches user's email
- [x] cancel button to return to the new page

**Comment by DerekCaelin** [comment]
Ruxandra expressed an interest in this

**Comment by CourtneyLee333** [comment]
This looks great! A few things:
- There seems to be an extra line break between the paragraphs on Delete Account screen. 
- I'm assuming that the "pending" status will be handled in another issue. 
- I didn't see the support ticket go to Hubspot as I had expected to see it [here](https://app.hubspot.com/contacts/9151742/objects/0-5/views/all/list) for my account courtney@tevhmatters.org. 
- I also still seem to be subscribed to the LandPKS newsletter.

**Comment by tm-ruxandra** [comment]
@CourtneyLee333 Yes, the pending status is handled in #1179 which I guess didn't go out in this build. For the second two issues I'd refer you to @paulschreiber since he handled the backend / hubspot integration side.

For the paragraph spacing I'm fine with making a trivial followup PR to change it, since it's a trivial one-liner.

**Comment by CourtneyLee333** [comment]
Paragraph spacing looks good!

**Comment by CourtneyLee333** [comment]
Noting here also that the Delete button is no longer working. See notes on #1179
