### ISSUE TITLE
Soil ID - Top Soil Matches - Notice - No Soil Map Data

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1271]
In the Top Soil Matches module of Soil ID page, notify the user that there is no Soil ID data for this site:

`There is no soil map data available for this site, so LandPKS cannot generate soil matches for this site. Data can still be collected for this site, and if soil map data becomes available in the future, soil matches will appear here.
Soil resources for Native lands:`

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=3800-22060&t=g8jmtP77fdOK01Fv-0)

#### Design as of 5/9/2024, please see Figma for most up-to-date version
<img width="342" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/10799815/5f4cf85c-d672-4cb6-9905-f9e3ecdd3069">

## Acceptance Criteria
- [ ] When there is no Soil ID information for a site, display the warning
- [ ] Link to Native Lands (use External Link Component)

**Comment by paulschreiber** [comment]
This is done is 1.0.
