### ISSUE TITLE
Make ExternalLink consistent with design

### ISSUE THREAD

**Issue by tm-ruxandra** [techmatters/terraso-mobile-client#1289]
Standardize usage of links to external URLs, using `ExternalLink` component. Update component to [match design.](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7242-19281&m=dev).

Go through the mobile codebase and replace any non-standard ad-hoc equivalents with these components which correspond to known design spec elements.

**Comment by paulschreiber** [comment]
question: would it make sense to have `<CloseButton size="...">` instead?

**Comment by tm-ruxandra** [comment]
> question: would it make sense to have `<CloseButton size="...">` instead?

This was the case originally, however I ended up deciding it would be better to have them as two different components. First, there's no material value in sharing the code between them (it's trivial). Second, the buttons are used in completely different contexts - it's not like they're two variants of one button with similar usage (like an action button colored red or green if its action is deletion or creation). I think it'll avoid more confusion in the long term to talk about a "close button" or "big close button" vs. "close button" having to remember if it's supposed to have a particular size in some context.

**Comment by DerekCaelin** [comment]
Related issue: https://github.com/techmatters/terraso-mobile-client/issues/1395

**Comment by DerekCaelin** [comment]
@tm-ruxandra I checked the data privacy info sheet. To my eye the ExternalLink matches the design. Over to @CourtneyLee333

**Comment by CourtneyLee333** [comment]
@tm-ruxandra Can you tell me what build to find this in?

**Comment by tm-ruxandra** [comment]
@CourtneyLee333 should be in anything after v170beta

**Comment by CourtneyLee333** [comment]
Looks great!
