### ISSUE TITLE
Text fields - enforce max character limits behavior

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1318]
Update text field behavior.

## Acceptance Criteria

- [x] Project name (max 50 char)
- [x] Project description (max 72 char)
- [x] Site name (max 50 char)
- [x] Input fields should disallow more characters to be entered once the user hits the max.
- [ ] show character counter while typing

From: Courtney's review of https://github.com/techmatters/terraso-mobile-client/issues/534.

**Comment by shrouxm** [comment]
@DerekCaelin [this issue](https://github.com/techmatters/terraso-mobile-client/issues/688) already exists for updating the text input field component, which i think should be tracked as separate work from these max char limit changes

**Comment by DerekCaelin** [comment]
Closing this issue in favor of: https://github.com/techmatters/terraso-mobile-client/issues/688

**Comment by DerekCaelin** [comment]
No!

**Comment by paulschreiber** [comment]
Limits are done. Character counter will be part of https://github.com/techmatters/terraso-mobile-client/issues/1718

**Comment by DerekCaelin** [comment]
Confirmed the character limits and the disallowing adding more characters. @CourtneyLee333 FYI, but I think this is small enough that you don't need to bother looking if you don't feel compelled. Will remove the character counter as acceptance criteria since it's tracked in https://github.com/techmatters/terraso-mobile-client/issues/1718

**Comment by CourtneyLee333** [comment]
This and the character counter should be considered part of the component work.

**Comment by DerekCaelin** [comment]
Are site/project name and description fields currently using a component?
