### ISSUE TITLE
"Unexpected soil color" should not give same suggestion as your result

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#1319]
### App Version

current

### Platforms

- [ ] iOS
- [ ] Android
- [X] iOS simulator
- [ ] Android emulator

### Description

(Link to slack discussion about it: [here](https://tech-matters.slack.com/archives/C0376RCCXD2/p1715634257552149))

### Steps to Reproduce

1. (I used iOS simulator, not sure if it repros on other platforms)
2. Use the image in the "Additional context" section (probably can just crop to the "Reference" box and the "Soil" box in the screenshot itself)
3. Choose "Dry" and "No" for radio buttons, and press the Analyze button

### Expected behavior

Not sure, but either: 
- An unexpected soil color modal with differently named colors between "Suggestion" and "Your result", or
- No unexpected soil color modal

### Actual behavior

Unexpected soil color modal with: 
- Same named color for both ("5Y 7/2")
- Similar looking color swatches

### Additional context

Using the first image and settings  ---------------------> After pressing the Analyze button, I received this modal:
![Screenshot 2024-05-13 at 2 05 20 PM](https://github.com/techmatters/terraso-mobile-client/assets/5590815/2652368a-ea1c-4179-ab77-60b345239e91)  --> ![Screenshot 2024-05-13 at 2 02 44 PM](https://github.com/techmatters/terraso-mobile-client/assets/5590815/9a51c31e-1a2e-4335-ae86-490e1607d4f7)

**Comment by DerekCaelin** [comment]
We think this is resolved; can't repro after Garo's changes
