### ISSUE TITLE
Site title should not get cut off or overlap settings icon in the AppBar

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#1320]
### App Version

v124

### Platforms

- [ ] iOS
- [ ] Android
- [ ] iOS simulator
- [X] Android emulator

### Description

When viewing info about a site, the site title should wrap nicely in the width of the app bar with and without settings icon, no matter what the title is

### Steps to Reproduce

1. Name a site "Starts with standard depth intervals"
2. On an Android Pixel 3a emulator (maybe works on others too), go to that Site's location dashboard screen
3. Look at the title in the AppBar

### Expected behavior

- Title wraps in the app bar, like it does with other long strings (such as with other long names) and does not get cut off. 
- When you are the owner of a site (or manager of a project containing a site), the title should not overlap the settings icon.
- Also, when you are not the owner of a site, title should look reasonable when the settings icon is not there

### Actual behavior

- Sometimes title gets cut off
- Sometimes title overlaps settings icon

### Additional context

![image](https://github.com/techmatters/terraso-mobile-client/assets/5590815/0a7da077-3b2e-45ae-8de6-b7dfcb8b9e9e)

![image](https://github.com/techmatters/terraso-mobile-client/assets/5590815/7681aea1-999b-4f84-af48-9f5106571b68)

**Comment by knipec** [comment]
@CourtneyLee333 @tm-ruxandra Is this covered by components library work? If so, let's close this?

**Comment by tm-ruxandra** [comment]
@knipec I think it is, @CourtneyLee333 let's just be sure that the expected text wrap behavior is documented in the app bar component

**Comment by CourtneyLee333** [comment]
https://github.com/techmatters/terraso-product/issues/946

**Comment by knipec** [comment]
Added a note to ^ that issue; closing this one
