### ISSUE TITLE
"create site" or "rename site" form submit fails silently

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1326]
### App Version

1.0.125

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

When I fill out the form to create or rename a site and I hit the save button, the form remains open and the site is either not made or not renamed. 

### Steps to Reproduce

**Create**
1. on Map, tap a place
2. select "create site" on popover
3. fill out form
4. hit save button
5. see issue

**Rename**
1. On home screen, select a site where you have management role
2. go to settings
3. rename site
4. select save
5. see issue

### Expected behavior

Form closes, site is either made or renamed.

### Actual behavior

User remains on the form, it doesn't appear to be submitted. 

### Additional context

I can still add data inputs.

**Comment by paulschreiber** [comment]
Staging backend was outdated. It has been updated.
