### ISSUE TITLE
Fix major inconsistencies with ExternalLink

### ISSUE THREAD

**Issue by tm-ruxandra** [techmatters/terraso-mobile-client#1329]
The `ExternalLink` component has several issues as implemented [compared to the component design](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7242-19281&m=dev):
- The text does not have a visible 'pressed' state
- The icon has a 'pressed' state, but it does not match the given style, and pressing the icon does nothing
- The text does not appear to have the correct font weight

Fix as many of these as possible to avoid confusing users. Also, rename it to `ExternalLinkButton` to match updated design terminology.

**Comment by paulschreiber** [comment]
Was this fixed with https://github.com/techmatters/terraso-mobile-client/pull/1778?

**Comment by tm-ruxandra** [comment]
@paulschreiber yes, this can now be closed.
