### ISSUE TITLE
Remove Tooltips from application and replace with Info Overlay Sheets

### ISSUE THREAD

**Issue by tm-ruxandra** [techmatters/terraso-mobile-client#1330]
Per the [components design](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7281-34294&m=dev), remove tooltips and replace with info sheets.

**Comment by knipec** [comment]
From Ruxandra: We decided we actually don't want to do this
