### ISSUE TITLE
Make icon buttons consistent with component design

### ISSUE THREAD

**Issue by tm-ruxandra** [techmatters/terraso-mobile-client#1331]
Standardize our icon button usages to match [the design specification](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7274-34080&m=dev).

- Make `SmallIconButton` and `MediumIconButton` components as a base foundation for the others.
- Use standard variant names for the background / no-background versions
- Update the other icon buttons in service to use these base components. Coordinate with designer to document any usages which were previously-undocumented.

**Comment by CourtneyLee333** [comment]
@tm-ruxandra is this available in v181?

**Comment by tm-ruxandra** [comment]
@CourtneyLee333 v182 should have it. Not sure why it isn't available yet....

**Comment by CourtneyLee333** [comment]
Looks good!
