### ISSUE TITLE
Make InternalLink consistent with component design

### ISSUE THREAD

**Issue by tm-ruxandra** [techmatters/terraso-mobile-client#1332]
The `InternalLink` component does not precisely match [its design specifications](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7249-19286&t=KubZnYZzlmVx22S0-0).

- Fix the pressed state to have the correct color

**Comment by DerekCaelin** [comment]
I can see a color change but can't verify if it's the right one. (red/green colorblindness). Over to @CourtneyLee333

**Comment by tm-ruxandra** [comment]
@CourtneyLee333 should be in anything after v170beta

**Comment by CourtneyLee333** [comment]
Looks good!
