### ISSUE TITLE
Remove "Last Modified" from site popover

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1341]
Remove "Last Modified" from site popover. To be reintroduced post Capri: https://github.com/techmatters/terraso-product/issues/781

![image](https://github.com/techmatters/terraso-product/assets/10799815/9d2a7030-0071-4875-819b-62bcd92faa08)

**Comment by paulschreiber** [comment]
This is fixed in v126.

**Comment by DerekCaelin** [comment]
Confirmed fixed huzzah!
