### ISSUE TITLE
Remove "Last Modified" from Sites Card - Project "Sites" tab

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1349]
Remove "Last Modified" field from cards in the sites in the project tab. To be re-introduced post-Capri: https://github.com/techmatters/terraso-product/issues/781

![image](https://github.com/techmatters/terraso-mobile-client/assets/10799815/70cfb1ae-3419-4827-a568-899e3c95e45c)

**Comment by paulschreiber** [comment]
Duplicate of #1341. (There is only one card component.)
