### ISSUE TITLE
Frontend should hide site data entry for Viewers

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#1350]
## Repro: 
1. Create a Project with a Site. 
2. Add another user (who you can log in as) to the project as a Viewer
3. Log out and log in as that other user from the previous step
4. Go to the site and one of the data entry screens (like slope > steepness)
**Expected**: No UI that makes me think I can actually input data. 
**Actual**: A "Done" button. A button for manual entry that I can put numbers into but doesn't work. A slope meter button that... well on my machine it causes a crash but maybe that's just the state of my branch?

## Additional info:
This is not as egregious because the permissions checks on the backend will prevent the changes from making it to the database. Apparently this also prevents selections from being reflected in the app UI, so that's nice behavior, but in a kinda hacky way.

But I shouldn't see editing-specific UI if I am in a role that cannot make edits. I believe this is the full list of such UI elements in the Site tabs that should be altered or removed for Viewers:
- Slope > Steepness: (1) "Done" button, (2) "Manual" button, (3) "Slope meter" button
- Slope > Shape: (1) "Done" button
- Soil: (1) ... menu for each depth interval
- Soil > Vertical Cracks: (1) dropdown, (2) grayed out "Done" button
- Soil > Texture/Rock fragment: (1) Texture dropdown, (2) "Use guide" button?
- Soil > Color: (1) "Enter values" button, (2) "Use guide" button, (3) button to take or upload a photo
- Notes: (1) pencil icon to edit a site note
- Also, something about the interaction between the frontend and backend seems to handle the Pressable images in the Rock Fragment, Slope Steepness, and Shape screens. But would be nice to have frontend code that makes it explicit.

**Comment by paulschreiber** [comment]
Slope Steepness fixed with https://github.com/techmatters/terraso-mobile-client/pull/1834

**Comment by DerekCaelin** [comment]
This appears resolved!
