### ISSUE TITLE
Remove data inputs from sites and projects in Capri

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1382]
For Capri, remove the inputs that wont be included at launch:

- Structure
- Carbonates
- pH
- Electrical Conductivity
- SOC/COM
- SAR
- Limitations
- Land Use / Land Cover
- Photos

Input toggles are found:
- Unaffiliated site: in soil depth intervals menu
- Affiliated site: In project data collection requirements

**Comment by paulschreiber** [comment]
"Disable" and "hide" are two different things. You can do one or the other, but not both.

**Comment by DerekCaelin** [comment]
I've made it "hide" - there should be no option to add the above data inputs in Capri.
