### ISSUE TITLE
Remove "Last Modified" element from data inputs

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1385]
For Capri, remove "Last modified by" element from data input screens. To be reintroduced later: https://github.com/techmatters/terraso-mobile-client/issues/1384#issuecomment-2120886782

## Acceptance Criteria
- [x] As a user I don't want to see "Last Modified by" in
   - [ ] Slope steepness
   - [ ] Slope shape
   - [ ] Texture/Fragmentation
   - [ ] Color
   - [ ] Vertical Cracks

**Comment by paulschreiber** [comment]
This is a duplicate of #1383.
