### ISSUE TITLE
Notes screen: Use correct delete button component 

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1395]
Use correct delete button component for notes screen.

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-12812&t=v5SvKfQz9HmiO0MY-0)
[Component Library](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7202-34072&t=v5SvKfQz9HmiO0MY-0)

**Comment by paulschreiber** [comment]
This was done for 1.0.
