### ISSUE TITLE
Inconsistent scroll behavior on screens / sheets containing soil properties table

### ISSUE THREAD

**Issue by tm-ruxandra** [techmatters/terraso-mobile-client#1397]
### App Version

128

### Platforms

- [ ] iOS
- [ ] Android
- [X] iOS simulator
- [X] Android emulator

### Description

The soil ID info sheets don't allow the user to scroll the table horizontally on Android or IOS. The soil ID screen does allow scrolling the table horizontally on android, but does not allow the screen to scroll vertically.

### Steps to Reproduce

1. Navigate to a site soil ID screen on Android.
2. Observe that the screen does not scroll vertically.
3. Open the info sheet.
4. Observe that the table does not scroll horizontally.
5. Navigate to the info sheet on IOS.
6. Observe that the table does not scroll horizontally.

### Expected behavior

The soil properties table can scroll horizontally, and the surrounding content can scroll vertically.

### Actual behavior

One scroll direction does not work as expected.

**Comment by DerekCaelin** [comment]
This is addressed in Android 142, still waiting to get access to iOS

**Comment by DerekCaelin** [comment]
Resolved in 142 on iOS
