### ISSUE TITLE
Implement filters for list views

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#143]
# Description

Certain screens (for example, Project List View and Project Sites) have list views with an associate filter. This issue will be to implement a generic filter component that can be used for all of these views.

# Criteria
- [ ] Text entered should filter associated list view; probably makes sense to use a context here?

**Comment by ltseng** [comment]
Needs a size

**Comment by ltseng** [comment]
Also waiting on one of David's PRs

**Comment by ltseng** [comment]
Is this why I was able to find this particular bug?

https://github.com/techmatters/terraso-mobile-client/issues/537
