### ISSUE TITLE
Placeholder - soilID algorithm work

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1430]
Placeholder issue to preserve time to work on Soil ID algorithm

Garo - "jon is currently investigating some potential bugs in the soil ID algorithm, i'm not sure how that's going to go so i'd like to reserve some capacity for the sprint in case i need to do any work on the algorithm myself"

**Comment by shrouxm** [comment]
i spent a lot of time this sprint surfacing bugs to jon, which he has fixed many of, and the algorithm is acceptably robust for launch now, so i will mark this done!
