### ISSUE TITLE
Use mixed case instead of all caps for labels in location popover

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1445]
Use mixed case capitalization for labels in location popover (currently, all caps).

[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-13278&t=ttaXBjiWPjZc8JHS-0)

## Acceptance Criteria
- [ ] In location popover, used mixed case capitalization for Soil ID Top Match, Ecological Site Top Match, Elevation

**Comment by DerekCaelin** [comment]
Meets my expectation - @CourtneyLee333 over to you

**Comment by CourtneyLee333** [comment]
Perfect. Much less shouty.
