### ISSUE TITLE
Add Team Member experience: update copy, change styles for Capri

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1447]
Align Add Team Member experience with designs for capri add team members experience

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-13057&t=o6LISltalYg1iugs-0)

## Acceptance Criteria
- [ ] button once user has entered name?
- [ ] heading size matches design
- [ ] text copy matches design
- [ ] text field matches design (use text field component?)
- [ ] trash can matches design
- [ ] save button matches design
### Carissa's notes
- 1st "Add Team Member" screen:
    - Update design upon first opening the screen 
    - Use new up-to-spec TextInput component
    - Red text "Enter a valid email address" shows up on open, and when user has not entered an email in a format considered valid (by the yup library)
    - Next button is disabled until email address has a valid email format entry
    - Next button triggers backend validation and red text shows up when email is not a terraso user ("No Terraso account found"), or when user is already in the project ("Already a team member")
    - Next button goes to the 2nd screen if user exists and can be added to the project
    - User can't get to this screen unless they're a Manager role
- 2nd "Add Team Member" screen (to choose role):
    - Looks very similar to "Manage Team Member" screen
    - Back arrow in app bar goes back to 1st "Add Team Member" screen, with email address filled out
    - Cancel button navigates back to 1st "Add Team Member" screen, with email address filled out
    - Add button adds user and navigates back to "Project Team" screen
- "Manage Team Member" screen: 
    - Add title
    - Include user photo
    - Reorder and slightly restyle radio button text
    - Minor spacing tweaks
    - Mostly fix "Remove from project" trash can button styling
### Didn't do as part of this
- "Manage Team Member" screen:
    - Put the Save button in exactly the right place (seems like a bigger pass of the app holistically)
    - Super duper pixel perfect

**Comment by knipec** [comment]
Most recent change is in v147

**Comment by CourtneyLee333** [comment]
This looks great!

**Comment by knipec** [comment]
Yay! Gonna close this.
