### ISSUE TITLE
Connect site transfer to backend

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#145]

**Comment by ltseng** [comment]
Ready for review tomorrow

**Comment by ltseng** [comment]
Assuming this will be ready in the next release?

**Comment by ltseng** [comment]
This can be closed, I'll do my testing in the parent issue.

**Comment by david-code** [comment]
> Assuming this will be ready in the next release?

Yep

**Comment by ltseng** [comment]
Don't forget https://github.com/techmatters/terraso-mobile-client/issues/566! (and let me know when these are ready to test)
