### ISSUE TITLE
On sites screen, set max height of bottom sheet to 75% of screen height

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1483]
The bottom sheet on the sites screen should never go higher than 75% of the screen, so that the user always remembers that the map is present and tapping on the map remains a way for the user to minimize the bottom sheet.

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-13123&t=hrR0pAW7WPaCWrxd-0)
![image](https://github.com/techmatters/terraso-product/assets/10799815/9e4273ad-2734-4364-b145-35d5dd70f27c)

## Acceptance Criteria
- [x] Bottom sheet on sites screen extends only as high as 75% of the screen, so the user can always interact with the map

**Comment by DerekCaelin** [comment]
@paulschreiber in what bild should I expect to test this?

**Comment by DerekCaelin** [comment]
Meets my review. @CourtneyLee333 ?

**Comment by CourtneyLee333** [comment]
Beautiful!
