### ISSUE TITLE
Bottom sheet on home screen should initially open to 50% height of screen

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1485]
On the Sites screen, the bottom sheet should default load to show 50% map and 50% sheet. Currently the sheet makes up about 75% of available space.

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-13231&t=hrR0pAW7WPaCWrxd-0)
![image](https://github.com/techmatters/terraso-product/assets/10799815/be2593b7-99b1-4b64-9c56-2020467166cf)

## Acceptance Criteria
- [ ] when viewing the sites screen default view, bottom sheet should take up about 50% of the available space.

**Comment by DerekCaelin** [comment]
This meets my expectation, @CourtneyLee333 over to you

**Comment by CourtneyLee333** [comment]
Perfecto!

**Comment by DerekCaelin** [comment]
Closing! Thank you.
