### ISSUE TITLE
Remove units of measurement and copy project download link from project settings for Capri

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1488]
From ProjectDashboard: Settings screen, remove:
- units of measurement
- copy project download link

Since these elements will not be included at launch

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-13002&t=XyuvjeoSuNuykt3x-0)

<img width="314" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/10799815/5a8606d2-8e10-4401-8051-d6c2309ebdae">

## Acceptance Criteria
- [ ] As a user on the Project settings screen, I should not see either the units of measurement or the copy project download option, so I can't interact with elements that have't been fully implemented yet.

**Comment by paulschreiber** [comment]
The remove download link was done as part of https://github.com/techmatters/terraso-mobile-client/pull/1449
Measurement units removed in https://github.com/techmatters/terraso-mobile-client/pull/1490

**Comment by DerekCaelin** [comment]
Got it, will close this as a duplicate:

**Comment by paulschreiber** [comment]
Those are PRs. This is not a duplicate.

**Comment by DerekCaelin** [comment]
@paulschreiber in 142, I see "Units of Measurement" in project settings:

1. Be a project manager
2. go to project
3. go to settings
4. see issue

**Comment by paulschreiber** [comment]
Looks like it got lost in a merge conflict. Please check again in 143.
