### ISSUE TITLE
Remove tripledot settings icon for viewers of affiliated sites

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1494]
Users with "viewer" role on affiliated sites should not see triple-dot settings menu on depth intervals.

<img src="https://github.com/techmatters/terraso-mobile-client/assets/10799815/8a7e5a65-bbe4-4511-86ab-fa683c054bce" width="200px">

## Acceptance criteria
- [ ] as a user with "viewer" role I should not see the icon that reveals the settings overlay sheet, because I don't have permissions to edit this information.

**Comment by CourtneyLee333** [comment]
Assuming this will be in v159.

**Comment by CourtneyLee333** [comment]
Looks good!
