### ISSUE TITLE
Create depth - "Required" signifier should appear by default

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1496]
The "required" signifier should appear by default when creating depth intervals, but it only appears after the user enters and clears text.

## Steps to reproduce
1. Create a project
2. Set "none specified" for depth intervals
3. add site to project
4. go to site as contributor
5. under "soil" tab add depth interval
6. look at modal
7. see issue

## expected behavior
 "Required" shows by default
<img width="312" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/10799815/a3dd3db8-d41c-4dd2-b93d-3d530ee96626">

## Actual behavior
Required only shows up when user enters and clears text

**Comment by knipec** [comment]
I'm just going through unprioritized bugs and: 
Is this breaking with UX convention? If so, do we still want to do this? @CourtneyLee333 
Also, do you consider this part of the components library work? @tm-ruxandra

**Comment by knipec** [comment]
Sounds good, thanks! Closing :)
