### ISSUE TITLE
Research - implement capri add team member experience

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1505]
Review [figma ](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=8268-31690&t=ooKfIwjwHAHAMDDn-0) and estimate a size to implement [this task](https://github.com/techmatters/terraso-mobile-client/issues/1447). If size is significant to implement (>5 effort) propose smaller scope implementation. 

## Acceptance criteria
- [ ] review
- [ ] size
- [ ] (Optional) propose alternate smaller implementation method

## Carissa's notes
Moved to #1447

**Comment by knipec** [comment]
Ok I kinda did this just as I implemented, so see #1447 for everything
