### ISSUE TITLE
Project screens need correct background

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1506]
### App Version

1.0.136

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

The background color of the screens in Project Management should be as follows. This includes the additional screens in the workflow.

- Inputs: #ffffff
- Sites: #e0e0e0
-  Team: #ffffff
- Settings: #ffffff

**Comment by CourtneyLee333** [comment]
@paulschreiber Teams tab still has light grey background below the team member list. Should be white all the way.

**Comment by paulschreiber** [comment]
Fixed.
