### ISSUE TITLE
Text shouldn't look different on Android vs iOS vs Figma

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#1537]
Issues:
- Text appears to be a different font between iOS and Android. This is especially noticeable looking at the zeroes on the "100%" on the SoilMatchTile
- Line spacing is also inconsistent between Figma and the app, even though we are using the same values for CSS styling attributes
- Font size also seems slightly different between Figma and the app (as font size was noted as rather small in [this comment](https://github.com/techmatters/terraso-mobile-client/pull/1581#discussion_r1643428171))
- Maybe there are others? 
- After doing this, may want to revert the change in [PR 1538](https://github.com/techmatters/terraso-mobile-client/pull/1538) to pixel-perfect match the design again (or just use non-px units in general, but that may be its own thing)

Thoughts: 
- I'm wondering if this is a nativebase thing. I vaguely recall that when using <Text> from react-native instead of native-base, the text would look different, but haven't pursued that yet.

Image showing Figma, iOS, and Android (from left to right):
![Screenshot 2024-06-10 at 1 26 11 PM](https://github.com/techmatters/terraso-mobile-client/assets/5590815/5b43879a-e7b4-4b77-8ed5-e3b9ec6584e5)

**Comment by knipec** [comment]
Going thru bugs and wondering, do you consider this part of the components library work? @tm-ruxandra @CourtneyLee333

**Comment by tm-ruxandra** [comment]
@knipec This is now redundant with https://github.com/techmatters/terraso-product/issues/909

**Comment by knipec** [comment]
Great, closing this
