### ISSUE TITLE
Implement capri soil depth presets

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1541]
Update presets and defaults for depth intervals in dropdowns for projects and unaffiliated sites. See parent issue for details.

## References
[2024/06/06 - Derek Courtney - Depth Interval Presets and Defaults](https://docs.google.com/document/d/1Ae1DuAVeAtpUsB06vQctzqgdwFBkx0Fy34JlT0LK-SQ/edit)

## Designs
[Figma - Project ](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-12975&t=754RJj1snmtTsV5a-0)
[Figma - Unaffiliated Site](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=8396-29402&t=yAGxhRYDhFVywIGv-0)

## Acceptance Criteria
- [x] In Project "Soil Pit Depth Intervals" and unaffiliated sites
   - [x] Rename "NRCS" to "NRCS/GSP"
   - [x] Make NRCS/GSP the default 
   - [x] Remove "LandPKS" 
   - [x] Add "BLM Monitoring Standard", set depths to:
       - 0-1 cm
       - 1-10 cm
       - 10-20 cm
       - 20-50 cm
       - 50-70 cm
 

## Eng notes
- On both project and site level, there are depth interval presets (enum of possible preset values)
- We're removing LPKS -- this would break existing sites that use the LPKS preset. Could write a data migration on the backend to turn it into custom. We could do that after checking in the code that would break it.
- change enums in the backend -- get auto-generated to schema.graphql from project_soil_settings.py --> They don't seem to be used anywhere except to generate test data
- soilIdTypes.ts DETPH_PRESETS 
- graphql.ts: A site level one and project level one? SoilId...DepthIntervalPresetChoices
- constants.ts DEPTH_INTERVAL_PRESETS

**Comment by paulschreiber** [comment]
Please verify in 168.

**Comment by DerekCaelin** [comment]
This meets my expectation. Over to @CourtneyLee333

**Comment by DerekCaelin** [comment]
Since the BLM monitoring standard was a part of this task, I'll reopen it until the bug is addressed

**Comment by DerekCaelin** [comment]
Possibly related bug: https://github.com/techmatters/terraso-mobile-client/issues/1830

**Comment by DerekCaelin** [comment]
@knipec OK, now that Courtney has OK'd and #1829 and #1830 are addressed, this issue can be closed
