### ISSUE TITLE
Reanimated generates reduceMotion console warning

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-mobile-client#1548]
This console warning is generated
```
 WARN  [Reanimated] Tried to modify key `reduceMotion` of an object which has been already passed to a worklet. See 
https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#tried-to-modify-key-of-an-object-which-has-been-converted-to-a-shareable 
for more details.
```

**Comment by paulschreiber** [comment]
This is a bug in the bottom sheet library:
https://github.com/gorhom/react-native-bottom-sheet/issues/1854
https://github.com/gorhom/react-native-bottom-sheet/pull/1848

**Comment by Quyet114** [comment]
import { LogBox } from 'react-native';
function App(): React.JSX.Element {
  LogBox.ignoreLogs([
    '[Reanimated] Tried to modify key `reduceMotion` of an object which has been already passed to a worklet.',
  ]);
    return (  )
}
  use in App.tsx

**Comment by paulschreiber** [comment]
@Quyet114 that does not work. You can use d a regex like thos:
```js
LogBox.ignoreLogs([
  /^[Reanimated] Tried to modify key `reduceMotion` of an object which has been already passed to a worklet/,
]);
```
