### ISSUE TITLE
Update "depth interval" verbiage

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1579]
The existing text in the app uses "depth", "interval", and "depth interval" inconsistently. Consulting some industry standard materials we have it seems that "depth" is the appropriate term. The following screen shots show where the term "interval" is used and should get deleted. Note that "depth intervals" should get changed to "depths".

![Image](https://github.com/techmatters/terraso-product/assets/8915145/90e791eb-276d-48d0-b827-8b650ed63757)

![Image](https://github.com/techmatters/terraso-product/assets/8915145/deec60c8-92e1-4388-b7d7-6ec41006240b)

![Image](https://github.com/techmatters/terraso-product/assets/8915145/debe5b37-d302-4d12-8520-0a58fb5b8e67)

![Image](https://github.com/techmatters/terraso-product/assets/8915145/fd5afbf5-8403-4ca9-b75e-be2309c76e43)

![Image](https://github.com/techmatters/terraso-product/assets/8915145/0e38d1cf-6f32-449e-b8e8-75f4066dc951)

**Comment by CourtneyLee333** [comment]
@paulschreiber should I be seeing this in v144?

**Comment by paulschreiber** [comment]
@CourtneyLee333 It will be in 145. Release notes for 144: https://github.com/techmatters/terraso-mobile-client/releases/tag/v144

**Comment by CourtneyLee333** [comment]
I'm no longer seeing the Transfer Sites to Project confirmation dialog. Will make a separate bug report. Otherwise everything looks good!
