### ISSUE TITLE
Site Notes screen has wrong color button

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1590]
Data Input: Notes needs our primary green color button as seen in the Figma design:

![Image](https://github.com/techmatters/terraso-mobile-client/assets/8915145/0b478fb1-67e2-4cf8-85b5-04f25451871a)

**Comment by paulschreiber** [comment]
This is fixed in https://github.com/techmatters/terraso-mobile-client/pull/1553
