### ISSUE TITLE
Soil ID match tile percentage should avoid wrapping in more cases

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#1635]
### Repro 
On certain devices, on the "Soil ID" page, the match percentage on the `SoilMatchTile` will wrap instead of staying on one line, even if there is a reasonable amount of space to accommodate it. 
It will more likely happen with "100%", but depending on the phone's size settings it may happen with 2-digit numbers as well
Decide what layout logic to use to satisfy: 
- Percentage doesn't wrap (unless the screen is very narrow, or the font size is larger than we want to support)
- Columns still line up

![image](https://github.com/techmatters/terraso-mobile-client/assets/5590815/4a41daf7-c577-4d11-9166-d189d7979a6e)

### Context 
Discussion in https://github.com/techmatters/terraso-mobile-client/issues/1197 
Potential solution: Instead of a fixed pixel width, use a percent width, or perhaps dp?

**Comment by paulschreiber** [comment]
Would `adjustsFontSizeToFit` work here?

**Comment by knipec** [comment]
> Would `adjustsFontSizeToFit` work here?

It is another option, but I think it looks weird because it could make things that are a higher percent match be a smaller size:
![Screenshot 2024-06-24 at 4 12 22 PM](https://github.com/techmatters/terraso-mobile-client/assets/5590815/6cea1b6a-6270-4315-9c42-a6602e10f686)

**Comment by CourtneyLee333** [comment]
Can I see what a single digit percent looks like?

**Comment by CourtneyLee333** [comment]
Also, it seems that we could just decrease the font size. We still have the issue of what happens on a small screen with the font size turned up. I'd rather address this particular instance in the context of larger responsive design strategy throughout the app. It's very unlikely, and maybe impossible, for a 100% match to be returned.

**Comment by paulschreiber** [comment]
Here is an example
![image](https://github.com/techmatters/terraso-mobile-client/assets/86784/1bc8a6e4-0d65-4df5-aa42-2783d6f0c53f)

**Comment by CourtneyLee333** [comment]
Noting that, though we had been told a 100% match would be impossible, it is actually quite common from what we've seen in the app so far.

**Comment by CourtneyLee333** [comment]
Perhaps something to think through - do we need to show percentage numbers? Do they help or just make things confusing. We could use a number ranking system instead.

**Comment by knipec** [comment]
Also seeing "100" with the "%" sign missing with lat/long 37.4303, -122.12658: 
![Image](https://github.com/techmatters/terraso-mobile-client/assets/5590815/0141533a-855e-4245-b35e-c7b7f2ef35a3)

**Comment by CourtneyLee333** [comment]
FYI I'm reconsidering whether we even want to reveal the percentage numbers, or go back to just showing the rank from 1 - 12. Stay tuned...

**Comment by paulschreiber** [comment]
We can revisit after Capri. Let's fix the text wrapping for now.

**Comment by knipec** [comment]
Ok, ended up decreasing font size and using adjustsFontSizeToFit. 
Closing, as Courtney took a look and approved it on https://github.com/techmatters/terraso-mobile-client/pull/1696
