### ISSUE TITLE
Delete depth dialog should display in project management screen

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1639]
Current behavior: After creating custom depths in the project management Inputs tab, I can delete a depth, even when data has been entered for that depth, without the [warning dialog seen here in Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-13071&t=kal2xQUEnGpihGpF-1). 

Expected behavior: This dialog should at least display when data has been collected at this depth for any site.

**Comment by knipec** [comment]
Triage notes: 
- Was this ever even implemented?
- Would be easiest to just display this dialog every time, even if there's no data. (This would be a good choice for offline too.)

**Comment by knipec** [comment]
@CourtneyLee333 Is it desired behavior that if the user has a bunch of depth intervals they want to delete, they'd have to get through the dialog one per depth interval? 
Like if they wanted to get rid of all these intervals:
<img src="https://github.com/user-attachments/assets/6700036f-ffc2-45c8-92bb-e1b2b4749672" height=600>

**Comment by CourtneyLee333** [comment]
Is it feasible to display it once per project per session? I have no idea how often this feature will be used, so I'd like to keep it simple until we get user observations that inform a better experience. Like, in the future we might want to include a "Clear" or "Reset" button to bulk delete them.

**Comment by knipec** [comment]
Chatted with Courtney, and concluded: Display the dialog every time. It's more effort than it's worth to have more complex logic. Most users will probably use a preset anyway, and probably unlikely to have this many depth intervals. And we'd rather have slightly annoying behavior than allow a user to accidentally delete their hard-won data.

**Comment by knipec** [comment]
Merged! Should be in 171 when that comes out

**Comment by knipec** [comment]
171 is out, assigning to Derek!

**Comment by DerekCaelin** [comment]
This passes functional review in 174beta. Over to @CourtneyLee333.

**Comment by CourtneyLee333** [comment]
Looks good.
