### ISSUE TITLE
Map "My Location" icon button needs to prompt for location permission

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1645]
Any time a user has not given location permission to the app and they tap the "My Location" IconButton on the map, they should be prompted to give the app permission. I believe we can reuse the [modal used for camera permission seen here in Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7711-20430&t=mDy56PEOs97i2XXC-1), with the following text:

LandPKS needs to access your location
For the best map experience, grant LandPKS access to your location in device settings. 
(Cancel) (Go to settings)

**Comment by CourtneyLee333** [comment]
@DerekCaelin FYI this issue exists. I gave it P2 because there is a workaround, but it's a high priority in my opinion.

**Comment by CourtneyLee333** [comment]
@paulschreiber This might be a low-hanging fruit for you?

**Comment by paulschreiber** [comment]
I can do this. Waiting on https://github.com/techmatters/terraso-mobile-client/pull/1398 to be merged first.

**Comment by CourtneyLee333** [comment]
@DerekCaelin Has this been QA'ed, or is it in the queue to be?
