### ISSUE TITLE
App unresponsive after viewing temporary location and site

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#1647]
## Repro
Not sure this are the minimum repro steps, but:
1. On home screen, click on a site. (Might need to wait for soil id to load, haven't confirmed this)
2. Go back to home screen
3. Click on a location on the map. (Also may need to wait for soil id)
4. Go back to home screen
5. Click on a site
**Expected**: 
I can view and navigate the site as normal
**Result**: 
Weird state where the app is nearly unresponsive, with the exception of swiping to interact with the site tabs bar. 
Console log says: ERROR  Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.

https://github.com/techmatters/terraso-mobile-client/assets/5590815/a358781f-93ac-4041-bdd1-b212239cc39b

**Comment by paulschreiber** [comment]
@shrouxm can you look at this?

**Comment by knipec** [comment]
Triage notes:
- Likely related to Soil ID / elevation integration 
- Coordinate with Carissa on soil id loading/error indication

**Comment by CourtneyLee333** [comment]
This seems fixed on Android. Can't test iOS yet.
