### ISSUE TITLE
Soil ID tile on dashboard sometimes has 5+ second lag before it displays

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1649]
Soil ID Tile on dashboard has a lag of 5+ seconds before it loads. I assume this is because it's waiting for soil calculations. And sometimes it seems to not ever load. This is for sites I've created in the past and new sites. 

A loading indicator would help. Caching will too.

**Comment by knipec** [comment]
Triage notes: 
- Carissa is working on loading indicator with [#895](https://github.com/techmatters/terraso-product/issues/895)
- Garo is working on some backend caching to help with this (#649?)
