### ISSUE TITLE
Site depth settings appear to not save

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1650]
What this video shows:
- Open a site Soil tab
- Tap the 10-20cm 3-dot icon, toggle on some things, check "Apply to all depths, sheet immediately closes without tapping Save
- Tap the 10-20cm 3-dot icon, toggle on some things, tap Save, sheet closes but no inputs display at that depth
- Tap the 10-20cm 3-dot icon, toggle on some things, check "Apply to all depths, tap Save, sheet closes but no inputs display at that depth

https://github.com/techmatters/terraso-mobile-client/assets/8915145/4f69d0ff-26a6-4834-872e-d8991bc680e2

**Comment by knipec** [comment]
Triage notes: 
- Seems pretty related to #1660 
- Wonder if this is related to [#1657](https://github.com/techmatters/terraso-mobile-client/issues/1657)
- Wonder if this is related to Paul's work on disabling certain collection methods -- verify this still occurs with latest release

**Comment by CourtneyLee333** [comment]
I think this is actually a huge lag, rather than it not working at all.

**Comment by CourtneyLee333** [comment]
This appears fixed on Android. Can't test on iOS yet because of crashes.

**Comment by CourtneyLee333** [comment]
Brilliant!
