### ISSUE TITLE
Location and Soil Properties Info Sheets on Soil Info Sheet open too tall and X button does not work

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1651]
This appears to be the same issue we had the previous implementation of the Data Privacy sheet. 

![Image](https://github.com/techmatters/terraso-mobile-client/assets/8915145/e6a5d806-8c35-4c03-85a4-1d1832dcf4dc)

![Image](https://github.com/techmatters/terraso-mobile-client/assets/8915145/5f748c44-575f-44f3-a593-65ec447f78ac)

**Comment by knipec** [comment]
Triage notes: 
- Components work is going to touch overlay sheets. Prefer to fix this via components work (#697), and not need this fix for Capri

**Comment by paulschreiber** [comment]
@knipec can web fix the close button now and the sheet later?

**Comment by knipec** [comment]
I'm not sure -- would be nice to have for Capri, but we think it's a P2 so not critical for Capri because you can swipe the sheet down instead of pressing the X

**Comment by tm-ruxandra** [comment]
@paulschreiber @knipec the issue is that the sheet's unexpected height causes the close button to be out of tapping range for users on some devices. I can poke around to try and find a good fix.

**Comment by paulschreiber** [comment]
Please verify in 168.

**Comment by DerekCaelin** [comment]
This looks good to me. Over to @CourtneyLee333, who filed the issuse.

**Comment by CourtneyLee333** [comment]
This passes for me too!
