### ISSUE TITLE
Tapping a site in Sites List while temp popover is open causes multiple styling and functional issues

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1653]
v148, but I think I've seen this in the past. See video below. After this error I can swipe between the Site tabs, but the back arrow and Site settings icon don't respond, and I can't swipe back to get out of the Site and back to the map. The only way to get out is to quit the app. 

https://github.com/techmatters/terraso-mobile-client/assets/8915145/1f09f4b7-24f3-4355-9b4f-8c55e41d238e

**Comment by paulschreiber** [comment]
I can reproduce this on iOS as well.

**Comment by CourtneyLee333** [comment]
Closing as a duplicate of #1647
