### ISSUE TITLE
Top Soil Matches list needs loading indicator

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1655]
When the Top Soil Matches list is loading, we need to indicate that status to the user. A good example is when you edit site data and return to this screen, the Top Soil Matches section is disappeared and doesn't display for 5+ seconds:

![Image](https://github.com/techmatters/terraso-mobile-client/assets/8915145/7ed9db6c-e4ea-4139-94b3-21872e4e0ffc)

**Comment by knipec** [comment]
Closing this, I'm planning to handle all loading indicator stuff as part of https://github.com/techmatters/terraso-product/issues/895
