### ISSUE TITLE
Map callout should not reach width of the screen with long site names

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#1656]
## Repro
1. Create a site named "Test site that should not be in the bay area" or something of similar length
2. View the site in the callout box on the home screen map
**Expected**: Callout box for the site has a smaller width than the screen, and the name wraps appropriately, like these:
![Image](https://github.com/techmatters/terraso-mobile-client/assets/5590815/7b2314bc-fa84-4a3e-bc88-110eba081d2e)
**Actual**: Depending on device, callout box may be wider than the screen and the edge of the site's title may overflow past the edges of the screen
![Image](https://github.com/techmatters/terraso-mobile-client/assets/5590815/63c56121-9312-43c4-8c43-c2c0bda29791)

The emulator on the right is iPhone SE (3rd generation) - iOS 17.5

**Comment by paulschreiber** [comment]
Please verify in 178 or later.

**Comment by knipec** [comment]
Verified; closing
FYI @DerekCaelin -- though lmk if you don't care if I ping you when I close something :)

**Comment by knipec** [comment]
Verified; closing

**Comment by knipec** [comment]
Things that aren't caused by this changelist but in a similar realm:
- https://github.com/techmatters/terraso-mobile-client/issues/1784#issuecomment-2265932393
- SiteCard popover on map is missing the CardTriangle that makes it look like a callout instead of just a box (untracked)
