### ISSUE TITLE
Depth headers need vertical margin to visually separate them

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1659]
Just one or two pixels below each depth header would help to make this UI more understandable. At some point I had this in Figma but I don't see it now. 

![Image](https://github.com/techmatters/terraso-mobile-client/assets/8915145/31bd9139-6bb6-4295-8fe7-25d5528aa924)

**Comment by CourtneyLee333** [comment]
This is also needed in #570

**Comment by paulschreiber** [comment]
How is this?
<img width="414" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/86784/d080bb74-fe1e-4965-bceb-9cb58202d080">

**Comment by CourtneyLee333** [comment]
Perfect, thanks!

**Comment by CourtneyLee333** [comment]
Looks good in implementation!
