### ISSUE TITLE
Entire screen content area should be scrollable on Notes tab

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1661]
Currently, on the Notes tab of a Site the Pinned Note and Add Note section do not scroll. This means the scrollable area for a person to scan down the list of site notes is very small. Instead, the entire content area under the tab slider should scroll.

**Comment by knipec** [comment]
@CourtneyLee333 @tm-ruxandra Is this part of components library work?

**Comment by tm-ruxandra** [comment]
@knipec I think this is in a weird halfway point -- not sure if specifying what's scrollable is a component standardization thing or a more general requirements thing.

**Comment by paulschreiber** [comment]
Please verify on 179.

**Comment by CourtneyLee333** [comment]
Looks good!
