### ISSUE TITLE
Site dashboard causing crash

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1694]
I just experienced a crash - I went to a project, to a site in that project, went to the site settings tab, hit the back arrow in the app bar and the app closed.

Just tried to repro, and get a blank screen when I go to the site dashboard using the same path above. The dashboard loads for a moment, then all I see is the green bar behind the phone info and a white screen.

These scenarios happen on Android, and the second one also happened on iOS.

**Comment by paulschreiber** [comment]
This seems fixed in 156.

**Comment by CourtneyLee333** [comment]
Seems fixed in 156 on Android, but worse on iOS.

**Comment by paulschreiber** [comment]
Looks like a null dereference. Here are some backtraces:

https://techmatters.sentry.io/issues/5569435178/?environment=staging&project=4506299761623040&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=7d&stream_index=1

https://techmatters.sentry.io/issues/5569431144/?environment=staging&project=4506299761623040&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=7d&stream_index=0

**Comment by paulschreiber** [comment]
@tm-ruxandra @shrouxm Please take a look at this.

**Comment by paulschreiber** [comment]
Might be fixed in 157. Waiting for confirmation from Courtney.
