### ISSUE TITLE
Setup issue creation template

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#17]
# Description

As we create issues, it would be nice to have a template for the type of issues we create. This would allow us to have a uniform issue structure and save some time when creating new issues.

# Definition of Done

- [ ] Decide on what kind of issues we want to create
- [ ] Create templates for these issues and add them to terraso-backend, terraso-frontend, terraso-mobile-client

**Comment by ltseng** [comment]
I assume this was done but never closed. Feel free to reopen and move to the right milestone if not.
