### ISSUE TITLE
Make MenuList and MenuItem consistent with component design

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1719]
Menus throughout the app need to implement the MenuList and MenuItem components per the [design](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7604-45783&t=Esm9mQnDuie9QHKp-1).

**Comment by tm-ruxandra** [comment]
@CourtneyLee333 It'd be helpful if you could make some minor updates to the docs now that things are implemented:
- The "destructive" variant ended up being part of the main component, so it can just be called `destructive`
- I added a property to control whether text is uppercase (which it is in the user settings menu) which would be nice to have documented
- It would also be nice to document that menu items support sub-label text (like the "deletion pending" text on the settings menu)

**Comment by DerekCaelin** [comment]
@tm-ruxandra in which build should we review MenuList and MenuItem?

**Comment by tm-ruxandra** [comment]
@DerekCaelin Should be out on v177beta now.

**Comment by DerekCaelin** [comment]
Looking at the team member list and the settings screen, this appears to match the design, but I'll trust @CourtneyLee333's keener eye here.

**Comment by CourtneyLee333** [comment]
Looks great!
