### ISSUE TITLE
when searching, long text extends beyond search bar when search is deselected

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1740]
### App Version

160

### Platforms

- [X] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

When typing a long string into the search bar, and then deselecting the search bar or tapping "search", the text extends beyond the vertical bounds of the search bar. It seems to wrap.

### Steps to Reproduce

1. On the home screen, type a long string, such as `34.97277, -106.68278`
2. select "search" on the keyboard
3. see issue

### Expected behavior

Text remains in the search bar but is truncated to fit within the horizontal bounds of the search bar

### Actual behavior

Text extends beyond the search bar, as if wrapping. 

### Additional context

![IMG_2CE3BE799310-1](https://github.com/techmatters/terraso-mobile-client/assets/10799815/7d7414c8-3929-4856-a2f8-3ee0e3968502)

**Comment by paulschreiber** [comment]
This only happens when text magnification is greater than 100%.

**Comment by DerekCaelin** [comment]
1. I think my text magnification is at the default
2. Isn't this a bug, even if I have changed my text magnification?

**Comment by paulschreiber** [comment]
Yes, it's a bug even if magnification is changed. We hope to support responsive text sizing in a future version.
