### ISSUE TITLE
on iOS, navigating away from the login screen and returning makes google and microsoft login buttons unresponsive

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1748]
### App Version

160

### Platforms

- [X] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

On iOS, on the login screen, the Microsoft and Google login buttons will fail silently if the user navigates away and returns

### Steps to Reproduce

1. Log out and go to the login screen
2. Switch to another app
3. return to LandPKS
4. Tap Google or Microsoft Login buttons

### Expected behavior

Login proceeds as expected

### Actual behavior

Google and Microsoft login buttons fail silently (Apple behaves normally)

**Comment by paulschreiber** [comment]
I can't reproduce this on 166 (iPhone 14 Pro with iOS 17.5.1).

**Comment by DerekCaelin** [comment]
no longer occurring in 169, closing
