### ISSUE TITLE
Make FormOverlaySheet consistent with component design

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1774]
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7289-34451&t=FWzt402zPDCk2duY-1)

**Comment by tm-ruxandra** [comment]
Per discussion with @CourtneyLee333 

-`Select` component should use this new `FormOverlaySheet`
- Soil depth interval editor should be migrated to `InfoSheet`
- Soil settings editor should be migrated to `InfoSheet`
- Camera/photo source picker should be standalone component, no underlying reused sheet component

**Comment by DerekCaelin** [comment]
My uncultured eyes think this looks good. I found a FormOverlaySheet sheet in selecting project depths.

**Comment by CourtneyLee333** [comment]
Looks great!
