### ISSUE TITLE
Login fails silently

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1777]
Login fails silently for some users. 

## Version
169

## OS
Android, iOS

## Accounts 
Courtney - courtney@techmatters.org (Google)
Courtney - courtney.tiberio@gmail.com (Google)
Max - Maxjc@nmsu.edu (Microsoft)
Max - maxjc@landpotential.org  (Google)
Jon - jjmaynard9@gmail.com (Google)

## Steps to reproduce
1. Go to sign in screen
2. select "Sign in with Google"
3. Provide consent for Google to access data
4. see issue

## Expected behavior
After a few seconds wait, app displays home screen and map

## Actual behavior
Login fails silently (app does not progress from sign in screen)

## Additional Context

Courtney: I have uninstalled and reinstalled the app, and restarted my phone as well. See video for details. 

https://github.com/user-attachments/assets/1f018859-97d0-4752-a76b-65e6c5402ee9

- Jon maynard and laura encountered this as well.
-  (7/16/2024) said that he could neither log in with Google nor Microsoft on Android. Max is beta tester.

**Comment by DerekCaelin** [comment]
@paulschreiber I updated the issue with emails and types. Jon clarified that he did not face a microsoft issue

**Comment by paulschreiber** [comment]
FIx/workaround
-quit the app
- press and hold on the app icon
- tap app info
- tap storage & cache
-  tap clear storage
-  when the confirmation prompt appears, tap delete

- then try logging in again.
