### ISSUE TITLE
on Android, user can't see own location on first load of map

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1780]
### App Version

169

### Platforms

- [No] iOS
- [YES] Android
- [No] iOS simulator
- [No] Android emulator

### Description

First-time Android users can't see their own position on the map, and the "my location" button fails silently. Reloading the app once permissions have been granted allows the map to see the user's location. 

### Steps to Reproduce

On Android:
1. Uninstall, reinstall and open app
2. Pass through interstitial
3. Sign in with any identity
4. Open home screen and accept permissions request
5. See issue (fails to pan/zoom to your location)
6. Tap "my location" button
7. See issue

### Expected behavior

The map will know and center on the user's location
Tapping on "My location" button will center the map on the user's location

### Actual behavior

The user provides permission, but no point representing the user appears on the map, and the "my location" button does nothing. 

### Additional context

- Upon closing and re-opening the app, the map can pull the user's own location
- on iOS, permissions are granted on the intersitial screen, but on android, Permissions come when viewing the map. Theory: the app tries and fails to get the user's location, asks for permission, but doesn't try again to get location once it has permission.

**Comment by DerekCaelin** [comment]
Possibly related to https://github.com/techmatters/terraso-mobile-client/issues/1749

**Comment by DerekCaelin** [comment]
Assigning to Garo since they have dealt with permissions issues and are looking at related task #1806

**Comment by DerekCaelin** [comment]
Hi @knipec I see this is in QA. The bug appears to still occur in 187. Is the fix in the current build?

**Comment by knipec** [comment]
Sorry @DerekCaelin - should be in v188

**Comment by DerekCaelin** [comment]
@knipec Sorry for the delay in reviewing this. After granting permissions to access my location, the app successfully zooms in to my location. The "My location" button works.

However, on first view, the blue marker signifying my location doesn't appear. I need to close and re-launch the app to see see the blue marker.

**Comment by knipec** [comment]
@DerekCaelin Oh yeah, weird -- I can repro that behavior on a physical Android device, but not on the emulator or an iOS device. 
Would you be ok with filing a new bug for that, and pulling the new bug into October (or leave it out if you think it's lower priority than other things)?

**Comment by knipec** [comment]
@DerekCaelin Hm actually I can only inconsistently repro it on a physical Android device (after deleting and re-installing the app) -- are you seeing it consistently?

**Comment by DerekCaelin** [comment]
It is consistent, yes. I'll file another bug.
