### ISSUE TITLE
Elevation does not render "unknown" result in the UI

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-mobile-client#1787]
## Description
When a user taps on a location outside the US, the elevation API returns a string:
```
Invalid or missing input parameters.
```

Our `elevationServices.ts` file calls `getElevation()`, which handles that and correctly returns `undefined`.

The `renderElevation`file correctly handles `undefined` and renders "unknown".

However, somewhere in between (perhaps in `elevationSlice`?), the unknown value gets lost and doesn't get passed up the client layer.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 I tested this by tapping in Africa. Field returns "unknown" (lowercase) - should we stylize the word?

**Comment by CourtneyLee333** [comment]
No, I think it's fine the way it is.
