### ISSUE TITLE
bug: after logging out, pressing "back" button returns user to the app in a logged out state with data still visible

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#1790]
### App Version

1.0.0 (commit 0395913)

### Platforms

- [ ] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

Currently, if the user logs out of the app, they will be navigated to the login screen in a way where the home screen is still at the bottom of the screen stack, so if they hit the back button on Android (not sure if there is equivalent on iOS) they will go back to the user settings screen, but while logged out. they will then need to close and re-open the app to get back to the login screen.

### Additional context

[Screencast from 07-18-2024 09:49:17 AM.webm](https://github.com/user-attachments/assets/2ec8bbb3-b9c1-4e7e-8198-655f7deccb2a)

the way we've implemented our authentication flow currently does not align with [React Navigation's recommendations](https://reactnavigation.org/docs/auth-flow/), but i think that page can be used as a guide for how to make some structural changes which will resolve this bug

**Comment by knipec** [comment]
Triage notes: 
- Destroy navigation stack? See library's advice in description

**Comment by tm-ruxandra** [comment]
@DerekCaelin Was this on a physical device? I cannot reproduce the issue on an Android emulator.

**Comment by DerekCaelin** [comment]
Yes, this is using my OnePlus Nord N30.

**Comment by DerekCaelin** [comment]
This is resolved! Thank you.
