### ISSUE TITLE
Prompt for location permission appears on signin or welcome screens instead of on map screen 

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-mobile-client#1808]
LandPKS requests permission to access locations in the signin or welcome screen, but we expect this to happen when the map screen is first viewed. 

## Version
175 beta

[x] Android
[x] iOS

## Steps to reproduce
1. Uninstall and reinstall app
2. Open the app

## Expected behavior
Prompt for location permission on map screen (not login or welcome screens)

## Actual Behavior
Prompt for location on signin or welcome screen

**Comment by knipec** [comment]
Should be available to verify in build 178

**Comment by paulschreiber** [comment]
Verified as fixed.
