### ISSUE TITLE
App hangs searching for lat/lng pair

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-mobile-client#1827]
### App Version

1.0.1 (172)

### Platforms

- [ ] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

App hangs searching for a lat/ng pair.

Sentry profile: https://techmatters.sentry.io/issues/5632803701/?project=4506299761623040

### Steps to Reproduce

1. Start typing `36.30218,-83.19369` into the search box (type, don't paste the whole thing in)
2. Around `36.30218,-83.19` the app hangs

**Comment by DerekCaelin** [comment]
- Relevant issues: https://github.com/techmatters/terraso-mobile-client/issues/772
- Look to google maps as the method of putting in the lat/long
- solution may involve using a debounce system

**Comment by paulschreiber** [comment]
We use [use-debounce](url) in the web app.

**Comment by DerekCaelin** [comment]
@paulschreiber I was never able to reproduce on my devices... can you review this?

**Comment by DerekCaelin** [comment]
Pulling into August since the QA still needs to happen.

**Comment by paulschreiber** [comment]
I can n longer reproduce. Likely mitigated by https://github.com/techmatters/terraso-mobile-client/pull/1848
