### ISSUE TITLE
Changing to BLM monitoring standard fails silently

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1829]
### App Version

172 beta

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

Attempting to choose the preset "BLM Monitoring standard" at either the project level or in an unaffiliated site fails silently.

### Steps to Reproduce

**Unaffiliated Site**
1. Go to unaffiliated site
2. Go to soils tab
3. Select the Soil Pit Menu
4. Select "BLM monitoring standard" radial button
5. Save and confirm selection
6. See issue

**Project**
1. Go to a project where you are a manager
2. Go to "inputs" tab
3. in the Soil Pit section select, go to soil presets dropdown
4. Select "BLM monitoring standard" radial button
5. Save and confirm selection
6. See issue

### Expected behavior

Soil depth presets are adopted for the site.

### Actual behavior

Action fails silently (last preset persists)

**Comment by paulschreiber** [comment]
Bumping to P1.

**Comment by DerekCaelin** [comment]
This is resolved

**Comment by paulschreiber** [comment]
Was also fixed with a backend update.
