### ISSUE TITLE
Selecting "soil pit" section in new project causes crash

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1830]
### App Version

172 beta

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

Opening the "soil pit" section in a new project causes crash

### Steps to Reproduce

1. go to projects screen
2. Create project
3. On the "inputs" screen, tap "soil pit"
4. See issue

### Expected behavior

Accordion expands, user can interact with soil pit dropdown

### Actual behavior

Crash

### Additional context

Pre-existing projects appear to allow the user to edit soil depths

**Comment by paulschreiber** [comment]
Here's the crash:
```
 ERROR  TypeError: Cannot read property 'map' of undefined

This error is located at:
    in DepthTable (created by SoilPitSettings)
    in RCTView (created by View)
    in View (created by Box)
```

**Comment by DerekCaelin** [comment]
This is resolved for me

**Comment by paulschreiber** [comment]
This was fixed by updating the staging backend.
