### ISSUE TITLE
Transfer Sites screen needs consistent spacing between accordion headers

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1845]
Some of the accordions have spacing and some don't. The spacing should be consistent with the accordions on the Project Inputs tab. 

![Image](https://github.com/user-attachments/assets/1779b9f3-c3f0-4a15-80ef-1a40f31fac2a)

**Comment by CourtneyLee333** [comment]
I'm assuming this should be in 176 or higher.

**Comment by paulschreiber** [comment]
Yes, this is in [176](https://github.com/techmatters/terraso-mobile-client/releases/tag/v176beta).

**Comment by CourtneyLee333** [comment]
Looks good!
