### ISSUE TITLE
Delete dummy data from mobile client

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#185]
Once we are using the backend fully, all the files used to create dummy data should be deleted. These are mostly in the folders `dataflow` and `types`.

**Comment by ltseng** [comment]
I would really like to get all references of "Sample Sam" and "8/15/23" replaced with actual data in this next sprint. @shrouxm should I file a separate issue for that, or use this one?

**Comment by ltseng** [comment]
@shrouxm - does this mean I do or do not need to create a separate issue?
