### ISSUE TITLE
project contributers and viewers can see "Add Depth" button and toggles on the input screen

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1850]
Contributors/viewers looking at the project "Inputs" tab see toggles and buttons that they don't actually have the ability to manipulate. Disable/hide elements.

## To reproduce
1. Be a contributor or a viewer of a project
2. Go to that project and look at the "inputs" tab
3. See the issue

## Expected Behavior
- [x] as a manager of a project, I should see the depth button and be able to see and adjust input toggles
- [x] As a contributor or viewer, I don't want to see the button to add depth on the input screen
- [x] As a contributor or viewer, I want to see the disabled input toggles (toggled to the choice the manager made)

## Actual behavior
Project contributors or viewers can see and manipulate the button, and see the toggle in the enabled state.

## Additional context
- this is a client side, not a backend issue

<img width="344" alt="image" src="https://github.com/user-attachments/assets/440940b3-31b9-4633-9d71-32faf4ec6965">

**Comment by paulschreiber** [comment]
Please verify in 176 or later.

**Comment by DerekCaelin** [comment]
@paulschreiber confirmed that contributors and viewers can't see add depth, thank you. I think @CourtneyLee333 wanted contributors and viewers to be able to see required inputs, but not to be able to change the toggle. Is it possible to show the toggles in their on/off state, but to disable them?

**Comment by DerekCaelin** [comment]
(@paulschreiber if you are in the inputs screen there is a related bug that maybe you could tackle at the same time? https://github.com/techmatters/terraso-mobile-client/issues/956 )

**Comment by DerekCaelin** [comment]
This is complete.
