### ISSUE TITLE
Make chip consistent with component design

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1877]
Chips should be consistent across the app with the [design](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9334-12527&t=1rygqWdA7ochfVlJ-1).

**Comment by knipec** [comment]
Should be ready to QA in v197

**Comment by DerekCaelin** [comment]
This looks right to me - over to @CourtneyLee333 for her review

**Comment by CourtneyLee333** [comment]
Looks good on Android, iOS is currently crashing on launch.
