### ISSUE TITLE
Soil ID Screen - Implement Soil Cracking Module

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1888]
Create a module on the Soil ID page to display Soil Cracks, which is relevant for the Soil ID algorithm. See parent issue for details. 

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10962-8287&t=fcyACT7ReWehB7l3-1)

### Soil Cracking
- [x] Add text field displaying user's selected observations on soil cracking, if any
- [x] Add a button saying "ENTER CRACKS" that brings the user to the soil cracks input screen
<img width="261" alt="image" src="https://github.com/user-attachments/assets/624e35aa-20eb-480f-bdd3-8fef1a45457e">
<img width="261" alt="image" src="https://github.com/user-attachments/assets/b432deb2-ee52-43e7-8f8d-448c97ffbb28">

**Comment by paulschreiber** [comment]
Please verify in 216 or later.

**Comment by DerekCaelin** [comment]
This meets my expectations. Over to @CourtneyLee333

**Comment by CourtneyLee333** [comment]
This passes my review in the narrow sense. There is an issue where I cannot change the Soil cracks selection back to empty, but that is a separate bug.
