### ISSUE TITLE
"Add Team Members" button is stretched; should be "Add Team Member"

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1890]
## Description
The "Add Team Members"  button is stretched to full width (it should be smaller to match design) and use  read "Add Team Member" to reflect our current experience of adding one team member at a time.

## Version
177beta
iOS, Android

## Steps To Reproduce

1. Open project where you are a manager
2. Go to "Team" tab
3. See issue

## Expected behavior
Add member [button matches design](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-12846&t=37XUVPyJG53QYHF4-0):
- width
- text ("Add Team Member")

![Image](https://github.com/user-attachments/assets/89333651-00e1-4991-a3a1-d27a61a25f12)

## Actual behavior
Button is full width and says users can invite multiple team members

<img src="https://github.com/user-attachments/assets/0a5a8a8b-9283-48e3-a9cc-61c45c5dfc52" width="300px">

**Comment by paulschreiber** [comment]
Please verify in 178.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 implementation seems functional but doesn't match design (multiline button). Thoughts?

#### implementation vs design
<img src="https://github.com/user-attachments/assets/68bdd3e8-f5db-437f-9cee-fc5aa3b4822c" width="200px">
<img src="https://github.com/user-attachments/assets/146a4cf6-3bf3-40e3-8d5d-5e4173a0d6cb" width="200px">

**Comment by CourtneyLee333** [comment]
@DerekCaelin I don't see a multi-line button like your screenshot, neither on Android nor iOS.

**Comment by CourtneyLee333** [comment]
But no, I don't like the multi-line and think it should match the design.

**Comment by DerekCaelin** [comment]
@paulschreiber this is happening on my OnePlus Nord N30 5G.

**Comment by paulschreiber** [comment]
@DerekCaelin the multi-line button isn't happening for me on 178 on Android on my Pixel 7a. did you increase the default font size?

**Comment by DerekCaelin** [comment]
@paulschreiber I haven't changed my font size. It is set to default.

**Comment by DerekCaelin** [comment]
Can't reproduce on iOS.

**Comment by paulschreiber** [comment]
Closing as completed.
