### ISSUE TITLE
Generate .PO for LandPKS Soil ID US client

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1896]
Create a .po file that contains all the strings in the Soil ID client. See parent task https://github.com/techmatters/terraso-product/issues/860 for details.

**Comment by DerekCaelin** [comment]
@paulschreiber where can I find the file?

**Comment by paulschreiber** [comment]
https://github.com/techmatters/terraso-mobile-client/tree/main/dev-client/locales/po

**Comment by DerekCaelin** [comment]
@paulschreiber The translator says that the file has the source text as the "ID" - is it possible to generate a version of the file where "English" is the source text?

#### Translator view
![Image](https://github.com/user-attachments/assets/010658aa-244e-42d4-a1b6-ede98125b524)

**Comment by paulschreiber** [comment]
This is working correctly.
