### ISSUE TITLE
Bug: Keyboard hides inputs on user selection

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#190]
When a user selects a text input, it would be nice for the screen to scroll so that the input is not hidden by the selection (note from the future: does "selection" mean "keyboard"?). Right now the user has to scroll down in order to see the text that is being entered.

**Comment by knipec** [comment]
@DerekCaelin @CourtneyLee333 Anyone know if this is happening in any particular screen? If not, I'm tempted to close it.

**Comment by CourtneyLee333** [comment]
If I could sign in to the app on my phone I'd be glad to hunt for this 🙃

In the meantime, I wonder if this is behavior that is/should be covered by the component work. I'll go ahead and add a note to the documentation.

**Comment by CourtneyLee333** [comment]
I can't find any instance of this happening currently. I'll close it for now, and if we do find an instance in the future we should relate it to the relevant component.
