### ISSUE TITLE
bug: icons on home screen have weird hitbox and positioning

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#192]
## Description
Icons on the home screen have hitboxes that don't match their visible boundaries, and shift slightly as the map is moved in and out. I suspect the second issue is because the icon component has a padding around the actual icon, and so the bottom of the icon is directly anchored to the coords. The hitboxes we may need to manually specify.

**Comment by ltseng** [comment]
Is this related to #367?

**Comment by shrouxm** [comment]
this was unrelated. this issue is icons reacting to a tap when they have not been tapped, #367 is the app doing a bad job picking which icon to tap when a tap is near multiple icons. this issue seems to have gotten resolved unintentionally in the many iterations of our map icon rendering code so i'm gonna close it!
