### ISSUE TITLE
Research - Redux state persistence library (NOT for data syncing)

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#1931]
- Regardless of syncing, we just want to preserve redux state between launches, so that offline local changes to data are saved if you never have connectivity
- Serializing what's in memory, load it back from disk when app opens again

## References
[Offline Research](https://docs.google.com/presentation/d/1eHO52LqsSsOV6tyBQrEUA857VHsjGAdxQEDYWcWQLaY/edit#slide=id.g2f0a32b466d_0_13)

## Acceptance Criteria
- [ ] How would we break this down into smaller prototype chunks? (And create separate issues if appropriate)
- [ ] Make recommendation for Redux state persistence library

**Comment by shrouxm** [comment]
i've written up my research in [this doc](https://docs.google.com/document/d/1cMRc5SD3XIQ1jrtR-AfAqdEXsag5hbJ32MMzM5FTp40/edit?usp=sharing)

**Comment by shrouxm** [comment]
doc has been reviewed and approved by everyone, and its action items transcribed to github issues, so this is done!
