### ISSUE TITLE
Display correct user location accuracy on Site Creation screen

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#197]

**Comment by ltseng** [comment]
Can we size this?

**Comment by ltseng** [comment]
@david-code saw that you had linked a PR for this one, so I'm assigning it to you. I know @CourtneyLee333 has listed this as part of a styling issue for the Create Site screen, so it's not critical for the usability study, but would be nice to have. I'm leaving this task as a medium priority one.
