### ISSUE TITLE
User can get to home screen if signed in and offline

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2030]
In order to actually use Soil ID offline, the user must be able to see map screen while not being connected to the Internet. As of 8/2024 the user can't progress past the sign in screen. 

## Acceptance Critiera
- As an offline user who previously logged in to LandPKS Soil ID, I want to be able to "get past" the sign-in screen and see other aspects of the app
  - [ ] When user has already logged in and opens the app offline: app opens to home screen, same as in online mode, and knows what user I am (can see in User Settings screen, and on a Project's Team screen?)
  - [ ] Do not regress online behavior for login / logout / opening app when already logged in
  - [ ] Any sensitive data is stored securely
  - [ ] Also, should this be behind a feature flag?
- Investigate for later
  - [ ] Does it makes sense to prevent user from logging out while offline?
  - [ ] When user has not logged in (or has signed out) and opens the app offline: [[Behavior undefined; recommend what should happen]]

Non-goal
- If the user has not already logged in, they shouldn't be able to see the app.

## Notes
- Will this come for free with garo's work on saving redux state? 
  - Data exists in Redux as `state.account.currentUser`
- From Whitespectre: "You’re in the right path. Actually a common practice in mobile apps regardless of Offline support is to store the user info (including access and refresh tokens) and then if you have those, don’t show the login screen and go straight to the logged in experience.
The only thing you need to consider is the expiration of the access tokens - you might decide to leave the user do everything while in offline and then when they come online just check if the access token is still valid to sync the data changes, or refresh the access token before doing that."
- Perhaps just store currentUser data in mmkv?

**Comment by knipec** [comment]
This is covered by the redux persistence work that @shrouxm did with their work on #2164. 

I expect there may still be some stuff to do with expiration of the access tokens, as Whitespectre folks mentioned. Creating a separate story for that, which will need to be fleshed out: #2284

**Comment by knipec** [comment]
This should be QA-able in v195beta

**Comment by DerekCaelin** [comment]
@knipec in 195beta, I closed the app, went into airplane mode, and opened the app. I expected to progress to the homescreen but I remained on the sign in screen.

**Comment by knipec** [comment]
@DerekCaelin Had you turned on the feature flag before closing the app?

**Comment by DerekCaelin** [comment]
Aha! It works!
