### ISSUE TITLE
Implement a network status hook

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#2031]
Now that we've done the initial investigation and prototyping (from #1930), do some stuff for real

## Acceptance criteria
- Create a hook that can be used throughout the app, that will provide network status (online, offline, or unknown/null). See [Whitespectre writeup](https://docs.google.com/document/d/1vc2GrmcZLsLPuqeQ5kWJQCxv_8ErfJr6FUR2b3Wr16w/edit) for guidance 
- Try out the proxy debugger that Whitespectre folks suggested --> This is now #2127
- App monitors network status when 'active' (meaning it's in the foreground)
- App stops monitoring network status when not 'active'
- Use it in the Soil ID sheet "Top Soil Matches" section to show a "You are offline" box (see image below)
- Consider: any tests we can write for this work?
- Should any of this be behind a feature flag? I think it'd be ok not to.

![Image](https://github.com/user-attachments/assets/7763a64b-a1cd-4950-be36-09f15c792588)

**Comment by knipec** [comment]
Should be available in next build (v191beta)

**Comment by DerekCaelin** [comment]
This worked for me! 
1. While online, open app
2. Open a site, go to the Soil ID page
3. Go into airplane mode
4. See change 

This appears to be both a working status hook and resolve:
- https://github.com/techmatters/terraso-mobile-client/issues/1360

Over to @CourtneyLee333

**Comment by CourtneyLee333** [comment]
It works on Android and iOS! 

One design nit-pick: the alert box doesn't have the pale orange background as specified in the design. Should we go ahead a create a design component for this since we are introducing a new component to the app?

**Comment by knipec** [comment]
@CourtneyLee333 Could you point me to the design with the pale orange background? 
All I see on the [Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=3800-22059&node-type=instance&t=jayxGV4uVBjAfph5-0) linked on #1360 is this palette: 
![Screenshot 2024-09-25 at 10 04 34 AM](https://github.com/user-attachments/assets/5bf5ab89-922c-41a0-90e7-eb57abbe4392)

**Comment by CourtneyLee333** [comment]
@knipec oh, you're right! I forgot that I had updated the design from a previous version that had a pale orange background. All good, carry on.
