### ISSUE TITLE
Make "depths" button use text instead of an icon

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2069]
Multiple users don't understand that the Depths button (currently an icon) allows the user to edit Depths. Change it to TextButtonDefault with trailing icon.

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9786-16021&node-type=frame&t=blHjW97EXmvTHUIm-0)

**Comment by knipec** [comment]
Currently the InternalLink requires a valid url, perhaps this should change or perhaps we should make a new component

**Comment by DerekCaelin** [comment]
Thanks @knipec. I think the core of the request is that the icon change to be a word "Depths", and be presented in a style to match internal link. @CourtneyLee333 do I have this right?

**Comment by CourtneyLee333** [comment]
I actually changed the design to use TextButtonDefault instead. Didn't realize this issue existed with details already. 
![Screenshot 2024-11-01 at 5 22 23 PM](https://github.com/user-attachments/assets/4153841f-734b-4b44-957a-cf8a9592ff92)

**Comment by shrouxm** [comment]
@DerekCaelin will be ready for QA in version numbers 210 and above

**Comment by DerekCaelin** [comment]
Thanks Garo! The depths button looks slightly further to the left than in the Figma design, but I'll leave @CourtneyLee333 to be the judge
