### ISSUE TITLE
Move soilID Redux slice into mobile client codebase

### ISSUE THREAD

**Issue by tm-ruxandra** [techmatters/terraso-mobile-client#2070]
Currently, the Redux slice the handles soil sample data and Soil ID interactions lives in `terraso-client-shared`. This causes architectural challenges for mobile-only considerations for offline mode operation. Migrate this code (Redux slices under `project`, `site`, and `soilId`)  into the `terraso-mobile-client` repository, and apply minor refactoring to make further offline research tasks more manageable.

**Comment by shrouxm** [comment]
closing because i think this is complete
