### ISSUE TITLE
Create feature flag infrastructure to gate offline functionality

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#2100]
## Intention
We want to do development and testing on the new offline feature, while shipping releases that don't yet expose offline functionality to users.
Previously we'd been talking about having a long-lived feature branch like feat/offline or something. After some discussion, sounds like the preference is to have a feature flag. This will reduce the complexity of merging between branches, as well as potential confusion of which version we're testing against.

## Acceptance Criteria
- A feature flag exists. By default it is off.
- Users can see and toggle the feature flag state when in development or staging environments (not production)
- The team knows how to use it, and developers know how to write code with it
- It will be easy to enable when we are ready to ship the offline feature 
- It will be easy to remove entirely after it has been enabled in prod for a while

Optionally, but not part of this, a later stage could: 
- Make the feature flag system support multiple feature flags
- Figure out how to restart the app for you when you hit the toggle, or allow the developer to specify which flags require a restart

**Comment by knipec** [comment]
Pulling this into the sprint to enable checking in work specific to offline, that is not ready to ship

**Comment by knipec** [comment]
FYI 
- Developers can use the flag to gate new functionality: `if (isFlagEnabled('FF_offline')) { // do new thing }`
- Users in a non-production environment can now toggle the feature flag from the settings screen. The user must restart the app for the new feature flag value to take effect.
<img src=https://github.com/user-attachments/assets/ea7910dc-0623-4869-89f1-f772a5d0aec0 width=350>

- #2160 now tracks the semi-distant future work of removing the feature flag from the codebase once the feature is released and we're like, "it's on forever now and we're never gonna want to turn this off". @DerekCaelin Feel free to change the milestone of that item.

**Comment by DerekCaelin** [comment]
Seems like the right milestone

**Comment by DerekCaelin** [comment]
@knipec in what build can I test this?

**Comment by knipec** [comment]
@DerekCaelin should be in 191

**Comment by DerekCaelin** [comment]
@knipec I see the flag in settings in the current build! Is that all I need to test?

**Comment by knipec** [comment]
@DerekCaelin Almost! Also that when you switch the flag between on/off, it's remembered. And when you clear app storage it's forgotten and set back to the default.

**Comment by DerekCaelin** [comment]
Great! I've done that, and this passes.
