### ISSUE TITLE
Set up a proxy debugger

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#2127]
Whitespectre recommended a proxy debugger (they use one called Charles) to simulate offline mode and stay connected to Metro. Set this up for myself and share how to do it.

**Comment by knipec** [comment]
I looked into this for some days and didn't figure out how to get it working with our configuration, but here's where I got: 

## Proxyman
Progress
- I like Proxyman’s UI better, and I got a license for it. (They gave us a 50% discount; ask Paul or Carissa for the code)
- Got it set up to connect to iOS simulator ([Proxyman documentation here](https://docs.proxyman.io/debug-devices/ios-simulator)). There are additional steps for Android, which I haven't yet done.

Issues:
- But I can’t figure out how to actually make it simulate offline mode without disconnecting from Metro, as:
  - I tried to add a Block List rule to block everything except Metro with a regex like: (^(?!.*192\.168\.0\.203:8081).*) 
    → **But Netinfo still didn’t consider us “offline” when I turned the block rule on** (also tried to specifically block both the backend (localhost:8000, which somehow is showing up now, dunno why) AND the url that netinfo uses to check reachability? Uh maybe you can block one though? I don’t heckin know, I tried to block “https://clients3.google.com/generate_204” and netinfo didn’t consider it “offline”)
- Anytime I enable network conditions, or allow list, or block list, the app disconnects from metro
- I sometimes can’t see calls to our backend (though I did see localhost:8000 once if I changed the TERRASO_BACKEND .env variable from the local IP to that -- which I think works on iOS but fails to reach the backend on Android)

## Charles
Progress
- Whitespectre wrote up some [standard setup instructions](https://docs.google.com/document/d/15VfW5BASvCqUsMxQi7rpsLOcRe6rjiL8qVDO-1KfbGU/edit?usp=sharing). (I think they revoked viewing permissions, but I've re-requested them.)
- Got it connected to iOS simulator, but there are additional steps for Android, which I haven't yet done.

Issues
- If I turn the allow list on while the app is running, I don't see the app recognize anything has changed -- like the Soil ID sheet should show an offline message [as described in this story](https://github.com/techmatters/terraso-mobile-client/issues/2031). (I do see the app in offline mode if I start with allow list on, and I do see the app update to online mode if I then turn the allow list off -- I just can't go from online to offline)
  - I don’t actually recall if I see any expected errors in this case (like for mapbox or being unable to connect to our backend)
- I can’t see calls to localhost:8000 (or using my local IP, 192.168.0.203:8000). I found [this page about localhost traffic not appearing in Charles](https://www.charlesproxy.com/documentation/faqs/localhost-traffic-doesnt-appear-in-charles/), but it didn't solve the issue, and our .env file already uses the local IP 
- Side note: I’ve had an issue where I quit Charles, but requests are still being blocked. Not sure how common this is.

## Other things I tried
- adb commands at the bottom of https://github.com/facebook/react-native/issues/38579 

## Workaround(s) so far:
- If it’s okay to disconnect from Metro, you can just use airplane mode in the Android simulator or a physical iOS device
- To stay connected to Metro, you can use a physical Android device with the steps here → [NetInfo investigation](https://docs.google.com/document/d/1yv_Hiw56yi7TioE4hAac8LWu1AAf6tTwXGIel0KEdGY/edit)

**Comment by DerekCaelin** [comment]
We don't think this is needed right now. Closing with the expectation that if we need to set up a proxy debugger in the future, we can reference these notes.
