### ISSUE TITLE
Remove SSRProvider warning

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#213]
We are now getting this lovely warning:

```
In React 18, SSRProvider is not necessary and is a noop. You can remove it from your app.
```

Googled what causes this, and it's because NativeBase relies on an old version of a certain library that it does not seem like they will update. Let's silence the warning, as it is not relevant to us.

**Comment by paulschreiber** [comment]
Which library? See if anyone has already forked/patched it.

**Comment by paulschreiber** [comment]
Closing as there is nothing for us to fix. We have already suppressed it on development builds.
