### ISSUE TITLE
Terasso LandPKS app layout on tablet is at phone size 

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#220]
## Description
The layout on my iPad (8th gen, iPadOS 16.4.1) does not fill the screen, but seems to be at phone size. There is a button in the lower right corner that allows me to zoom in, or expand the view, but the size ratio stays the same without filling the screen. 

## Steps To Reproduce
Open the app. That's all. There are no other actions I can perform in the current version. 

## Expected behavior
The layout of the app will fill the screen in a responsive manner.

## Actual behavior
The layout seems to be a set size on the ipad. The bottom tabs are not accessible.

## Additional context

![PXL_20230726_174732622](https://github.com/techmatters/terraso-mobile-client/assets/8915145/f037e427-37b1-4f5a-9a43-e1012f05707d)

**Comment by ltseng** [comment]
I am able to replicate this on my iPad as well. It's a 9th generation iPad on 15.3.1

**Comment by ltseng** [comment]
@david-code @paulschreiber What would the size of this bug be? Steve is asking if there's a simple workaround, but I'm hoping this is straightforward enough to just fix.

**Comment by paulschreiber** [comment]
Turned out the size was pretty small. Mostly just Xcode config changes.
