### ISSUE TITLE
Deploy test builds automatically

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#222]
Now that there are more features available to test on the mobile client, it would be nice to deploy new development versions of the mobile client to the App Store / Play Store every time a PR is merged. This would let team members test the newest versions on their phones.

**Comment by paulschreiber** [comment]
You mean to `staging`, right?

**Comment by david-code** [comment]
> You mean to `staging`, right?

Yeah, I guess that would make more sense.

**Comment by paulschreiber** [comment]
We are now deploying nightly. We need to do some additional work to bump the build number.

**Comment by ltseng** [comment]
The script to deploy new builds nightly doesn't seem to have been working for a while. @paulschreiber can you look into why?

**Comment by ltseng** [comment]
Is this still a valid task?

**Comment by shrouxm** [comment]
not planning to do this, instead we want to just reduce the friction of deploying new builds enough that we can just do it manually more frequently
