### ISSUE TITLE
[Offline] Implement and test local soil data mutations

### ISSUE THREAD

**Issue by tm-ruxandra** [techmatters/terraso-mobile-client#2277]
In order to support offline soil data collection, we must replicate our backend logic for soil data changes on the frontend. These GraphQL mutations will need to be replicated on the client side:

1) `SoilDataUpdateMutation`
2) `DepthDependentSoilDataUpdateMutation`
3) `SoilDataUpdateDepthIntervalMutation` (only if product decides to include depth intervals in MVP)
4) `SoilDataDeleteDepthIntervalMutation` (see above)

These should be stateless pure functions which take in the corresponding mutation input and a `SoilData` object, and return the resulting updated `SoilData` object, or return an error message if the backend would have returned an error message.

Create a service under `terraso-mobile-client/model/soilId` which implements this logic, and cover it thoroughly with unit tests. These should be drop-in replacements for the GraphQL calls; the offline feature flag should determine whether Redux invokes the GraphQL or local version of the mutation.

**Comment by DerekCaelin** [comment]
@tm-ruxandra How should I test this?

**Comment by tm-ruxandra** [comment]
@DerekCaelin Open the application with the offline feature flag turned on and use the soil screens as normal.

**Comment by DerekCaelin** [comment]
I

**Comment by CourtneyLee333** [comment]
@tm-ruxandra  This doesn't work for me. Here's what I did on v199:
- turn feature flag on
- relaunch app
- go to a site and enter texture and rock frag for a few depths
- close the app and relaunch
- the data I entered is gone

My data does persist if I navigate around the app without stopping my session.

**Comment by CourtneyLee333** [comment]
NOTE: If I toggle on airplane mode in addition to the steps above, data does persist as expected.

**Comment by tm-ruxandra** [comment]
@CourtneyLee333 Persisting data between app sessions in online mode will be covered by https://github.com/techmatters/terraso-mobile-client/issues/2279 -- right now we don't have the push sync mechanism implemented, so local changes just get overwritten by what's on the server when the app launches in online mode
