### ISSUE TITLE
[Offline] Field-level change tracking for mobile client push

### ISSUE THREAD

**Issue by tm-ruxandra** [techmatters/terraso-mobile-client#2283]
Augment the push system developed in #2279 to support tracking individually-changed fields on Soil Data, Depth-Dependent Data, and Depth Intervals (if depth intervals were included in MVP). Only fields/intervals which were modified by the user should be transmitted to the server; any which were unchanged on the user's device should be omitted.

There are two possible paths to implementation:
1) Compute a diff between the user's current `SoilData` and the state of the `SoilData` before they began making local changes (requires a thoroughly-tested diff function) -- likely more reliable and reusable long-term
2) Manually track changes made during local mutations -- more brittle, invites more bugs due to burden of recording each change in two places, but easier to get out the door quickly

1) is preferred, but we have 2) as an option if it somehow proves infeasible.

**Comment by CourtneyLee333** [comment]
What did we decide about order - should most recently pushed data win, or most recently entered data should win?

**Comment by tm-ruxandra** [comment]
@CourtneyLee333 Most recently pushed.

**Comment by DerekCaelin** [comment]
This passed! Courtney and I took turns recording data online and offline, and the app synced as expected. Very exciting to see.
