### ISSUE TITLE
[Offline: Pull] When online, I see up-to-date data pulled from server every [?] seconds

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#2291]
### Acceptance Criteria
- Decide frequency (Derek says 5 minutes :))
- When offline, no pulls are attempted
- When online, user sees data updated at that frequency 
  - Don't pull when the user has unsaved changes in the syncManager
  - Check if this will re-trigger soil ID matches (maybe this is fine either way, but would be nice to do so if and only if data has changed)
- When app is active (in the foreground), pulls happen. Otherwise, no pulls happen

- When verifying, do a quick check of data usage to make sure I wasn't totally off in my estimates

Non-goals:
- Any indicator that a pull is happening or has happened (besides that your data may update)

### Notes
- Very rough data usage ballpark: Looks like a site's data is around 1-2 KB, project's data around: 1-2 KB. Pulling every minute if you have 10 sites would take estimated ~50 minutes to hit 1MB data usage.

**Comment by DerekCaelin** [comment]
every 5 mins while app is in foreground?

**Comment by knipec** [comment]
This and #2292 should be in future v216
