### ISSUE TITLE
[Offline] When app starts or user comes back online, I see updated server data

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#2292]
### Acceptance criteria
- When:
  - app starts and is online, or 
  - user returns from offline to online
- Then:
  - pull (after push has completed, if there was a push)
- If you have a spotty connection, don't do this repeatedly over and over (I think the debouncing for push would apply here too)

**Comment by knipec** [comment]
This and #2291 should be in future version 216

**Comment by DerekCaelin** [comment]
@knipec has something changed here? When Courtney and I tested offline data collection on 11/14 we found a push and pull when coming from offline to online.

**Comment by knipec** [comment]
@DerekCaelin Hmm, do you know if it did a full pull of all the data? The way the push system works I'd expect the app to receive updated data from server, but only for the sites that had changes to push. So if on 11/14 you didn't also check sites that didn't have pushed changes, I suspect they weren't getting updated data when coming back online yet.

**Comment by DerekCaelin** [comment]
@knipec does this test sound right?
- User A and User B are in a project with sites 1 and 2
- User A goes offline
- User A adds observation to site 1
- User A does nothing to site 2
- User B adds observation to site 2
- User A comes back online

Expected outcome
- User A should see their change reflected in site 1
- User A should see User B's edits to site 2

**Comment by knipec** [comment]
@DerekCaelin Yeah, that sounds right to me!

**Comment by DerekCaelin** [comment]
Courtney and I tested, and this works.
