### ISSUE TITLE
Units of measurement are formatted incorrectly in Spanish

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#2296]
### App Version

1.1 (195)

### Platforms

- [ ] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

Units show up with extra punctuation in Spanish

### Steps to Reproduce

1. Set phone system language to Spanish
2. Go to a Project's input tab. Set Soil Pit Depths to Custom... and look at the table header for depth
Code in DepthTable:
``` 
  headers.push(t('projects.inputs.depths.depth', {units: 'cm'}));

```

I have also seen this behavior on a couple other components: 
SlopeShapeInfoContent
```
      <Text>
        <Trans
          i18nKey="slope.shape.info.description"
          values={{units: 'METRIC'}}
          components={{
            bold: <Text bold />,
          }}
        />
      </Text>
``` 
SoilPropertiesDataTable
```
text={t('site.soil_id.site_data.soil_properties.depth', {
  units: 'METRIC',
})}
```

### Expected behavior

"Profundidad (cm)", probably?

### Actual behavior

"Profundidad ({{unidades}})" 

### Additional context

<img src="https://github.com/user-attachments/assets/f03e363c-c39f-4b8b-a299-99443ac0f513" width=300>
<img src="https://github.com/user-attachments/assets/0fabe1a9-2636-4fb5-b244-8a92caf6f16f" width=300>
<img src="https://github.com/user-attachments/assets/e43eb031-b46c-4a68-a1c0-28de6ebb6539" width=300>

**Comment by paulschreiber** [comment]
@DerekCaelin Please verify in 199 or later.

**Comment by DerekCaelin** [comment]
We still get this issue on the slope screen, the line where they are emerging appears to be `slope##shape##info##description`

![Image](https://github.com/user-attachments/assets/f5502066-167e-46b8-b612-a9237faa837c)

**Comment by paulschreiber** [comment]
Please verify in 205 or later.
