### ISSUE TITLE
Bullet list on texture info screen fails to wrap

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#2298]
### App Version

1.1 (195)

### Description

BulletList needs to be pulled out of a <Text> component in TextureInfoContent. See comment in BulletList.tsx.

### Additional context

(Repros in both Spanish and English) 
<img src="https://github.com/user-attachments/assets/575d6191-ec6e-45fc-989c-342783945593" width=300>

**Comment by knipec** [comment]
Triage notes: 
- Someone take a look at this task and see if there's a quick fix to do prior to component work
- @CourtneyLee333 to make a component library task for the BulletList 
- Third party list component that Paul mentioned: https://github.com/jsamr/react-native-li  #1173

**Comment by shrouxm** [comment]
the library suggested [mentions the following styling requirement](https://www.npmjs.com/package/@jsamr/react-native-li#what-to-do-when-text-in-list-items-overflows):
> What to do when text in list items overflows?
> Don't forget to add flexShrink: 1 to your Text element.

1 is the default value for flexShrink on the web, but [not in react native](https://reactnative.dev/docs/flexbox#flex-basis-grow-and-shrink):
> CAUTION
> Flexbox works the same way in React Native as it does in CSS on the web, with a few exceptions. The defaults are different, with flexDirection defaulting to column instead of row, alignContent defaulting to flex-start instead of stretch, flexShrink defaulting to 0 instead of 1, the flex parameter only supporting a single number.

**Comment by knipec** [comment]
Confirmed fixed in v200
