### ISSUE TITLE
Console error "i18next::pluralResolver: Your environment seems not to be Intl API compatible, use an Intl.PluralRules polyfill."

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#2303]
### Description

I believe this was introduced with the Spanish changes

### Steps to Reproduce

1. In a dev environment, open the app
**Expected behavior:** No console error
**Actual behavior:**
![image](https://github.com/user-attachments/assets/2dbe441e-4bfc-4159-9cae-a0deaf4e90f0)

**Comment by paulschreiber** [comment]
Please verify in 198 or later.

**Comment by knipec** [comment]
Looks good to me!
