### ISSUE TITLE
Wrong translation for "Soil texture" on soil tab in Spanish

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2363]
### App Version

199

### Platforms

- [ ] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

The translation for "Soil Texture" should be "Textura de suelo" but is instead much longer. The wrong translation was provided.

**Derek corrected this in POEditor, we just need a new translation build.** 

### Steps to Reproduce

1. Open the app in spanish
2. Go to a site
3. Open the soil tab
4. see issue

### Expected behavior

"Soil texture" should be "Textura de suelo"

### Actual behavior

"Soil texture" is longer string

### Additional context

<img width="200px" src="https://github.com/user-attachments/assets/378a42fa-ce16-44a9-b6a9-477a63ef711e">

**Comment by DerekCaelin** [comment]
Labeling this a P1 because it confuses the user. We should not release Spanish with this issue unresolved.

**Comment by tm-ruxandra** [comment]
We just need to ingest the updated PO file to fix this.

**Comment by DerekCaelin** [comment]
(This string will change when we replace "Soil Texture" with "Texture Class" with #2225 - maybe we save time and do that.)

**Comment by DerekCaelin** [comment]
Closing as irrelevant once we implement 2225

**Comment by DerekCaelin** [comment]
obsolete with #2225.
