### ISSUE TITLE
Offline UI: Projects not available offline

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2368]
On the project screen, inform a user who is offline that projects are not available by displaying a "you can't do that offline" notice and hide the project list.

## References
- https://github.com/techmatters/terraso-product/issues/1021 
- https://github.com/techmatters/terraso-product/issues/1117

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10346-10386&node-type=frame&t=1cPOpawF7xV05phQ-0)
<img width="300px" src="https://github.com/user-attachments/assets/a9fb226b-0bdb-4571-8118-880a55c65063">

## Acceptance Criteria
- [ ] As a user who is offline and views the projects screen
    - [ ] display offline notification
    - [ ] hide project list
- [ ] As a user who goes offline while looking at a project
    - [ ] redirect to the project screen

**Comment by tm-ruxandra** [comment]
Appears to have been completed in #2374.
