### ISSUE TITLE
Offline UI: bottom sheet can't create sites offline alert

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2369]
Inform users that they can't create sites while offline. (Future enhancement: allow users to create sites while offline.)

References:
- https://github.com/techmatters/terraso-product/issues/1117

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10463-16911&node-type=frame&t=4gl5NKSP0imlvgSa-0)

![Image](https://github.com/user-attachments/assets/06854ff1-3f91-4482-9aee-adbbdbc003e8)

## Acceptance Criteria
- [ ] If I am offline Display "You are offline, can't create sites" alert on the bottom sheet

**Comment by paulschreiber** [comment]
The first half of this (empty sites list) is done. Second half (regular site list) needs doing.

**Comment by DerekCaelin** [comment]
The bottom sheet is missing in 217.

**Comment by CourtneyLee333** [comment]
Looks good!
