### ISSUE TITLE
Offline UI: Disable site privacy radio buttons

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2370]
On unafilliated sites, while offline, disable radio buttons for site privacy:
<img width="432" alt="image" src="https://github.com/user-attachments/assets/3de976bf-9cb1-42f3-a47e-37eb1e3b01d1">

**Comment by paulschreiber** [comment]
Please verify in 215 or later.

**Comment by DerekCaelin** [comment]
This meets my expectations, ove
