### ISSUE TITLE
Offline UI: Disable site settings

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2371]
While offline, disable options on the site settings screen.

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10604-16804&node-type=frame&t=aNOkjDj8zfXau8az-0)
<img width="323" alt="image" src="https://github.com/user-attachments/assets/13cca913-91f8-4584-9ac7-2bae3514440b">

**Comment by paulschreiber** [comment]
Please verify in 219 or later.

**Comment by DerekCaelin** [comment]
this meets my expectation
