### ISSUE TITLE
Offline UI: Alert: Soil Properties Score not avillable offline

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2372]
When offline, make an alert saying the soil properties score will be used offline.

References:
- https://github.com/techmatters/terraso-product/issues/1117

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9314-5377&node-type=frame&t=aNOkjDj8zfXau8az-0)
<img width="405" alt="image" src="https://github.com/user-attachments/assets/52463ea5-d5c1-43cc-b591-3eff64cffb3f">

## Acceptance Criteria
- [ ] If the user is offline and views the Soil ID screen, show the most recent soil property score calculated (do not try to update the soil property score) and display this error.

**Comment by DerekCaelin** [comment]
I added more information in the acceptance criteria.

**Comment by paulschreiber** [comment]
@DerekCaelin the UI part is done and you can verify that in 217. @tm-ruxandra will implement the score data separately. (Don't close out the issue until both parts are done.)

**Comment by DerekCaelin** [comment]
OK, I will review when both parts are finished

**Comment by CourtneyLee333** [comment]
Looks good!
