### ISSUE TITLE
Offline UI: Projects not available offline

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2373]
While offline, hide everything on the Projects screen and display an alert

References:
- https://github.com/techmatters/terraso-product/issues/1117

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10346-10425&node-type=section&t=aNOkjDj8zfXau8az-0)
<img width="428" alt="image" src="https://github.com/user-attachments/assets/65503873-0cf0-44e7-86ba-cb478f5c22c4">

**Comment by paulschreiber** [comment]
Please verify in 217 or later.

**Comment by DerekCaelin** [comment]
Looks great

**Comment by CourtneyLee333** [comment]
It looks like the paragraph text isn't using the color specified in the design. 
The paragraph is missing a period at the end.

**Comment by paulschreiber** [comment]
The period and color are fixed in 218.

**Comment by CourtneyLee333** [comment]
Closing this, with the expectation that the details will get fixed in the component implementation issue.
