### ISSUE TITLE
Offline UI: Notes: Disable add site notes, disable manipulates

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2374]
While offline, change the Notes screen experience.

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10643-15334&node-type=section&t=aNOkjDj8zfXau8az-0)
<img width="252" alt="image" src="https://github.com/user-attachments/assets/69e69426-9fd1-4458-b3f9-3f8d057dd4ad">

## Acceptance Criteria
- [x] add alert
- [x] remove "Add note" button
- [x] disable edit icon button

**Comment by paulschreiber** [comment]
Please verify in 217 or later.

**Comment by DerekCaelin** [comment]
this meets my expectations

**Comment by CourtneyLee333** [comment]
Looks good to me.
