### ISSUE TITLE
Offline UI: prevent logging out/deleting account

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2376]
When a user is offline, disable the option to sign out and delete account.

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9314-5129&node-type=canvas&t=aNOkjDj8zfXau8az-0)
<img width="354" alt="image" src="https://github.com/user-attachments/assets/54054e02-cf75-42e6-a820-ddc980c83e13">

## Acceptance criteria
- [ ] If offline, on settings screen
   - [x] disable delete account button
   - [ ] disable sign out button

**Comment by shrouxm** [comment]
should be QA-able in versions 210 and above

**Comment by DerekCaelin** [comment]
@shrouxm Both buttons appear to be disabled, but I can interact with "sign out"

**Comment by shrouxm** [comment]
🤔 must be because it opens a modal. will have to look into it when i get back

**Comment by DerekCaelin** [comment]
Unassigning Garo while they are out - any engineer can pick this up.

**Comment by DerekCaelin** [comment]
@paulschreiber Both buttons appear to be disabled, but I can interact with "sign out"

**Comment by paulschreiber** [comment]
@DerekCaelin this is pending #2594. Should be in 219 or later.

**Comment by DerekCaelin** [comment]
This meets my expectation
