### ISSUE TITLE
soil cracks: implement new help text

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2378]
Update soil cracks module with new text. See [parent issue for details.](https://github.com/techmatters/terraso-product/issues/1076)

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10684-12570&node-type=section&t=FllvXiOQe7LDojDx-0)
<img width="374" alt="image" src="https://github.com/user-attachments/assets/72e02334-7607-42ff-a182-3cbd6213dc93">

- dependent on https://github.com/techmatters/terraso-product/issues/1085

## Acceptance Criteria
- [ ] Update screen title to "Soil Cracks"
- [x] Add helper text use select component with label
- [ ] Move image to below select field
- [ ] Update helper text

**Comment by shrouxm** [comment]
could you clarify the change related to the select component? the app appears to already be using a select component with a label for this screen (at least in the code) :thinking:

**Comment by DerekCaelin** [comment]
You're right, it looks like that component was already implemented with: 
https://github.com/techmatters/terraso-product/issues/1085

**Comment by DerekCaelin** [comment]
Duplicate of https://github.com/techmatters/terraso-product/issues/976
