### ISSUE TITLE
Terminology updates - Change/Delete depths warning dialog

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2467]
Update the dialogs for the change depth experiences. 

## Design
![image](https://github.com/user-attachments/assets/88d1e16b-a91f-42d8-b0dc-65f49fb8268e)
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10731-13005&node-type=frame&t=Qqa0NUYJwdrkxrVV-0)

## Acceptance Criteria
**Change Depths warning dialog**

- [ ] `Soil pit data` -> `Soil pit observations`

**Delete Depth warning dialog**

- [x] `Data that has` -> `Observations that have`

**Comment by DerekCaelin** [comment]
@paulschreiber The "Delete Depth" dialog has the right language, but the "Change Depth" dialog still says "Data"

**Comment by paulschreiber** [comment]
Please re-verify in 210 or later.
