### ISSUE TITLE
Terminology updates - Team management

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2468]
Make updates to the project team management screen and dialog windows

## Design 
![image](https://github.com/user-attachments/assets/fe2614b3-84cd-43c4-af4e-8fc7c19f92d0)
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10731-13062&node-type=frame&t=Qqa0NUYJwdrkxrVV-0)

## Acceptance Criteria
**Add Team Member**
- [x] Viewer: `Can view site data` -> `Can view site data and observations`
- [ ] Contributor: `Can view, add, and edit site data` -> `Can view site data, add and edit observations`

**Manage Team Member**
- [x] Viewer: `Can view site data` -> `Can view site data and observations`
- [ ] Contributor: `Can view, add, and edit site data` -> `Can view site data, add and edit observations`
- [x] Remove from project: `data` -> `observations`

**Remove Member dialog**
- [ ] New dialog: `This will remove the team member from the project. Their contributed site observations will be retained.`

**Comment by DerekCaelin** [comment]
- Team member "Remove From Project" experience says `"Yheir contributed"`
- Contributor dialog says `"and add and edit"`

**Comment by paulschreiber** [comment]
Fixed the first one. Second one is correct. Please verify in 210 or later.
