### ISSUE TITLE
Soil Info page: add LCC Subclass

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2481]
Currently, LCC displays a class level (e.g., 1-7) but to be useful it needs to display subclass (e.g., e, s-t, s-d, etc).

This information is already available in the graphql response as soilInfo.landCapabilityClass.subClass

## References
[Spec](https://docs.google.com/document/d/1fBxZqAGP92OAqlsLW_SyDHcRK3TTM2UvB2emQGJ381I/edit#heading=h.54w02ys7n8ko)

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-12771&t=A0doyci49YB1KGKL-0)

<img src="https://github.com/user-attachments/assets/96f22ef0-2f36-4db6-b346-575fc10cf475" width="200px">

## Acceptance Criteria
- [ ] On Soil Info page, where I see LCC Class, I want to see subclass, so I know the limiting factors of my soil.

**Comment by shrouxm** [comment]
can be QA'd in versions 214 and above
