### ISSUE TITLE
Soil Info screen: overly specific distance for location score 

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2496]
### App Version

208

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

When viewing the Soil Info page of a potential soil that is **outside** the user's current map unit, the distance count is overly specific (too many decimals to be helpful).

### Steps to Reproduce

1. Create site at `37.27636, -122.00441`
2. Go to Soil ID page
3. Select soil candidate low-down in probability (e.g., "Fagan")
4. Look at location score
5. See issue

### Expected behavior

Number rounds to the nearest meter

### Actual behavior

No rounding, too many decimal points to be useful displayed

### Additional context

<img width="200px" src="https://github.com/user-attachments/assets/5d109dc7-7c91-42e1-8471-653190e96cbe">

**Comment by DerekCaelin** [comment]
Assigning pri 3 because the user's intent is not blocked - it just lacks polish.

**Comment by paulschreiber** [comment]
Please verify in 209 or later.
