### ISSUE TITLE
Soil match part 1 — select soil

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2506]
Allow the user to declare, after reviewing their own site's data and information provided by the Soil ID algorithm, what the selected match for Soil ID is. Expectation is to have as small a scope as possible with the intention to improve with https://github.com/techmatters/terraso-product/issues/658

Part 2 is https://github.com/techmatters/terraso-mobile-client/issues/1162

## Designs
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-14751&t=ZiX409rcZeu01oPp-0)

#### Design
<img src="https://github.com/user-attachments/assets/e6808fb9-1894-4c74-9394-db4b08b3d5c7" width="200px">

### What's in
- checkbox declaring soil is a match
- backend - store the information
- Top of soil ID screen shows selected soil
- Soil ID card says "selected soil" and not "top match"

- [ ] As a manager or contributor, I want to be able to state whether a given soil is  the correct match for a site  so that the site will either have an official SoilID and Ecological Site ID, or eliminated possible values
- [ ] Once I have rated a soil, its status is reflected in the UI of the relevant Soils ID page, so I can see at a glance my progress in selecting a soil to match a site.

**Comment by CourtneyLee333** [comment]
@tm-ruxandra what release will this be in?

**Comment by CourtneyLee333** [comment]
Will be available in 216.

**Comment by DerekCaelin** [comment]
I followed [these tests](https://docs.google.com/spreadsheets/d/14e9yr5m5JeASbjJKvjvIkYDCtpm4Cw40vr6iZUquwOA/edit?gid=2004954072#gid=2004954072). This experience is OK by me. I found I had to tap a few times check the tiny box on my screen.  Over to Courtney.
