### ISSUE TITLE
Selecting "back" in site or project crashes app

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2510]
### App Version

210

### Platforms

- [ ] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

When viewing a site or project dashboard, if the user taps the "back" arrow or uses gestural controls, the app will crash. 

### Steps to Reproduce

1. Open site or project
2. select Back
3. See issue

### Expected behavior

Go to sites screen

### Actual behavior

Crash

**Comment by paulschreiber** [comment]
Crash is `viewpager2 does not support direct child views`.

**Comment by paulschreiber** [comment]
Filed https://github.com/software-mansion/react-native-screens/issues/2529

**Comment by paulschreiber** [comment]
Please verify in 211 or later.
