### ISSUE TITLE
Bottom sheet missing if there are no sites on signin

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2512]
### App Version

210

### Platforms

- [X] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

When the user opens the app and has no sites, the bottom sheet does not appear.

### Steps to Reproduce

1. have no sites
2. sign in
3. see issue

### Expected behavior

Site bottom sheet is visible

### Actual behavior

no site bottom sheet is visible

### Additional context

site bottom sheet reappears if user creates a site

site bottom sheet stays if user creates and deletes a site, until closing and reopening the app

**Comment by paulschreiber** [comment]
This broke with https://github.com/techmatters/terraso-mobile-client/pull/2338.

**Comment by paulschreiber** [comment]
Please verify in 212 or later.
