### ISSUE TITLE
Offline UI: Disable checkbox for selected soil when offline

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#2516]
When offline:
- If there is a selected soil for a site, I can click on it. Scrolling down on the resulting screen, I see a checkbox for selecting the correct soil. The checkbox should be disabled, because setting it when offline is not yet supported by our local changes mechanism.
- If there is any other way to view soil match tiles while offline, make sure clicking on them brings up a screen with the checkbox disabled as well.

This should be the state after https://github.com/techmatters/terraso-mobile-client/issues/2506 but before https://github.com/techmatters/terraso-product/issues/1055

**Comment by CourtneyLee333** [comment]
I don't know what release this will be in, but I can't test on 216 because Top Match list returns errors for every site when offline.

**Comment by CourtneyLee333** [comment]
Looks good!
