### ISSUE TITLE
Connect project inputs settings page to backend

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#253]
Specifically, the "inputs" tab that asks for soil information source and units settings

**Comment by shrouxm** [comment]
@CourtneyLee333 @ltseng i'm unclear based on above discussion if there's still product/design decisions to be made before implementing? 

also i'm confused about the setting for "default soil information source". i thought the central point of the US/intl app split is that this setting is confusing and will always be set to "NRCS" in the US app and "SoilGrids" in the intl app?

**Comment by CourtneyLee333** [comment]
There are still design decisions being made (hence the "WIP" in the name of the frame in Figma.) I just learned today that SoilGrids won't apply to the US app. And units of measurement might get moved. Still have some decisions to make on some of the input requirements.

**Comment by ltseng** [comment]
Ready for development now! See Courtney's most recent designs.
