### ISSUE TITLE
Sync: Implement pull retry mechanism

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#2556]
### Scenario
A user makes a change to soil data while a pull has already started happening. We don't want to clobber the user's change with the pulled data. But we also don't want to totally ignore the pull and have to wait for the next one if it will be a long time between pulls.

### Proposed solution
Implement a pull retry mechanism. 
Probably do something in soilIdGlobalReducer.ts, in the fulfilled case for fetchSoilDataForUser

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added a pull retry mechanism in the soilIdGlobalReducer.ts file to handle scenarios where a user makes changes to soil data while a pull is in progress. This prevents clobbering user changes with pulled data and ensures that pulls are not entirely ignored.

You can review changes in this commit: https://github.com/lkilu6456546/techmatters-terraso-mobile-client-2556/commit/89f4a25c8a6dce70adaea7e774de5211bd8afb28.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by knipec** [comment]
Actually this isn't needed because setSoilData does mergeUnsyncedEntities, so we won't clobber the user's changes. Closing.
