### ISSUE TITLE
Add GPS refresh to Create Site form

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#256]
The Create Site form needs a way to refresh the GPS coords when the user moves around.

**Comment by ltseng** [comment]
Decided to auto-update GPS coordinates as user moves around without need for extra button. Leaving specific interval/refresh period to engineers

**Comment by CourtneyLee333** [comment]
Just doing a quick bit of research, I found [this article](https://www.workyard.com/employee-time-tracking/gps-tracking-battery-life) and got some takeaways:
- Dedicated GPS devices, optimized for battery life and such, can be used along with the mobile device they are using for the app. I wonder how common such a device is around the world?
- Extreme temperatures affect battery life, and I don't know what we can do about that. 
- We can set the GPS to be active only when the user is using GPS related functions - like the home screen map and site creation form - and to only refresh the location if they move.
