### ISSUE TITLE
Offline UI: Temporary Site Popover - Soil ID data not available offline, disable buttons

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2560]
Changes to the popover for temporary sites.

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10368-5034&node-type=instance&t=aNOkjDj8zfXau8az-0)
<img width="324" alt="image" src="https://github.com/user-attachments/assets/7d316daa-6daf-4d0e-921e-c16ff3c90cc0">

<img width="397" alt="image" src="https://github.com/user-attachments/assets/76782daa-baad-418e-a430-bdda6cace61e">

## Acceptance criteria
- [ ] When offline, and the user taps the map, display `"NOT AVAILABLE OFFLINE"` for Top Matches and Elevation. 
- [ ] Disable "Create Site" and "Learn More" buttons

**Comment by paulschreiber** [comment]
Please verify in 216 or later.

**Comment by DerekCaelin** [comment]
This meets my expectations.

**Comment by CourtneyLee333** [comment]
Niiiiice.
