### ISSUE TITLE
Update content on Sites screen infosheet

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#2564]
Task: Update the middle section of the infosheet to use content that reflects what's in the bottom sheet about how to use the map to create a site. 

[Figma link](https://www.figma.com/design/KMJb
![Screenshot 2024-11-27 at 12 52 46 PM](https://github.com/user-attachments/assets/8e4faf48-332a-4965-b5b6-ae44c70c40eb)

**Comment by CourtneyLee333** [comment]
@paul The periods are inconsistently used - the first two have a period, the third doesn't. I don't care which route you go, but they should be consistent. Otherwise, this looks good and passes my review.

**Comment by paulschreiber** [comment]
Periods have been removed — this will be in 220 or later.
