### ISSUE TITLE
Login requires restarting the app

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#257]
## Description
Logging into the app returns the user to the login screen. They need to restart the app in order to be able to access the home screen.

This should be easy to fix, but is obviously a high priority bug.

@paulschreiber @ltseng @CourtneyLee333 @Hanal-code FYI for when you try logging in yourselves

## Steps To Reproduce

Try to log in.

**Comment by ltseng** [comment]
I think it happens each time the app is updated. Once I've signed in, and don't need to update again, the issue necomes much less frequent.

**Comment by david-code** [comment]
See https://github.com/techmatters/terraso-mobile-client/pull/280 and https://github.com/techmatters/terraso-mobile-client/pull/280#issuecomment-1681082748
