### ISSUE TITLE
"Transfer sites" floating button location overlaps search bar when no sites

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#2618]
### App Version

217

### Platforms

- [ ] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

- I presume this is because it's a FAB (floating action button), so expects to overlap content, which makes sense when the list of sites is long

### Steps to Reproduce

1. Log in with a user that has no sites (or delete all your sites) and only 1 project
2. Go to the project, to the "sites" tab, and then click the transfer sites button 

### Expected behavior
Maybe work with design to figure out 

### Actual behavior
With 1 existing site:
![image](https://github.com/user-attachments/assets/b46a024e-4016-4b04-8b21-bf27b1089791)

With 2 existing sites:
![Screenshot 2024-12-09 at 4 58 17 PM](https://github.com/user-attachments/assets/3283ffe1-4959-4d6e-a44e-a5ea748d06d2)

**Comment by CourtneyLee333** [comment]
This will be addressed by the button component work. Doesn't seem to me to be worth a one-off effort.

**Comment by knipec** [comment]
Duplicate of #1856
