### ISSUE TITLE
Add placeholder images to sites in list view

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#267]
<img width="225" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/e340a04d-8252-40e9-9937-3508fc5ec75a">

**Comment by CourtneyLee333** [comment]
@ltseng I'm expecting an aerial view. We talked about the possibility of the user selecting an image for this space, which would be great, but I don't think that's included in MVP.

**Comment by ltseng** [comment]
So the engineers can probably choose some random aerial image to use as a temporary thumbnail
