### ISSUE TITLE
QA: Site Creation Form

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#272]
# Description

This issue covers the test cases for the Site Creation Form (Create site - form in the Google Doc)

# Test Cases

- User can enter the site name into the form title
- An error message is displayed if the user enters too short of a site name in the input for site name
  - Limitation: The validation might not match the spec for valid site names exactly, but this can be updated fairly easily
- User can use their current position to create a site
  - Note: This option should only be available if the user has turned their GPS on and shared location permissions with the app
  - Limitation: Haven't tested without GPS location or if user rejects permission, this might cause a crash
- User can use map pin to create a site
   - Note: This should only be available if the form is accessed by dropping a pin on the map
- User can manually enter latitude and longitude of a location
- If user enters in invalid latitude and longitude values, an error message should be displayed
- A user can select to add the site to a project in which they are manager 
- When a project is selected, the site privacy should be set to match the project privacy and the privacy input should be disabled
- If a project is not selected, the site privacy should be able to be set to public or private
- Switching between entry mode (current location, map pin, custom) should NOT reset any inputs beside the longitude and latitude inputs

[Test case document](https://docs.google.com/spreadsheets/d/1cS7BuuzbX0BC4m68rqpj5vMgtC0J8KHlIMgcntQTpjs/edit#gid=1667723721)

```[tasklist]
### Bugs to fix for usability study
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/305
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/312
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/315
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/352
```

```[tasklist]
### Bugs to fix later
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/302
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/310
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/392
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/395
```

**Comment by ltseng** [comment]
Writing up test cases [here](https://docs.google.com/spreadsheets/d/1cS7BuuzbX0BC4m68rqpj5vMgtC0J8KHlIMgcntQTpjs/edit#gid=0)

**Comment by CourtneyLee333** [comment]
@ltseng I'm done with this one.

**Comment by Hanal-code** [comment]
Blockers for UT:
1) Create site button in Location popover doesn't work.
2) Close button in Location popover doesn't work.

**Comment by ltseng** [comment]
Logged in https://github.com/techmatters/terraso-mobile-client/issues/305, which I'm putting in the tasklist above.

**Comment by Hanal-code** [comment]
iOS 24: 
The lat & long fields don't show the error message when they are empty.
The name field stops showing the error message when the lat or long field is empty.

**Comment by ltseng** [comment]
That feedback has already been noted in https://github.com/techmatters/terraso-mobile-client/issues/310
