### ISSUE TITLE
QA: Create Project screen

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#273]
# Description

This issue is for the Create Project screen, which can be accessed by the Project list view.

# Test Cases

- Project name can be added in the project name input.
- If user enters too short of a project name and focuses outside of the project name input, an error message is displayed.
  - Limitation: Verification might not match spec, I think only the name length is verified
- User can enter a project description. This is optional, and a project should be able to be created without a description.
- User can select public or private data privacy
  -  Limitation: project privacy help message not implemented
- When user creates a project, they are redirected to the Project List view. 
- The project should be displayed in the list, and the information should match the data input in the creation form.

[Test case document](https://docs.google.com/spreadsheets/d/1cS7BuuzbX0BC4m68rqpj5vMgtC0J8KHlIMgcntQTpjs/edit#gid=1667723721)

```[tasklist]
### Bugs to fix for usability study
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/307
```

```[tasklist]
### Bugs to fix later
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/301
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/308
```

**Comment by CourtneyLee333** [comment]
@ltseng @Hanal-code I'm done with this one. I'm using bold in the spreadsheets to indicate what is critical for UT.

**Comment by Hanal-code** [comment]
Tested on iOS 24:
Tapping Save didn't go to the list view from Create Project form. 
It worked before this release.

**Comment by david-code** [comment]
> Tested on iOS 24: Tapping Save didn't go to the list view from Create Project form. It worked before this release.

@Hanal-code I think the issue #307 was for the user to go to the project dashboard itself instead of the project list.

**Comment by Hanal-code** [comment]
@david-code I see. What I meant above is that I was stuck in Create Project form screen -- didn't go anywhere. 
- Data Privacy radio buttons didn't respond properly(some delay?)  


[screenshot]
<img width="240" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/92342777/1fd9272a-ca63-4b9c-a891-ab208637994c">

**Comment by ltseng** [comment]
Were you able to replicate this more than once @Hanal-code?

I've noticed that sometimes the buttons take more than one click to properly activate, and on other occasions, the save action is delayed a couple of times.

**Comment by Hanal-code** [comment]
@ltseng Yes, more than once with iOS 24.

**Comment by ltseng** [comment]
On iPad or iPhone, specifically?

**Comment by Hanal-code** [comment]
@ltseng iPhone 13 Pro + iOS 16.6. After rebooting the phone a couple of times, I noticed the responsiveness has improved. It proceeds to Project Settings screen now. Rebooting the device was the answer?!

**Comment by ltseng** [comment]
I guess so! This shouldn't have been the case though. We'll have to keep an eye on this moving forward.

**Comment by Hanal-code** [comment]
Done with the review. Removing myself
