### ISSUE TITLE
QA: Project List View

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#274]
# Description

This QA issue is for the Project List View

# Test Cases

- If the user is not a member of any project, a filler message is displayed.
  - Limitation: The link doesn't go anywhere yet 
- A button "Create Project" is displayed, which redirects the user to the Create Project screen
- If the user is a member of a project, the project is displayed in a list
  - Limitation: filter has not been implemented
  - Limitation: does not match the latest mockup
-  Clicking on the "go to project" link displays the project view

[Test case document](https://docs.google.com/spreadsheets/d/1cS7BuuzbX0BC4m68rqpj5vMgtC0J8KHlIMgcntQTpjs/edit#gid=1667723721)

```[tasklist]
### Bugs to fix for Usability Study
- [ ] Projects list view does not match mockups
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/351
```

```[tasklist]
### Bugs to fix later
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/309
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/396
```

**Comment by ltseng** [comment]
@david-code one of the test cases refers to a member seeing projects that they're a part of. However, it's my understanding that the feature to add a member to a project doesn't exist yet. Is that accurate? Otherwise, I'm writing the test cases for the usability study to be run purely from a Manager's perspective.

**Comment by david-code** [comment]
> However, it's my understanding that the feature to add a member to a project doesn't exist yet. Is that accurate?

@ltseng Yeah, that's correct! Sorry for the misunderstanding.

**Comment by ltseng** [comment]
Awesome, thanks for confirming!

**Comment by CourtneyLee333** [comment]
@ltseng I'm done with this one.
