### ISSUE TITLE
Create re-usable map component

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#28]
We should move the map logic to a map component we can re-use in the different screens which show maps

**Comment by shrouxm** [comment]
Moving this back to Todo and untracking it because I'm not sure if we will in fact have different screens which show maps.

**Comment by ltseng** [comment]
I think we have moved away from the idea of having more than one map. Tagging @CourtneyLee333 to confirm

**Comment by CourtneyLee333** [comment]
For now we only have one map.
