### ISSUE TITLE
QA: Site List View

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#282]
## Description
This issue is for the home screen's site list view, which can be accessed in the bottom sheet.

## Test Cases
- Pulling up on the bottom sheet expands the list.
- When there are more sites than will fit on the screen, the list scrolls so that all sites can still be viewed.
- Tapping the title of a site opens the location dashboard for that site.
- Tapping the map icon on the bottom corner of a site card centers that site on the map.
  - Question: currently tapping the map icon centers the site, but does not change the zoom level. Should we zoom to a particular level?

[Test cases](https://docs.google.com/spreadsheets/d/1cS7BuuzbX0BC4m68rqpj5vMgtC0J8KHlIMgcntQTpjs/edit#gid=1723273706&range=A1)

```[tasklist]
### Bugs to fix for Usability test
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/378
```

```[tasklist]
### Bugs to fix later
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/306
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/289
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/311
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/366
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/406
```

**Comment by ltseng** [comment]
Tagging @CourtneyLee333 in for this discussion as well

> Question: should tapping anywhere on the card open the location dashboard or just the title?

I think the site title might be a little too small and would prefer the full card, but I haven't tried to interact with it on any of my devices yet.

> Question: currently tapping the map icon centers the site, but does not change the zoom level. Should we zoom to a particular level?

I think yes, perhaps defaulting to matching Google Maps's scale of a 400-1000 m radius when you first open the app?

**Comment by CourtneyLee333** [comment]
What I'm seeing on the site card does not match the design, so I'm not sure if I'm seeing the right version of the app and what level of design detail I should be paying attention to.

**Comment by david-code** [comment]
@CourtneyLee333 I think we need to release a new version for Android and iOS. I'll do this once I take a look at Garo's latest PR.

**Comment by ltseng** [comment]
Just created a site for the first time and saw this card, so I'm guessing that I'm seeing the same thing Courtney does?

![Screenshot_20230817-083848_Terraso LandPKS.jpg](https://github.com/techmatters/terraso-mobile-client/assets/2730009/257d155c-f5ff-465a-a776-f972c30ae708)

**Comment by david-code** [comment]
@ltseng Yeah, I think that's probably expected. I think we should hold off on testing any of the QA issues Garo has created until we make a new release

**Comment by Hanal-code** [comment]
Site List (bottom sheet) opens 100% of available space, but the mockup indicate, the map should be visible. a bug or a finesse to-do? 


![Image](https://github.com/techmatters/terraso-mobile-client/assets/92342777/4498e690-fa28-44a4-b49a-928f7f69cb6e)
