### ISSUE TITLE
QA: Manage a site

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#283]
## Description
This issue is for managing a site via the location dashboard. Note that the relevant PR #277 hasn't landed yet, I will update this issue when it has.

## Test cases
- Location dashboard displays satellite view of site with pin.
- The details accordion can be expanded to show  site metadata.
- Within the details accordion, the site's privacy status can be toggled.
- The settings button in the top right can be used to navigate to the site's settings page, where the site's title can be changed.
  - Limitation: There are many other buttons on this page that do not work.
```[tasklist]
### Bugs to fix for usability study
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/339
```

**Comment by ltseng** [comment]
Tagging @CourtneyLee333 in here too

> Question: should the map be interactive? The default behaviour is that it can be panned, zoomed, etc, which is currently enabled.
Are you talking about the satellite view here? If so, I did not envision it being interactive. 

> Question: the home screen map doesn't display a satellite view at the moment. Should I make the location dashboard view the same map style for consistency for now?
That would be nice, but not imperative

> Question: should the accordion be expanded by default?
Hm, I think not, but defer to Courtney

> Question: this settings page was implemented a while ago, I'm not sure if it's still how courtney is envisioning the site management UI to work. Should I just disable/remove the settings button for now
Deferring to Courtney. If the privacy toggle works here, then I think we're safe to remove the button?

**Comment by shrouxm** [comment]
to clarify the last point, the settings page doesn't contain the privacy toggle, it contains buttons/inputs to change e.g. the site's name, project, or delete the site. (only the name change is currently functioning)

**Comment by CourtneyLee333** [comment]
edit: I can get past the login screen by restarting the app

**Comment by ltseng** [comment]
Courtney and I chatted, here is what we settled on:

> Question: should the map be interactive? The default behaviour is that it can be panned, zoomed, etc, which is currently enabled.

Dashboard image should be an aerial/satellite snapshot, not an interactive map.

> Question: the home screen map doesn't display a satellite view at the moment. Should I make the location dashboard view the same map style for consistency for now?

Keep the aerial/satellite view on the dashboard, and if you can't display the pin, it's fine. The site dashboard image should be more specific/detailed than the general map view, though we are definitely counting on the home screen map supporting a satellite layer later.

> Question: should the accordion be expanded by default?

Yes, expanded by default. In the future, it would be nice to remember if a user minimized the accordion, so that the next time they visit that exact site, the accordion is minimized already, but it's not critical.

> Question: this settings page was implemented a while ago, I'm not sure if it's still how courtney is envisioning the site management UI to work. Should I just disable/remove the settings button for now

We'd actually like to see what you have for the settings page before saying whether to keep it or remove it.

**Comment by shrouxm** [comment]
here is the current settings screen: 
<img src="https://github.com/techmatters/terraso-mobile-client/assets/3411715/391948a8-656e-4e43-be04-53d4f52802a8" width="40%" height="40%"/>

**Comment by ltseng** [comment]
I think we don't mind leaving this in for now.

**Comment by ltseng** [comment]
Should this come back to me now for writing test cases?

**Comment by david-code** [comment]
@ltseng I think so

**Comment by ltseng** [comment]
Logged https://github.com/techmatters/terraso-mobile-client/issues/339 for that @Hanal-code

**Comment by ltseng** [comment]
Closing this task out - this flow is ready for the usability test!
