### ISSUE TITLE
Placeholder text in sites list flashes before loading sites when opening app

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#289]
## Description
When I first open the app, since I've already created a site, I wouldn't expect the sites placeholder text to appear in the bottom sheet. Instead, I see the text "Soil Science in your hands" flash before the full sites list is loaded.

## Steps To Reproduce
1. Create a site
2. Close the app
3. Reopen the app (pay attention to the bottom sheet)

## Expected behavior
See full sites list from the beginning, without any placeholder text.

## Actual behavior
"Soil Science in your hands" appears first until the full sites list loads and replaces the placeholder text.

## Additional context
Observed on Android v1.0.1, Samsung Galaxy S10 running Android 12
https://github.com/techmatters/terraso-mobile-client/assets/2730009/fd863013-bf91-4d22-8df7-ee7ec3c8b956

**Comment by ltseng** [comment]
Courtney and I would prefer the second option

**Comment by ltseng** [comment]
To a smaller extent, I'm sometimes seeing the same behavior happen with the placeholder text for projects before the full list of projects loads. It's happened less with newer builds, though.

**Comment by ltseng** [comment]
I'm anticipating that this will still happen even after #378 is done. This is still happening on version 40.

**Comment by shrouxm** [comment]
yes, we have not done anything to fix this so it's expected that it's still broken!

**Comment by ltseng** [comment]
No worries! I was just making this comment in response to Paul's request for a bug scrub

**Comment by ajabeckett** [comment]
@ltseng, could you take another screen recording of this happening on sites and projects? I'm looking through the relevant components, and it's not clear to me how the "Soil Science in your Hands" message is showing up on the bottom sheet. Thank you!

**Comment by ltseng** [comment]
It's not the Soil Science in Your Hnds message any more, it's actually the "you have not created any sites/projects" message.

https://github.com/techmatters/terraso-mobile-client/assets/2730009/92807100-28a2-4786-9b39-88eabd08ea08

**Comment by ajabeckett** [comment]
Got it, thanks!

**Comment by ltseng** [comment]
Re-opening as a reminder to myself to run tests when this is available.

**Comment by ltseng** [comment]
Looks great on iOS and Android!
