### ISSUE TITLE
Adding site to project from site creation form shows wrong privacy

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#302]
## Description
When creating a site and adding it to a project as part of the site creation process, the form displays incorrect project privacy. The project in question was public, but the site creation form showed private. The site seemed to have been created with the correct privacy though.

## Steps To Reproduce
https://github.com/techmatters/terraso-mobile-client/assets/2730009/a00d4f3c-43e2-4fbe-828c-01439b827f8a

**Comment by shrouxm** [comment]
@ltseng i am not able to reproduce this bug locally, does it still occur for you in the latest test apps?

**Comment by ltseng** [comment]
Not seeing it any more on iPad!
