### ISSUE TITLE
Site popover on Home Screen cannot be closed and buttons do not work

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#305]
## Description
The site popover is intermittently unresponsive, i.e. cannot be closed and the "Create Site" and "More Info" buttons do not work. Observed on iOS (iPhone and iPad) only.

## Steps To Reproduce
When trying to create a site through map pin
1. Long press the map to drop a pin
2. Try to click "Create site," the close button, or "More info" on the location popover

When trying to create site using Create site button in bottom sheet
1. Long press the map to drop a pin
2. Click "Create site" in the bottom sheet, give it a valid name, and click Save
3. Try to click "Create site," the close button, or "More info"

When site is already created
1. Open app and select an existing pin

## Expected behavior
When trying to create a site through map pin
1. Create Site button takes user to Create site screen

When trying to create site using Create site button in bottom sheet
1. Site is created, site popover is open by default (though trying to change this behavior ultimately in #312), and popover can be closed/tapping site title takes user to site dashboard

When site is already created
1. Close button works to close the popover
2. Site title can be tapped to take user to site dashboard

## Actual behavior
When trying to create a site through map pin
1. Create site button does not take user to Create site screen

When trying to create site using Create site button in bottom sheet
1. Same general location popover is open and cannot be closed, site does not appear to be saved

When site is already created
1. Close button does not close popover
2. Site title cannot be tapped to take user to site dashboard

## Additional context
[Video recording](https://github.com/techmatters/terraso-mobile-client/assets/2730009/6b4703f3-8919-427b-9851-08fe6de2bdea)

**Comment by CourtneyLee333** [comment]
A bit more context: this seems to only be an issue on iOS. We've used iPhones and iPads to reproduce the issue.

**Comment by shrouxm** [comment]
@paulschreiber: one of our dependencies has an update that isn't released yet which could potentially fix this, can you try updating the dependency as specified here? https://github.com/rnmapbox/maps/issues/2880#issuecomment-1630091579

if that doesn't work, some other potential workarounds are suggested in:
- https://github.com/rnmapbox/maps/issues/2834
- https://github.com/rnmapbox/maps/issues/2751

**Comment by paulschreiber** [comment]
The fix (https://github.com/software-mansion/react-native-gesture-handler/pull/2533) appears to be part of 2.12.1, which was released in July. (Or did I miss something?)

**Comment by shrouxm** [comment]
i don't think it is because they release from branches not from main? on the 2.12.1 branch it looks as though the fix is part of the 34 commits behind main: https://github.com/software-mansion/react-native-gesture-handler/tree/v2.12.1

**Comment by paulschreiber** [comment]
aha.

**Comment by paulschreiber** [comment]
@ltseng Please write out steps to reproduce.

**Comment by ltseng** [comment]
The steps are in the issue

**Comment by paulschreiber** [comment]
There's only one step. It's confusing.

**Comment by ltseng** [comment]
@paulschreiber we're keeping this issue open, but moving it to QA. Please assign to me and Courtney when the fix is released and ready for testing

**Comment by ltseng** [comment]
This may be an unrelated new bug - @paulschreiber can you confirm? https://github.com/techmatters/terraso-mobile-client/assets/2730009/5d69a2a3-ee66-480c-8c11-96af3aae8289

**Comment by ltseng** [comment]
Otherwise, the fix works for me on iPhone. Testing Android now.

**Comment by ltseng** [comment]
Android is unaffected, save for a couple new flashing effects when tapping on Create Site or More info from the popover. Not annoying enough to block the usability study, but should fix before December for sure.

https://github.com/techmatters/terraso-mobile-client/assets/2730009/0730e9bf-f5ee-4803-a52c-37faa8977a93

@CourtneyLee333 can you confirm whether the fix works for you on iPad?

**Comment by ltseng** [comment]
I'll file a new bug report for the issues you brought up @CourtneyLee333. Otherwise, closing this!

**Comment by shrouxm** [comment]
@ltseng i'm not sure i understand what the bug is in https://github.com/techmatters/terraso-mobile-client/issues/305#issuecomment-1692111952?

**Comment by ltseng** [comment]
It's a little hard to see, but at approximately 0:25, when you click "More info" - the black box that would otherwise contain the satellite image of the site loads in before the rest of the dashboard, contributing to a flashing black box effect.
