### ISSUE TITLE
Tapping on map buttons on site cards does not open expected site popover

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#306]
## Description

When using the map icon on the site cards in the sites list view to change my viewport, I expect two things:
- be able to tell which pin is selected/viewed
- open up the site popover

Instead, when I don't open the popover for some random site beforehand, and then use the map icon to zoom to the location of another site, the popover doesn't open. Also, there is not an easy way to determine which pin is selected, which wouldn't normally be an issue since I'm not currently creating sites on top of each other, but right now, the pins are enormous.

## Steps To Reproduce
No popovers open

1. Open app
2. Open sites list view with at least two sites created
3. Tap on pin icon for one site
4. Close bottom sheet to view map (which is also a bug)

One popover open
1. Open app
2. Select a site on the map and open the popover
3. Open the sites list view with at least two sites created
5. Tap on the pin icon for a site that is not the one you have selected
6. Close bottom sheet (which is also a bug)

## Expected Behavior

1. The bottom sheet sheet should close.
2. The map viewport should center on the location.
3. The map marker for that site should be displayed in the "selected" state, which is slightly larger with Elevation 6 style.
4. The site card popover should display with Elevation 18 style.
The result will be the same as if the user had tapped a Site map marker on the map itself, which can be seen in this mockup https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=582%3A36087&mode=design&t=gJYpXXYNt458Ak2R-1

## Additional context
https://github.com/techmatters/terraso-mobile-client/assets/2730009/d65f98d4-2e4a-43e2-a861-ece0c1b6b737

**Comment by ltseng** [comment]
Gonna add this in up above.

**Comment by CourtneyLee333** [comment]
@ltseng IMO this should be fixed before UT, as it's part of the core concept of the site list and map working together. We're trying to vet if this concept is valid. @Hanal-code would you agree?

**Comment by CourtneyLee333** [comment]
Should we leave this open until it passes QA? @ltseng @shrouxm ?

**Comment by shrouxm** [comment]
mm it's a good question. typically we close out issues when it's fixed in development, we don't wait until it's released and validated, so it's easier to keep track of what still needs to be worked on

but we haven't been developing for platforms as finnicky as cross-platform mobile in the past

maybe on a case-by-case basis we could move issues into the "QA" state rather than "Done"? i wasn't here when we created the "QA" status so i'm not sure if it has a specific intended meaning

in the case of this specific issue, i just missed the requirement that the popover should be opened but the code to do so is straightforward so there's no reason to expect that it won't work once released

thoughts? i will defer to whatever makes your QA process easier since it's all the same to me

**Comment by ltseng** [comment]
The QA column is for things that need to be tested. Ideally, both full QA issues with test cases for features, and bug reports would be moved into this column when things are ready to be tested. I'm going to reopen this bug and move it to QA, but leave assigned to @shrouxm until this fix has been released and is ready for us to test, at which point, it should be assigned back to me and @CourtneyLee333 

@david-code and @paulschreiber tagging you for this process discussion

**Comment by Hanal-code** [comment]
> @ltseng IMO this should be fixed before UT, as it's part of the core concept of the site list and map working together. We're trying to vet if this concept is valid. @Hanal-code would you agree?
Yes

**Comment by ltseng** [comment]
https://github.com/techmatters/terraso-mobile-client/assets/2730009/c12845c0-f786-432d-ab96-bfedafa1d412

Sending this one back -the bottom sheet isn't closing automatically. That's the one missing piece.

**Comment by ltseng** [comment]
@david-code will you be able to merge this in for Garo today?

**Comment by david-code** [comment]
> @david-code will you be able to merge this in for Garo today?

Yes, should be able to.

**Comment by ltseng** [comment]
Looks perfect on all devices!
