### ISSUE TITLE
Styling for Create Projects screen

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#308]
- [ ] Save button is not in the correct location and the elevation is too high (Android and ipad). 
- [ ] Error message should read "Project name must be at least 3 characters", both when there is no name entered and when the name is less than 3.

**Comment by ltseng** [comment]
@CourtneyLee333 at your convenience, can you attach a screenshot or two illustrating what you mean? Unless a screenrecording would be better.

**Comment by CourtneyLee333** [comment]
![Screenshot_20230822-164929](https://github.com/techmatters/terraso-mobile-client/assets/8915145/b466bfc3-58b4-4238-8330-2367b512b2ba)
Save button should be FAB anchored to bottom right of screen

**Comment by CourtneyLee333** [comment]
![Screenshot_20230822-164957](https://github.com/techmatters/terraso-mobile-client/assets/8915145/057f445d-d50b-4646-b353-2cdd229a49aa)
When user taps save before entering a project name, the error message should be consistent with entering too short of a name. "Project name must be at least 3 characters"

**Comment by CourtneyLee333** [comment]
![Screenshot_20230822-165015](https://github.com/techmatters/terraso-mobile-client/assets/8915145/22c58b3b-dd56-4dbd-9df8-49841fd47949)
![Screenshot_20230822-165049](https://github.com/techmatters/terraso-mobile-client/assets/8915145/05c919bc-1383-429f-8b95-f50553c4166a)
Text input field labels should remain visible. Shown in the second image is a common, expected way of handling that.

**Comment by shrouxm** [comment]
it seems that keeping the input's name visible does not come out of the box in our component library, so it will be a much higher lift to implement. thankfully when we do implement it it should automatically apply to all of our inputs at once (unless we only want this feature for some of our inputs?? @CourtneyLee333). i will file a separate issue to track that feature

**Comment by CourtneyLee333** [comment]
@shrouxm If that's a much higher lift I'm open to an alternative, such as a "header" type thing on top of the field. This will come into play a lot in the data inputs, so it's important to figure out holistically.

**Comment by ltseng** [comment]
@CourtneyLee333 can you help me QA this? I don't have your same eye for detail, or familiarity with the designs.

**Comment by CourtneyLee333** [comment]
@ltseng Looks good!

**Comment by ltseng** [comment]
Awesome, closing this one!
