### ISSUE TITLE
Button to create projects or view project dashboards from projects list view requires several clicks to activate

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#309]
## Description

There is either a lag, or the Create Project button sometimes does not work. I have to tap it several times to open the Create Project form (ipad). The same is true for the close "x" at top of the screen.

Intermittently replicable for me on iPhone (Lillian)

Same issue occurs with the "Go to project" link on the project cards on iPhone and iPad

**Comment by ltseng** [comment]
@CourtneyLee333  a screen recording of this one would probably be helpful to the engineers. I'll try to get one, but if you get to it first, I'd appreciate you!

**Comment by CourtneyLee333** [comment]
@ltseng I can't reproduce this in the newest version of the app, so maybe it is resolved.

**Comment by ltseng** [comment]
Bumping this down to a medium priority one until we see it again.

**Comment by ltseng** [comment]
https://github.com/techmatters/terraso-mobile-client/assets/2730009/1d1be04f-6d10-4033-84bd-24177d078696

I got it to happen a couple times out of about 30 tries. I think it might have to do with the size of the touch target?

**Comment by CourtneyLee333** [comment]
Hopefully the styling updates can get made to the Project card and the Go to Project link will no longer be relevant.

**Comment by ltseng** [comment]
Not seeing this problem anymore since we removed the Go to Project link!

I think we lost the project name in the sites list though? The bottom two sites belong to projects.

![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/b3cacf5f-da2c-4c30-af05-8f03aa7ad02b)

**Comment by ltseng** [comment]
But I recognize that would belong in a different issue, so I'm gonna close this one.
