### ISSUE TITLE
Styling changes for Create Site form

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#310]
Using this issue to call out differences between what is observed in the app vs. what is present in the Figma designs

- [ ] Form does not show GPS accuracy (Android and ipad). Note the placement of the accuracy field has been updated since the last Figma release. 
- [x] Save button elevation seems too high. Refer to design. 
- [ ] No error message displays when "Enter coordinates" is selected and invalid lat/long coordinates are entered, and the user clicks save (Android and ipad). It should read "Invalid coordinates", but I'm not sure if more detail is needed. Note the design update in the Figma working file that displays helper text for the consolidated lat/long field. 
- [ ] Save button displays on top of bottom sheet project selection (ipad).
- [ ] Error message should be "Site name must be at least 3 characters", both when there is no name entered and when the name is less than 3. Currently, different error messages display for each case, but we should use the same error message.
- [ ] (When adding a site directly to a project from the project dashboard screen) I don't receive the error message for the Site name field when taking this path unless I've entered valid coords (Android and iOS).
- [ ] Let’s get rid of the pencil icons on lat and long fields. 
- [ ] Add counter that shows current character length of site title, and max length of site title

**Comment by ltseng** [comment]
@CourtneyLee333 can you provide screenshots for some of these?

**Comment by CourtneyLee333** [comment]
![Screenshot 2023-08-22 at 5 12 38 PM](https://github.com/techmatters/terraso-mobile-client/assets/8915145/296a791a-e247-4d20-877f-e71dbf9cefe3)
Location accuracy and lat/long. Note that this screenshot is my working file and not included in the current engineer version. Location accuracy was a Jeancarlo task, and hasn't been implemented in the app yet, so might as well put it in the new location.

**Comment by CourtneyLee333** [comment]
![Screenshot_20230822-171621(1)](https://github.com/techmatters/terraso-mobile-client/assets/8915145/808aaa58-6504-409a-a550-43a7a7bd8d28)
Elevation, or drop shadow, on the Save button is not correct. You can find the styles in the LandPKS MUI doc. Engineers, let me know if you need direction on that.

**Comment by CourtneyLee333** [comment]
@ltseng This one can be removed as it will be addressed by another fix:
 Latitude and Longitude input labels should have a different style than the headers "Site Location", "Add to Project" and "Data Privacy". They should be not bold and smaller font size.

**Comment by CourtneyLee333** [comment]
Save button should be underneath bottom sheet:
![PXL_20230822_213848660](https://github.com/techmatters/terraso-mobile-client/assets/8915145/c5407d0c-e517-421b-84c4-920ae2466c72)

**Comment by CourtneyLee333** [comment]
@ltseng 
>Error message should be "Site name must be at least 3 characters", both when there is no name entered and when the name is less than 3. Lillian saw both error messages on Android, but Courtney did not see them...on iPhone? iPad?

I did see both error messages, but there should only be one error messages for both errors: "Site name must be at least 3 characters"

**Comment by ltseng** [comment]
@shrouxm I see you merged a PR with changes, but the body of the issue was not updated. Which changes did you implement?

**Comment by shrouxm** [comment]
i think it's just the FAB bit which is ticked off!

**Comment by ltseng** [comment]
Oh phew, thanks! I was worried that you had fixed a lot more. I hope it's all right if I add some more items to the list.
