### ISSUE TITLE
Styling changes for sites list view

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#311]
- [ ] Sites list doesn't show project name for sites that belong in projects (see comment for screenshot)
- [ ] ~The site card in the site list has incorrect date for Last Modified.~ 
- [x] Can't tell if fonts have the correct size and weight styles. But also, the typography doesn't seem responsive yet to device settings, so I don't know if this is relevant yet. 
- [ ] ~The thumbnail image on the site card should be an image, not a zooming panning map.~

**Comment by ltseng** [comment]
@CourtneyLee333 I created this issue to encompass [this feedback](https://docs.google.com/spreadsheets/d/1cS7BuuzbX0BC4m68rqpj5vMgtC0J8KHlIMgcntQTpjs/edit#gid=0&range=F9), since it was about the sites list view rather than the site creation form. We might need a screenshot here though.

**Comment by CourtneyLee333** [comment]
Hmm. Let's hear from engineers if they understand what I mean. If not, we can discuss. The only screen shot would be exactly what's on the site list cards, so I don't think that's helpful.

**Comment by shrouxm** [comment]
- the site card is using dummy data for last modified, but we can update it to real data sooner if desired
- fonts maybe we should have a call to discuss? i've been copying over the typography data from the figma file, but there's probably still text that is not using it. i have no idea how to respond to device settings (does the design specify how to be responsive?)
- the map issue is already captured in another bug

**Comment by CourtneyLee333** [comment]
>the site card is using dummy data for last modified, but we can update it to real data sooner if desired
It doesn't matter for the usability study, but we've captured it here as we were noting all the things. 
>fonts maybe we should have a call to discuss? i've been copying over the typography data from the figma file, but there's probably still text that is not using it. i have no idea how to respond to device settings (does the design specify how to be responsive?)
I think I was wrong, and it is responsive. What I meant by that was responding to the user's device settings for font and display size, and I think it is working as expected. Let's leave as-is and see how users react. 
>the map issue is already captured in another bug
Cool, we can mark it off here as well when it's fixed.

**Comment by ltseng** [comment]
Looks like there's nothing major to fix here. I'd rather not have multiple bug reports tracking the same issue, so I'll make a note in #317 to test in the sites list as well.

**Comment by ltseng** [comment]
The sites list should show project association, right @CourtneyLee333?
![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/3eb78eca-dd0f-4132-95be-f21363bfe94a)

**Comment by CourtneyLee333** [comment]
Right!

**Comment by shrouxm** [comment]
@ltseng could you file new bug reports for new bugs rather than re-opening and editing old bug reports?

**Comment by ltseng** [comment]
Whoops, can do! Sorry about that. I'll put this feedback in a new issue.
