### ISSUE TITLE
Take user to site dashboard after creating a site

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#312]
## Expected behavior

After a user creates a site, take them to the site dashboard.

## Actual behavior

After a user creates a site, they are taken to the sites list

**Comment by david-code** [comment]
@ltseng @CourtneyLee333 

Garo asked the following question in their PR review:

>  do you know what the exact expected behavior is for navigation? e.g. if you create a site from a project's sites view, you'll now be taken to the site's dashboard. but if you exist the dashboard, should you go back to the project's sites view or back to the home screen?

What are your thoughts? I assumed the user should just go back the home screen after they exit the site dashboard, but like Garo says, it might make more sense to return to the site project list.

**Comment by CourtneyLee333** [comment]
Yes, Garo is correct. 

- Go to project
- Create new site for that project
- Get taken to site dashboard
- Close site dashboard to return to project sites list

If the user creates a site from the home screen, they would be taken back to home screen when closing the site dashboard.

**Comment by david-code** [comment]
@ltseng this has been merged, will be ready for QA Monday

**Comment by ltseng** [comment]
Was this merged? When I tried it just now, the app took me back to the home screen with the bottom sheet collapsed.

**Comment by ltseng** [comment]
Passes tests on Android, waiting for a new iOS release

**Comment by ltseng** [comment]
This test passes, but I found another one while testing this 😅
