### ISSUE TITLE
QA: Create Site in Project

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#321]
# Description

This is for creating a site from the "Sites" tab of the Project view.

# Steps

- Navigate to the Sites tab of a given project
- Click on the "Add Sites" button
- Select the "Create Sites" option in the drop down menu
  - Limitation: "Transfer Sites" does not work ATM
- The Create Site screen will appear. All of the steps in #272 should apply, except:
- The "Use map pin" site location should be disabled.

[Test cases document](https://docs.google.com/spreadsheets/d/1cS7BuuzbX0BC4m68rqpj5vMgtC0J8KHlIMgcntQTpjs/edit#gid=185266655&range=A1)

```[tasklist]
### Bugs to fix for Usability Study
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/323
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/325
```

```[tasklist]
### Bugs to fix later
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/329
```

**Comment by ltseng** [comment]
@CourtneyLee333 I've finished writing test cases for this one

**Comment by ltseng** [comment]
@david-code should the Go to Site links on the sites cards in the project sites view work?

**Comment by david-code** [comment]
> @david-code should the Go to Site links on the sites cards in the project sites view work?

I think this one has slipped through the cracks and was never implemented.

**Comment by ltseng** [comment]
Logging a bug

**Comment by CourtneyLee333** [comment]
@david-code The site card has been significantly updated since the very early iteration that is currently implemented. It's identical to the site card in the Sites list view, with the addition of the quick menu. See the mockup here https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=224%3A20695&mode=design&t=tpjsZFeRbHtexLSY-1

**Comment by ltseng** [comment]
Closing this QA issue and transferring the one remaining styling issue to the larger user story for adding a site to a project.
