### ISSUE TITLE
Can't click save when creating site from project dashboard

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#325]
## Description
When creating a site from the project sites list view, the Save button could not be clicked. The first time I tried to do this, I think the Create Site form actually silently crashed, but I wasn't able to get a screen recording of it.

## Steps To Reproduce

1. Open up a project and switch to Sites tab
2. Click on Add Sites and select Create Site
3. Give the site an appropriate name
5. Click Save

## Expected behavior
Site is created and user is taken back to sites list in project dashboard (though this may be changed to the site dashboard instead)

## Actual behavior
Save button does nothing.

## Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/7eb686b9-ffcf-4081-ac7f-ea1a1d87ab96

**Comment by shrouxm** [comment]
@ltseng does it work for you on android?

**Comment by ltseng** [comment]
It did work for me on Android!

**Comment by shrouxm** [comment]
@paulschreiber paaaauuuuuuul ios bug

**Comment by paulschreiber** [comment]
@ltseng Works for me in build 23. Please confirm.

**Comment by ltseng** [comment]
Not observing this bug anymore in 23! 🤷‍♀️
