### ISSUE TITLE
Popover interaction changes

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#333]
## Description

- [ ] When a popover is open, tapping outside of it should close the popover.
- [ ] Need more space between site popover title (link) and close button touch targets. It's too easy to open the location dashboard rather than close the popover. (Apologies, my design component doesn't illustrate this well.)

## Steps To Reproduce

https://github.com/techmatters/terraso-mobile-client/assets/2730009/814f79c0-8ccd-455e-9112-2cd42a86663f

## Expected behavior

- When a popover is open, tapping outside of it should close the popover.
- Need more space between site popover title (link) and close button touch targets. so that it's not as easy to accidentally open the site dashboard when trying to close the site popover.

**Comment by ltseng** [comment]
@CourtneyLee333 @Hanal-code should I flag this one for the usability study or not?

**Comment by CourtneyLee333** [comment]
IMO no. This is lower priority.

**Comment by Hanal-code** [comment]
Agreed, it's not critical for UT.

**Comment by ltseng** [comment]
Still an issue in version 40, but still not critical

**Comment by ltseng** [comment]
Should be available in version 48

**Comment by ltseng** [comment]
@ajabeckett I'm seeing that when I tap out of the popover to close it, it ends up opening another popover instead. The recording can be seen in [this comment](https://github.com/techmatters/terraso-mobile-client/issues/120#issuecomment-1771700330), though I didn't realize it may not be what I intended at the time. Is this what you intended?

I know we had a conversation about how if you were to scroll off screen and tap another location, we would want to center that popover. I think it is still important to support the case where if your viewport doesn't move, and you tap outside of the popover, that should just close the current popover instead of opening a new one as well.

@CourtneyLee333 do you have any preferences?

**Comment by ltseng** [comment]
Looking good on iOS and Android!
