### ISSUE TITLE
Remove LOCATION_DASHBOARD placeholder text from site settings

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#339]
## Description
Remove LOCATION_DASHBOARD placeholder text from site settings
## Steps To Reproduce
1. Go to sites list
2. Open up site
3. Tap settings gear in top right corner

## Expected behavior
Only see the back arrow and the site name in the top app bar

## Actual behavior
LOCATION_DASHBOARD placeholder text shows when it shouldn't

## Additional context
![image](https://github.com/techmatters/terraso-mobile-client/assets/86784/3b74f34d-bb89-4368-98dd-e42c7a27ece8)

**Comment by david-code** [comment]
@ltseng Does this only occur on iOS? Not showing up on my most Android build.

**Comment by ltseng** [comment]
Sorry, yes, it appears to be an iOS-only thing

**Comment by ltseng** [comment]
@paulschreiber please keep these bug reports open, but move to QA when a pull request has been merged. Then, when it's available to test, please assign back to me.

**Comment by ltseng** [comment]
Passes tests on iPhone, iPad, and Android
