### ISSUE TITLE
Implement Create Projects screen

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#34]
Depends on #35

**Comment by shrouxm** [comment]
Depends on #35

**Comment by ltseng** [comment]
This task has been in progress for two weeks, are we close to having it done?

**Comment by ltseng** [comment]
Hoping to finish this by the end of this week.

**Comment by ltseng** [comment]
@JeancarloBarrios can you link the PR here and tell me what the status of the review is?

**Comment by ltseng** [comment]
@david-code will you see if this one is actually done?

**Comment by JeancarloBarrios** [comment]
yes it was merged

**Comment by JeancarloBarrios** [comment]
fixed by pr #115
