### ISSUE TITLE
QA - Location Search

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#343]
# Description

This issue outlines the test cases for the location search on the home screen.

# Test Cases

- Confirm the search bar appears on the Home Screen, over top the map
- Entering text more than 2 characters, a list of search suggestions should be displayed. Each of these suggestions should display the suggestion name and address.
- Touching outside of the suggestions should close the list of suggestions
   - Limitation: Currently interacting with the bottom bar does not close the list of suggestions
   - Limitation: Currently there is a space to the right of the list of suggestions where touching the map does not close the list of suggestions. 
- Moving to another screen by the bottom tabs should close the list of suggestions
   - Limitation: Currently moving to another screen through the site list in the bottom bar does not close the list of suggestions
- List of suggestions should be reloaded when the user presses the search input
- Pressing a suggestion should close the suggestion list. A temporary site marker should be added to the map at that location, and the user should zoom to that location on the map.
- Pressing on the temporary site should open the same callout as a temporary site

[Testing document](https://docs.google.com/spreadsheets/d/1cS7BuuzbX0BC4m68rqpj5vMgtC0J8KHlIMgcntQTpjs/edit#gid=2048887970&range=A1)

```[tasklist]
### Bugs to fix for usability test
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/363
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/316
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/364
```

```[tasklist]
### Bugs to fix later
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/365
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/367
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/371
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/370
- [ ] Viewport should zoom in more closely to location when selecting search location
- [ ] Viewport should zoom in on selected search suggestion more quickly, especially when location is far
```

**Comment by ltseng** [comment]
Sorry, didn't see this one until just now. Is it ready for me?

**Comment by david-code** [comment]
> Sorry, didn't see this one until just now. Is it ready for me?

@ltseng It's OK, I didn't assign it to you yet because I actually wanted to get one last change merged before we start testing.

**Comment by ltseng** [comment]
Ok, please assign this back to me and Courtney when it's ready for testing!

**Comment by ltseng** [comment]
I know you aren't ready for this one to be tested yet, just wanted to toss a couple things your way to see if they're on your radar for fixing. These have been observed on iOS

- Typing two or even three characters isn't enough to get the list of suggestions to display. I have to tap out of the text field and then back in to get the list of suggestions to display.
- When I clear out the search text field, the same list of suggestions still displays as when the search text field was previously filled out. Same happens when I tap out of the text field, and then back in. I have to close the app to get the previous list of suggestions to stop displaying.

**Comment by ltseng** [comment]
@david-code I've logged bugs for the above

**Comment by CourtneyLee333** [comment]
@ltseng In addition to notes I put in Slack for you:
- entering coords into the search bar doesn't work
- search suggestions don't prioritize what's near me
- when I tap a search result I should get zoomed much closer in to the location
- the zooming and panning when tapping a search result is too slow. Especially if you're going to a far location.
