### ISSUE TITLE
Update Home icon in bottom tabs

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#353]
Update from map icon to pin icon. This is what we want:

![Screenshot 2023-08-28 at 2 24 52 PM](https://github.com/techmatters/terraso-mobile-client/assets/2730009/36b8385d-50a6-4836-a368-26efdce88a84)

**Comment by ltseng** [comment]
When will this be available to test on iOS? Not seeing it in version 32 on iOS but I do see it in version 35 on Android

**Comment by paulschreiber** [comment]
iOS v35 is available now.

**Comment by ltseng** [comment]
Verified on all platforms. Thanks!
