### ISSUE TITLE
Implement signout feature on mobile client

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#358]

**Comment by ltseng** [comment]
@paulschreiber assigned this to you and updated the status based on the Slack discussion. Please let me know when this will be ready to test!

**Comment by ltseng** [comment]
@paulschreiber - @CourtneyLee333 had designed the sign out feature to go in a different spot than what you implemented.  The link is in the user story, but I'm pasting it here for reference:

https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=712%3A25892&mode=design&t=3ISjqX4ZWgkFfFIE-1

**Comment by paulschreiber** [comment]
@ltseng Once the settings screen exists, the button will go in its proper place. I didn't want to delay release of this feature for weeks/months.

**Comment by ltseng** [comment]
As long as we don't forget to come back and do it :)

**Comment by paulschreiber** [comment]
Closing as fixed in build 57.
