### ISSUE TITLE
Search bar is tiny on iOS

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#359]
## Description
The search bar should be wider on iOS, but it's almost the same width as the map and GPS icons on the home screen

## Steps To Reproduce
1. Open up the app on iOS (iPhone and iPad)

## Expected behavior
The search bar should match the designs, i.e. be wider.

## Actual behavior
The search bar is very short.

## Additional context
https://github.com/techmatters/terraso-mobile-client/assets/2730009/90521768-e54c-4f60-ab0f-057e0d15c438

**Comment by david-code** [comment]
@paulschreiber could you take a look at this? It should be as simple as fiddling with the styling in `MapSearch`. I would maybe start off by trying to set `flex={1}` on the `Input` provided as an argument to `renderTextInput`.
