### ISSUE TITLE
bug: Running release action manually does not bump app version, fails

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#361]
# Description
Running release action manually does not bump app version, and fails. See [ios example](https://github.com/techmatters/terraso-mobile-client/actions/runs/6015950354/job/16318896072), [android example](https://github.com/techmatters/terraso-mobile-client/actions/runs/6014060378). This did not seem to affect the scheduled releases last night.

**Comment by david-code** [comment]
@paulschreiber could you check this out too?

**Comment by paulschreiber** [comment]
It worked last night because I manually bumped the versions before midnight.

**Comment by shrouxm** [comment]
there is no way to automatically bump the app version in code so there's no way to resolve this specifically. if we switch to expo prebuild we'll be able to create releases from git tags which will obviate the need to resolve this
