### ISSUE TITLE
Typing three letters into home screen search box doesn't automatically load results

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#363]
## Description
I should be able to type three characters into the home screen search box and see search results, as per the testing instructions in #343. However, none are loading by default, and I have to tap out of the text field and then back in to get the list of suggestions to display.

## Steps To Reproduce
1. Type three characters into search box

## Expected behavior
Search results load

## Actual behavior
No search results load unless I tap out and back in again.

## Additional context
<img src = "https://github.com/techmatters/terraso-mobile-client/assets/2730009/196a7ec0-043e-4125-bced-f66e6c442135" width="300px">

**Comment by david-code** [comment]
@ltseng This somehow escaped my notice. It should have been fixed by the PR I linked and is working on my Android. Could you run the QA when you have a minute and let me know if there's more work to be done here?
