### ISSUE TITLE
Temporary site marker is transparent

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#365]
## Description
The temporary site marker that is added to the map when a search result is selected from the list of search suggestions appears to be transparent. It should instead be fully opaque, with the color #1A202C

![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/0de35d42-a4c4-457c-9c58-cf992a995c65)

**Comment by shrouxm** [comment]
@CourtneyLee333 in the design the color for "action/active" (which is used for the temp site marker) has a 70% opacity, can i assume based on the existence of this bug report that that's a mistake in the design file?


![Image](https://github.com/techmatters/terraso-mobile-client/assets/3411715/2c2d9b09-41b1-4735-84bf-194e3a6925fb)

**Comment by ltseng** [comment]
I see it fixed on Android, but not yet on iOS

![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/bc78de76-1de0-4022-aeff-a3f4032368d7)

**Comment by shrouxm** [comment]
i see this also on my latest iOS build. no idea why this would differ by platform, but i will re-assign to paul to look into why it's still not working on iOS specifically

**Comment by shrouxm** [comment]
i see it's marked as low priority, i was only touching it because i happened to be working on the icons anyway for other higher priority issues, so no rush @paulschreiber

**Comment by paulschreiber** [comment]
@ltseng Please check again against build 40 or later. Seems okay now.

**Comment by ltseng** [comment]
Does seem fixed now!
