### ISSUE TITLE
Misaligned icon in sites list placeholder text

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#366]
The location icon is too high in the sites list placeholder text. I observed this on iOS, but it's probably happening on all platforms.

![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/122b7bfd-43a0-49d2-84ab-e24ca8ded34f)

**Comment by ltseng** [comment]
@CourtneyLee333 just had a chance to fully see this on iOS and wanted to give you a heads up in case you see anything else that doesn't match your designs.

**Comment by CourtneyLee333** [comment]
I can't reset my sites list to empty, so I can't test this. But I don't see the location icon on top of the sites list.

**Comment by CourtneyLee333** [comment]
And yes, I see the location icon on top of it in my design... Will fix that.

**Comment by david-code** [comment]
Oh interesting, I completely misunderstood that. Thanks Courtney. I guess we should make a different issue to fix that.

**Comment by CourtneyLee333** [comment]
I'll make sure to leave a note for you on these information sheets going forward, so you know how they should behave.

**Comment by ltseng** [comment]
I'll make a separate issue to fix the placeholder text for the bottom sheet.

@shrouxm this may end up affecting your fix for #289

**Comment by ltseng** [comment]
For now, can we leave the placeholder text as is and just fix the icon placement? Unless the full fix would be super easy.

**Comment by ltseng** [comment]
After talking to @CourtneyLee333, I'm going to close this issue in favor of the higher priority #378
