### ISSUE TITLE
Unable to select correct site when two pins are moderately close together.

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#367]
## Description
When two pins are moderately close together, I'm having trouble selecting the right pin. This was observed on iOS - pins on Android are currently too small, so I'm avoiding this selection issue there.

## Additional context
https://github.com/techmatters/terraso-mobile-client/assets/2730009/3a621b8e-c055-40d9-9526-663e3d75ce32

**Comment by ltseng** [comment]
@shrouxm I filed this separate issue, as requested.

**Comment by shrouxm** [comment]
@ltseng there is a chance #387 may have incidentally solved this, are you able to reproduce on the newest app versions? i'm currently unable to find a pin distance where taps that were clearly closer to one pin than the other still opened the farther pin

**Comment by ltseng** [comment]
Not seeing it any more on Android or iOS!

**Comment by ltseng** [comment]
@david-code I seem to be unable to save any sites in version 37 on iPad now

https://github.com/techmatters/terraso-mobile-client/assets/2730009/7e4a1616-a639-4854-882e-dc203644a9ab
