### ISSUE TITLE
Screen for adding user to a project

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#37]

**Comment by shrouxm** [comment]
@david-code this is marked in review but i don't see any associated PRs for it?

**Comment by ltseng** [comment]
Echoing what @shrouxm said - who is reviewing this, if there is a PR ready?

**Comment by ltseng** [comment]
Can this one be closed?

**Comment by ltseng** [comment]
Closing this one since I'm doing my QA in the larger user story.
