### ISSUE TITLE
List of search suggestions should prioritize what is near me

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#371]
Search results are not localized to my location.

For the keyword "star" near me:

Google returns this
![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/2f9af1c3-1a94-483a-9d28-d55f2e097777)

And our app is returning this:

<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/32339144-3708-448e-8471-ef1afec9adba" width="300px">

With the obvious main problem being that Stauning airport out in Denmark is returned as the top result 😆

**Comment by knipec** [comment]
FYI @DerekCaelin I'm unable to repro this on my 2 physical devices and on my Android emulator (my iOS emulator is currently having technical difficulties). Closing this as "no repro"
