### ISSUE TITLE
Refactor Mapbox search request handling

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#388]
# Description

#386 introduces some changes to deal with canceling mapbox search requests if they are overridden by later requests. Unfortunately the logic is a bit convoluted. Could use some testing and refactoring to make it easier to understand, and catch any possible bugs.

**Comment by paulschreiber** [comment]
This was addressed with https://github.com/techmatters/terraso-mobile-client/pull/1848
