### ISSUE TITLE
feat: continue displaying input labels when there is text in the field

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#390]
## Description
Currently, when a user starts typing in a text input field (or there is pre-existing text), the label for the input field gets hidden. We should make it so that the label stays visible even when there is text. We haven't picked a specific design for this yet, but here is an example of how another app handles this:

![image](https://github.com/techmatters/terraso-mobile-client/assets/3411715/ce0bd7ce-ab93-4b67-a235-4e2e73ce9702)

originally reported in #308

**Comment by shrouxm** [comment]
@CourtneyLee333 in the original thread, you gave the above picture as an example and said it was a suggested way of handling this. is it the preferred way? and are there any other ways to implement that would still be an improvement but might be less engineering effort?

**Comment by CourtneyLee333** [comment]
I posted my thought on the other instead of here... so I'll post here too. 

I'm open to alternatives, such as the "header" type thing you currently use. It'll come into play heavily in the data inputs, so we need to figure it out holistically. 

Should we schedule a quick chat about it?

**Comment by ltseng** [comment]
Is this still a valid task to keep open?

**Comment by CourtneyLee333** [comment]
If there is another task that addresses the agreed upon styling, then I don't think this one is necessary.

**Comment by ltseng** [comment]
I don't know if there is one, or if this is covered by your "General Notes to Engineers" section of the Figma. @shrouxm @david-code can you weigh in here?

**Comment by shrouxm** [comment]
i think this is covered by #688
