### ISSUE TITLE
Diagnose problems with expired token

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#391]
# Definition

In #352, there was an error that was caused with the backend access token expiring. Two problems:

1) The access token should be refreshed automatically with a refresh token
2) User should not be able to access the app if their access token is not valid (i.e. expired)

This issue should diagnose why this is possible and fix it. Might need to create a separate issue in the terraso-shared-client repo in order to fix any issues there as well.

**Comment by DerekCaelin** [comment]
Making this into a P1 because once it occurs it inhibits Android users from using the app.

**Comment by paulschreiber** [comment]
We haven't seen this in a while. Moving out of Capri milsetone.

**Comment by DerekCaelin** [comment]
@paulschreiber when, if ever, should we close this issue? We no longer can reproduce...

**Comment by DerekCaelin** [comment]
Closing for now. We can reopen if we need to
