### ISSUE TITLE
Show error when invalid lat/lng is entered (site creation)

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-mobile-client#392]
## Description
When creating a site, if you enter an invalid lat/lng and click save:
* no error is shown
* the site is not saved

## Steps to reproduce
1. Open a project
2. Select the Sites tab
3. Tap Add Site > Create Sites
4. Enter a name ('hello world")
5. Enter latitude (100)
6. Enter longitude (100)
7. Tap Save

**Comment by ltseng** [comment]
@CourtneyLee333 do you think it would be useful to include valid latitude and longitude ranges in the error message? They should range from -90 to 90 for latitude and -180 to 180 for longitude.

**Comment by CourtneyLee333** [comment]
@ltseng Yes. And how many decimal places are we accepting? We should limit the field to that number. 

"Invalid coordinates. Enter -90 to 90 for latitude, -180 to 180 for longitude, separated by comma."

**Comment by paulschreiber** [comment]
We wouldn't show a combined error message. We'd show an error message indicating whether or not the specific field is valid. 

Latitude: Enter a value between -90 and 90.
Longitude:  Enter a value between -180 and 180.

Something similar to this:
<img width="241" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/86784/1a5979aa-5b8c-4905-8324-58e213cce5e1">

(visual treatment may vary.)

**Comment by CourtneyLee333** [comment]
The lat and long fields are going to be combined into one field, with values separated by a comma. This was a suggestion by Jeff, which will allow folks to copy directly from Google Map and GIS tools without needing to separate the values for two separate fields.

**Comment by ltseng** [comment]
@CourtneyLee333 to answer your question above, I believe we currently accept up to 15 decimal places, which seems a little long. Google Maps displays 6.

Tagging @david-code for awareness of this discussion

**Comment by paulschreiber** [comment]
@CourtneyLee333 We can parse on paste and split them out for the user. Trying to edit x.yyyyy,z.aaaaa on a mobile phone (and preserve the comma) is clunky.

An example of this is if you copy
`Jane Doe <jdoe@aol.com>`

and paste it in to my [concert RSVP form](https://concerts.shrub.ca/list):
<img width="420" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/86784/d9333f92-39ee-41d6-a4be-ae7d36d721bd">

the computer parses the name and email and puts them in the right spot.

**Comment by CourtneyLee333** [comment]
@paulschreiber Can you build this as you envision and then show me? I don't quite follow.

**Comment by david-code** [comment]
> @CourtneyLee333 to answer your question above, I believe we currently accept up to 15 decimal places, which seems a little long. Google Maps displays 6.
> 
> Tagging @david-code for awareness of this discussion

Agreed that we should limit the decimal places. If we decide on a desired accuracy range (within 1m?) it's pretty easy to roughly calculate how many decimal places we need.

**Comment by ltseng** [comment]
According to [Garmin](https://support.garmin.com/en-US/?faq=hRMBoCTy5a7HqVkxukhHd8), 5 decimal places is sufficient to get within 1.11 m accuracy, so let's go with that.
