### ISSUE TITLE
Create filter options for visible sites on map view

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#42]
Depends on #48

**Comment by ltseng** [comment]
Waiting for one of David's PRs to go through

**Comment by ltseng** [comment]
@shrouxm are we still waiting for one of David's PRs to go through? @paulschreiber is wondering which one.

**Comment by ltseng** [comment]
@CourtneyLee333 will check to see if the filters applied to the sites list view is meant to affect the set of visible sites on the map view as well.

**Comment by CourtneyLee333** [comment]
Yes! We talked through this and decided the map view of the site pins should always represent the list view.
