### ISSUE TITLE
feat: update home screen map viewport to match searched/filtered sites

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#422]
When the user applies search or filter options to the site list on the home screen map, we should update the map's viewport to encompass the new set of visible sites.

**Comment by ltseng** [comment]
We need to think this through. Tagging @CourtneyLee333 to help me think through this.

**Comment by CourtneyLee333** [comment]
Yes! We talked through this and decided the map view of the site pins should always represent the list view.
