### ISSUE TITLE
feat: use chip design for home screen site clusters

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#425]
See design for details.

**Comment by ltseng** [comment]
@shrouxm since this is a low-priority item, would it make sense to track this in https://github.com/techmatters/terraso-product/issues/346 instead? Otherwise, this would be the one remaining task blocking completion of https://github.com/techmatters/terraso-product/issues/43

**Comment by shrouxm** [comment]
that makes sense to me!

**Comment by CourtneyLee333** [comment]
@DerekCaelin @shrouxm I think we can close this one. It's not a big deal to me at all to use the chip. I didn't realize Mapbox's limitation at the time of design, and I'm totally fine with Mapbox's clustering.

**Comment by DerekCaelin** [comment]
Closing as Courtney suggests!
