### ISSUE TITLE
bug: site pins directly under user's location marker are not tappable

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#426]
I guess because the user location marker eats the tap event. I think the fix is to add a tap listener to the user location marker and redirect that event to any pins under the tap event. Hopefully `Mapbox.MapView`s `queryRenderedFeaturesAtPoint` method will make this straightforward.

**Comment by ltseng** [comment]
I'm seeing a small flicker most of the times I select a site under my location on iOS. Do you see this too @ajabeckett?

https://github.com/techmatters/terraso-mobile-client/assets/2730009/deb905af-8da6-4ebb-986d-8d04b30b9ccf

If this isn't an easy fix, I'll log it for later so we can move on.

**Comment by ltseng** [comment]
This is only happening on iOS for me. Android appears to be fine.

**Comment by ajabeckett** [comment]
I've seen this in the iOS simulator as well, since I started working on the project. I'm assuming it has something to do with Mapbox and the transparent overlays, but I haven't looked in to it, and I don't know if it's an easy fix.
