### ISSUE TITLE
feat: make site pin cluster callout list scrollable

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#427]
Currently the list of sites that opens when a site cluster is tapped while zoomed in is not scrollable, and will grow as large as the list of sites. It is still functional because the list can be navigated by panning the map, but this is awkward. I couldn't figure out how to stop the map from eating the scroll gestures and turning them into pan gestures when I originally looked into this, and it might not be possible at all as it's a relatively niche use case.

**Comment by CourtneyLee333** [comment]
Noting that an overlay sheet will replace the current popover component.
