### ISSUE TITLE
Connect site deletion from project to backend

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#431]
When we do so, we need to include a warning dialog.

**Comment by ltseng** [comment]
@CourtneyLee333 do you have a specific warning message in mind?

**Comment by CourtneyLee333** [comment]
Yes, https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2206%3A42355&mode=design&t=cfc4uev8pRaFPXoD-1
