### ISSUE TITLE
Connect removing a site from a project to backend

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#433]
Should probably have a warning dialog

This specifically refers to the "remove from project" option when selecting the three dots/More icon on a site card within the project's Sites tab.

**Comment by ltseng** [comment]
@CourtneyLee333 do you have a warning message in mind?

**Comment by CourtneyLee333** [comment]
Yes, https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2206%3A42355&mode=design&t=cfc4uev8pRaFPXoD-1

**Comment by CourtneyLee333** [comment]
@ltseng I haven't written one. Do we need one? Will the site retain its membership when it is removed from a project? What are the consequences for different team roles of removing the site from the project?

**Comment by ltseng** [comment]
When a project manager removes a site from a project, but doesn't delete it, they basically transfer ownership of the site to themselves. As a result, all other project members will lose access to that site.

**Comment by CourtneyLee333** [comment]
Is it an official decision that sites will not have team members, just the single site owner? If so, the dialog can be:

Remove site from project?
This action will remove other team members from the site, and make the site accessible only to you. Any previously collected site data will be retained.

**Comment by ltseng** [comment]
It's not an official one yet, more one that we're hoping we can sidestep by implementing project management very well, and the pure fact of the matter being that we simply won't have time to get to it. I think this works for now.
