### ISSUE TITLE
Styling changes for the map

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#436]
- [ ] Map popover
  - [ ] Needs drop shadow
- [ ] Map marker icon
  - [ ] Needs style when selected ([figma link](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=582%3A36087&mode=design&t=hfeNdwjZ8MPjsGCy-1))
- [ ] Search bar needs "x" option to clear the search text in the input field.

**Comment by ltseng** [comment]
Partially done as of 10/17, still need drop shadow and search bar "x"

**Comment by ltseng** [comment]
The search bar x looks good and functions as expected. The drop shadow shows up on iOS for the map popover, but not on Android though?

**Comment by ltseng** [comment]
Android screenshot ![Screenshot_20231026-112051_Terraso LandPKS.jpg](https://github.com/techmatters/terraso-mobile-client/assets/2730009/c86f1e4d-d559-4f10-8a9c-d4de050ee198)

**Comment by ltseng** [comment]
iOS screenshot![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/843cb434-5c9d-452e-ab53-7e7e1ad4dab6)

**Comment by ajabeckett** [comment]
I'll take a look at this once I fix an issue with the Android emulator on my machine.

**Comment by ltseng** [comment]
Reminder that this one is still pending :)
