### ISSUE TITLE
Design patterns for the mobile app

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#438]
- [ ] Change all date formats to MM/DD/YYYY (at least for the US app)
- [ ] All buttons should use the focus state style - see [MUI library here](https://www.google.com/url?q=https://www.figma.com/file/7ZD5nE1IZKRHUIhrLkekoz/LandPKS-MUI-for-Figma-v5.11.1---Material-UI?type%3Ddesign%26node-id%3D11011%253A143217%26mode%3Ddesign%26t%3D9pmGT73safdNRCir-1&sa=D&source=docs&ust=1695136762865579&usg=AOvVaw1F4kLosnLzU8msg6O0JoeH) for button styles. Currently, the focus style is a dark blue that doesn't exist in our palette.
- [ ] Save button should always appear above keyboards when text inputs are selected

To be updated after design patterns meeting on 09/20

**Comment by ltseng** [comment]
@CourtneyLee333 can you help me update this list, if this issue is even needed anymore?

**Comment by CourtneyLee333** [comment]
The engineers said it would be best to leave notes in the design, so I added a section for the general notes that came out of our meeting here https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2647%3A10445&mode=design&t=kljlEPRBwNyesTSt-1

As far as things that have been implemented and need fixes, your list is good but there is one more from our meeting: the missing - key from the iOS keypad. That is probably addressed in another issue already.

**Comment by ltseng** [comment]
I believe that's addressed in #439, so I'll close this issue. Thanks!
