### ISSUE TITLE
Minus (negative) button not visible on numeric keypad for iOS

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#439]
### App Version

1.0 (41)

### Platforms

- [X] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

When selecting numeric entry for lat/long on Create Site form, I am not able to enter negative numbers for latitude or longitude. The only non-numeric key available is the decimal sign.

### Steps to Reproduce

1. Select Create Site from bottom sheet, location popover, or project's sites list tab
2. Select Enter coordinates from Site location options

### Expected behavior

Key for negative inputs appears. 

Android:
![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/60023129-f12c-4653-a969-31e0a65072ec)

### Actual behavior

No key for negative inputs appears

iOS:
![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/4d9d5d85-8c60-4625-a772-ef21c61ff12e)

**Comment by paulschreiber** [comment]
Default keyboard:
<img width="427" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/86784/3a93231d-b54f-428a-8651-545d5539de04">

Numbers:
<img width="391" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/86784/23543784-76b8-4311-a974-31d73c2d4ee8">

Numbers with period:
<img width="401" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/86784/8b417999-5a5f-4567-9b6e-fd6ed94052d3">

Numbers and punctuation:
<img width="416" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/86784/7742e351-e61e-43a7-b659-136182e92628">

**Comment by CourtneyLee333** [comment]
This might be mostly moot now, since we've removed the lat/long entry from the Create Site form. But there might be other situations, like in data entry, where a number is warranted that also needs a period or negative.

**Comment by ltseng** [comment]
Let's do the numbers & punctuation keyboard then, thanks!

**Comment by ltseng** [comment]
@paulschreiber is this still a valid task? Or are you tracking this work elsewhere, perhaps as part of the work to audit keyboard types?

**Comment by paulschreiber** [comment]
We moved to the numbers + punctuation keyboard for this. Closing the issue.
