### ISSUE TITLE
Set up oauth login

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#44]
# Description

A user must be authenticated in order to perform most queries against the Terraso backend. This means that as a prerequisite to querying the backend we must provide some sort of way for the user to sign in an obtain a Terraso authorization token. In order to keep things simple, this will originally just be done for Google.

# Details

Originally I thought that we could reuse the OAuth signin process we use for the Terraso backend. However, it is not quite that easy. The redirects used in OAuth are complicated by the fact that the mobile app needs to switch between the browser view to approve the app, but needs to redirect to a native view afterwards. Unfortunately this means that we can't use the Terraso OAuth callback as our callback here -- we wouldn't be able to force the user back to the app and the user would end up at the Terraso website in their browser.

Unforunately, the alternative will be more complicated. What Google suggests doing is the following:

1) Set up OAuth identification using a public authorization flow in the native app. At the end of this stage we will have opened the user's default browser, closed it, and redirected the user back to the app. We will also have the authorization token from the server. In OIDC, this is a JWT.
2) Use this authorization token to retrieve a Terraso token from the backend. The Terraso backend can verify the properties of the JWT to ensure that the authorization token was in fact created by Google, create an account, etc. We then would create a new Terraso JWT, encrypted with our private JWT key, that would be used by the frontend for authenticating with our backend.

# Useful Links

[Google Docs on authenticating with a backend server](https://developers.google.com/identity/sign-in/android/backend-auth)
[React Native Docs on Deep Linking](https://reactnative.dev/docs/security#authentication-and-deep-linking)
[Expo Link on Deep Linking](https://docs.expo.dev/guides/linking/#handling-links)

**Comment by shrouxm** [comment]
ok i will try to clarify my understanding of the two login flows:

### web client
1. client retrieves login URLs from the backend with the backend's oauth client configuration, including a redirect URI to the backend
2. client navigates to login URL and logs in
3. oauth provider redirects the browser back to Terraso at one of the {provider}/callback endpoints, passing a login token in URL params
4. the callback endpoint on the backend sends the login token back to the oauth provider along with its secret token, who confirms it is valid, & gives the user's info

### proposed mobile client flow
1. client performs an oauth sign in without communicating with the backend, retrieving a signed ID token with their login info.
2. client sends signed ID token to backend.
3. backend validates the token's signature & logs the user in using the login info provided.

### questions
1. how is step 1 going to work for each provider? the google docs seem to be using a specific google SDK for android, will need to set up such SDKs for each platform?
2. i'm still not fully understanding what is preventing us from using the same flow as the web client but with an app redirect URI instead of a browser redirect URI. as far as i understand, that flow is secure because the user gets an authorization code from the oauth provider that can only be translated into an access token using the backend's secret key. it seems desirable to maintain a similar flow for web & mobile client.
3. this seems like the sort of thing apple would be weird about on iOS, do they mandate sign-in with apple work via their SDKs somehow on iOS?
4. have you looked into this library? https://www.npmjs.com/package/react-native-app-auth

**Comment by david-code** [comment]
> how is step 1 going to work for each provider? the google docs seem to be using a specific google SDK for android, will need to set up such SDKs for each platform/provider pair?

All of the providers use OpenID Connect, so they all should have the same JWKS that can be used to verify the JWT they sign. My plan is not to use the Google SDK and instead use the library you linked below to get the token. The rest will be done on the backend.

> i'm still not fully understanding what is preventing us from using the same flow as the web client but with an app redirect URI instead of a browser redirect URI. as far as i understand, that flow is secure because the user gets an authorization code from the oauth provider that can only be translated into an access token using the backend's secret key. it seems desirable to maintain a similar flow for web & mobile client?

Here's the way I see it
- App gets user to sign-in on provider website, gets authorization grant from provider (first step of OAuth)
- Provider redirects user using app's redirect URI to continue flow, passing authorization grant as a param
   - On web, this redirects to the callback view. When this is successful, the backend will create a Terraso access token.
   - On mobile, this redirect will just be handled by the app itself. We can't run code on the backend and therefore cannot can't create a Terraso access token for the user.
 - App makes request for access token using authorization grant

> this seems like the sort of thing apple would be weird about on iOS, do they mandate sign-in with apple work via their SDKs somehow on iOS?

AFAIK we use Apple's OAuth on the backend already, they should implement OIDC. Because we are creating and managing our own tokens it should work basically the same. However it's a good point that should be examined a bit more. Might be best just to try it out and address the problems when we get to them.

**Comment by ltseng** [comment]
How close are we to finishing this?

**Comment by ltseng** [comment]
Is this task safe to close?
