### ISSUE TITLE
Implement privacy tooltip for Create Project and Project settings screen

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#440]
[Create Project (Figma)](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=731-27314&mode=design&t=tWJV8YA3hzXAMuUa-0)

[Project Settings (Figma)](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=264-22979&mode=design&t=tWJV8YA3hzXAMuUa-0)

Tooltip text:

> All sites and data in a public project can be seen by the general public. Sites and data in private projects can only be seen by you and anyone you share them with.  **Learn more**.

(Learn more should open a bottom sheet for a fuller description of what privacy means)

Bottom sheet text:

> **Public sites** and their data can be accessed by anyone on the LandPKS data portal at [insert URL, TBD]. This means anyone can view information about your site.
> 
> **Private sites** can only be seen by you or other people you have shared your site with. If your private site is part of a project, other project members will be able to see your site data.
> 
> As a site manager, you can change the privacy of your site at any time, unless it is part of a project. In that case, the project privacy setting determines the site privacy setting.
> 
> If a private site is moved into a public project, the site privacy setting will be changed to public, and vice versa.
> 
> Sites that were previously public that are made private will no longer be publicly accessible on our data portal, and vice-versa. 
> 
> Read more about our data privacy policy at https://techmatters.org/privacy-policy/.

**Comment by ltseng** [comment]
@CourtneyLee333 and @DerekCaelin since the Landscape Data Commons/WOSIS integration won't be available until next year, should we explicitly say here that Public projects will make data viewable on the LandPKS Data Portal instead? The same question applies for the site version of this tooltip (see #441)

**Comment by DerekCaelin** [comment]
@ltseng yes, that sounds right to me.

**Comment by CourtneyLee333** [comment]
But will it sync to any other db's, like BLM? Or is that for future API work? (Sorry if we've covered this; I've lost track. Also sorry for commenting about this on Slack as well. I'm trying to keep up!)

**Comment by ltseng** [comment]
It will not sync anywhere for MVP. We're targeting syncing to public databases for next year.

**Comment by ltseng** [comment]
Have created a doc to get Laura's thoughts https://docs.google.com/document/d/1iNVEW9esVo_OnXLL_sfhpxckNnqzNp1O5TLXDZ_4Suo/edit
