### ISSUE TITLE
Short tap instead of long press to bring up location popover

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#444]
Coming from the usability study - people were not familiar with the concept of long-pressing on a map to drop a pin or bring up additional information. We'd like to change the current interaction model:

Current:
Long press on map to drop a pin and open the location popover

Desired:
Short tap on map to drop a pin and open the location popover.

**Comment by ltseng** [comment]
This is working well and as expected on all my devices. I'm seeing a bit more evidence of the behavior in #120, but on the home screen map sometimes. I'll upload a recording there.

**Comment by ltseng** [comment]
@CourtneyLee333 this is available to test if you want to see it in action!

**Comment by CourtneyLee333** [comment]
Yay, works great! I'd like to test it by searching and tapping on a location where I already have site, or have some very nearby, but the app seems to have logged me out and I can't log back in.

**Comment by CourtneyLee333** [comment]
Ok, what I'm seeing now is that when I tap my GPS location icon I cannot access the popover. Also, the icon is still moving around a lot, so once I tried to tap it but it moved at that moment so I created a pin at what I thought was my location but the location icon had moved. These issues exist on my iPad and Android phone. 

https://github.com/techmatters/terraso-mobile-client/assets/8915145/0b30d82d-ccc2-4c96-a14e-5746b8afb840

**Comment by ltseng** [comment]
Okay, we haven't addressed the issue of the user's location icon moving around too often. That is logged in #464. 

@ajabeckett do you want to use this issue to fix the bug that Courtney brought up, i.e. that of the GPS icon functionality interfering with the popover?

**Comment by ajabeckett** [comment]
Yes, I'm working on a fix for the user location interfering with taps now.

**Comment by ltseng** [comment]
Fixed!
