### ISSUE TITLE
feat: tooltips that move other components out of the way instead of overlaying them

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#455]
currently, we only implement tooltips that overlay the screen. the tooltip shown in this (unimplemented) design actually sits between the the tooltip's source and the related control:
![image](https://github.com/techmatters/terraso-mobile-client/assets/3411715/8ceacc18-01b6-4c1f-98ff-6775e443b62b)

this is particularly tricky to implement with the arrow pointing at the tooltip's source, but is generally a lot more finnicky than an overlay. if we only need these tooltips in form input labels we could create a bespoke implementation of the behavior for that use-case, but let's wait and see how the overall design shapes up before trying to figure out the right way to implement this

**Comment by ltseng** [comment]
@CourtneyLee333 do you have any flexibility in the way we approach tooltips here?

**Comment by CourtneyLee333** [comment]
Garo and I already discussed this in Figma comments.

**Comment by ltseng** [comment]
Whoops, gotcha. Withdrawing my question :)

**Comment by paulschreiber** [comment]
This will be handled in the tooltip component work: https://github.com/techmatters/terraso-mobile-client/issues/1776
