### ISSUE TITLE
Consider changing the way we update user's location

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#464]
As of build 41 on Android, the user's location on the home screen map moves often, and sometimes much further than I would expect, especially when sitting down at home. 

https://github.com/techmatters/terraso-mobile-client/assets/2730009/128b167c-619d-43b0-b3c4-e3d6442c6b2f

Summarizing the [Slack thread](https://tech-matters.slack.com/archives/C02K02L3Q48/p1695665490821429) here:
- The current min distance that a user should travel to receive a location update is 1 m.
- This is probably just GPS jitter
- If we increase the minimum distance, users might not see their location update when they expect it to. Should we consider setting the minimum distance to be higher than the GPS accuracy?

**Comment by knipec** [comment]
I am still seeing this repro on my physical device. It's only noticeable if I zoom in a lot.

**Comment by DerekCaelin** [comment]
Closing until a user expresses an issue with this
