### ISSUE TITLE
Show site completion status on map

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#49]
Distinguish sites on map by completion status. Details and design are in https://github.com/techmatters/terraso-product/issues/187

**Comment by shrouxm** [comment]
bumping to august because it depends on data inputs

**Comment by paulschreiber** [comment]
This is covered by https://github.com/techmatters/terraso-mobile-client/issues/1402 and https://github.com/techmatters/terraso-mobile-client/issues/1401
