### ISSUE TITLE
 Tapping a map marker should center the marker and the popover

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-mobile-client#492]
## Summary
On the home screen,  tapping a map marker should center the marker and the popover.

Currently, the items may appear partially offscreen:
![image](https://github.com/techmatters/terraso-mobile-client/assets/86784/1530170f-900c-4f01-9444-ec35bccf2c2a)

**Comment by ltseng** [comment]
Should be available in version 48

**Comment by ltseng** [comment]
This works well!
