### ISSUE TITLE
Able to leave project where I am the sole manager

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#496]
### App Version

46

### Platforms

- [ ] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

I am able to leave a project where I am the sole member/manager. I should not be able to.

### Steps to Reproduce

1. Open project where you are the only manager, and therefore member
2. Tap the Teams tab
3. Tap the "Leave Project" button

### Expected behavior

1. Should see error message snackbar informing you that you cannot leave the project while you are the only manager.

### Actual behavior

1. You appear to be removed from the project, but the project stays in your list of projects with an empty Teams tab. If you attempt to add yourself again, the app tells you that you are already a member of this project.

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/179ebd07-040b-4895-8778-d477d1d6fb76

![Screenshot_20231013-090041_Terraso LandPKS](https://github.com/techmatters/terraso-mobile-client/assets/2730009/9a429287-0ca6-4e4b-bd5a-0c3a9c253850)

**Comment by ltseng** [comment]
Still present in build 88 on iOS (and I assume on Android too)

**Comment by DerekCaelin** [comment]
Closing this issue as resolved in 118.
