### ISSUE TITLE
No error message displays when I attempt to add a user to a project while offline

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#497]
### App Version

46

### Platforms

- [ ] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

When my device is not connected to data, and I attempt to add a user to a project, I should see an error message telling me that I need to be online to do this.

### Steps to Reproduce

1. Place device in offline mode (i.e. turn off wi-fi and mobile data)
2. Open LandPKS project and switch to Teams tab
3. Enter valid email address

### Expected behavior

See error message 

### Actual behavior

Silently fails

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/c56d44ed-02c1-4a08-8615-2b4b8808344b

**Comment by DerekCaelin** [comment]
This behavior still occurs as of 125, but I'm closing this as a "bug" because it really is an unimplemented feature. Should be resolved by https://github.com/techmatters/terraso-mobile-client/issues/788
