### ISSUE TITLE
Refactor Modal component for more flexibility

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#511]
The custom `Modal` component has a lot of nice features. However, some of the styling elements make its reuse for difficult for other uses, like the `ConfirmModal`, for example. This issue will be to refactor the `Modal` element so it is more flexible in its styling.

**Comment by paulschreiber** [comment]
@knipec @tm-ruxandra Can this be closed?

**Comment by tm-ruxandra** [comment]
@paulschreiber we do not yet have finalized designs for modals / popups, but this ticket would likely be retired when those designs are ready and we can create a component ticket.
