### ISSUE TITLE
Contributor is unable to create sites within a project

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#513]
### App Version

46

### Platforms

- [ ] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

When I attempt to create a site within a project as a Contributor, the Save button can be pressed, but does nothing else.

### Steps to Reproduce

1. Go to Project where you have the contributor role
2. Switch to Sites tab, Click Add Sites, and select Create Site
3. Title the site and click Save

### Expected behavior

Site is saved and user is taken to Site Dashboard

### Actual behavior

Save button can be pressed, but user does not move away from Create Site form

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/219a66f5-a9b5-495e-beac-1d41326f30f0

**Comment by ltseng** [comment]
Let's please make sure that when we fix this, we don't accidentally allow viewers to create sites too :)

**Comment by ltseng** [comment]
@david-code I haven't tested this yet, is the fix deployed?

**Comment by ltseng** [comment]
Cool, contributors are able to create sites within a project now, but I could also create a site as a viewer...

 https://github.com/techmatters/terraso-mobile-client/assets/2730009/348c5f35-07da-427d-8f62-280159a31b32

**Comment by david-code** [comment]
> Cool, contributors are able to create sites within a project now, but I could also create a site as a viewer...

It seems to me like you are logged into the manager account in the screen recording you posted.

**Comment by ltseng** [comment]
🤦‍♀️ You are so right. I should have been more careful when I was checking this!

I tested this again as an actual viewer this time. They're still able to click on the Add Sites button on the Sites tab, and get all the way to the Create Site form, but the backend validation does block them from actually creating the site.
