### ISSUE TITLE
App requires relaunch to sync sites

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#518]
### App Version

47

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

When I delete a project that has 3 sites, I need to relaunch the app in order to see my Sites list update

### Steps to Reproduce

1. Have a project that contains at least three sites, and two members, one of whom is a viewer/contributor
2. As the manager, delete the project

### Expected behavior

User to taken to projects list, and if user checks their sites list, all sites that belonged to the deleted project are also deleted

### Actual behavior

User is still able to see the deleted site in their sites list, and launch the site dashboard

User needs to close and re-open app to see an updated sites list

### Additional context

Manager view

https://github.com/techmatters/terraso-mobile-client/assets/2730009/f23e9bb6-ca04-4aa3-b2b4-7e7dba8efc84

Contributor view

https://github.com/techmatters/terraso-mobile-client/assets/2730009/28006b38-2b66-479e-9a2e-2650d6986674

**Comment by paulschreiber** [comment]
It's not just deleted sites — it's any change. If you are logged in on two devices and add sites with device A, device B doesn't pick them up automatically.

**Comment by ltseng** [comment]
I did notice that as well, should that be logged as a separate issue?

**Comment by paulschreiber** [comment]
Let's use this issue to track sync generally. We can write up additional issues (if needed) after we investigate.

**Comment by CourtneyLee333** [comment]
@DerekCaelin Noting that this issue is covered by the broader sync issue.

**Comment by DerekCaelin** [comment]
Yes - this, too, is not a bug, it's an unimplemented feature, better reflected by:
https://github.com/techmatters/terraso-product/issues/230
