### ISSUE TITLE
Viewer is able to see/click on "Add Sites" button within project

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#525]
### App Version

48

### Platforms

- [X] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

Viewer is able to see and click on the Add Sites button within a project. 

### Steps to Reproduce

As a viewer, open a project and click on the Sites tab

### Expected behavior

1. Add Sites button is visible and clickable to managers and contributors only.
2. Add sites button is either hidden or disabled for viewers.

### Actual behavior

Viewer is able to see and click on Add Sites button, as well as Create Sites and Transfer sites options. Thankfully, they don't seem to be able to actually create any sites.

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/e5e479d1-ea8a-4ed9-8bfb-79d532f23021

**Comment by david-code** [comment]
This should be ready for QA

**Comment by ltseng** [comment]
It could be that

**Comment by ltseng** [comment]
Never mind, it was just slow to update. I had to relaunch the app to see the change.
