### ISSUE TITLE
Styling feedback for project & site creation forms

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#534]
Update Project Creation form with feedback from designer.

## Designs
See [Capri design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-12823&mode=design&t=3ueKX3VtS8XyKx1e-0)

## Acceptance criteria
**Project**:
Changes:
- [x] Project Name field needs `required` indicator.
- [x] Set maximum character length for Project Name to 50 characters
- [x] Set maximum character length for Project Description to 72 characters
- [x] Save button should be disabled until required field (Project Name) is completed.
Where to see it:
1. This is mostly about the project creation form (from Projects > Create Project)
2. But behavior should be the same on the Project Settings form (from Projects > an existing project > Settings tab)

**Site**:
Changes:
- [x] Site Name field needs `required` indicator.
- [x] Set maximum character length for Site Name to 50 characters
- [x] Save button should be disabled until required field (Site Name) is completed.
Where to see it:
1. When creating a site (from Home > click map > Create Site)
2. Maybe when editing a site?? (from Home > an existing site > Settings icon in upper right) --> Nope, this is now [#1234](https://github.com/techmatters/terraso-mobile-client/issues/1234)

## Additional Context
[Feedback from Courtney](https://github.com/techmatters/terraso-product/issues/22#issuecomment-1764735754) on initial implementation

**Comment by CourtneyLee333** [comment]
@DerekCaelin @shrouxm did we have a min number of char for site name? Was it 2? Probably the same should be implemented here.

**Comment by shrouxm** [comment]
site names are at least 3 chars long in the current implementation

**Comment by DerekCaelin** [comment]
WE decided to keep this in Capri

**Comment by knipec** [comment]
@CourtneyLee333 Why 72 characters for the description? That just seems kinda short to me

**Comment by knipec** [comment]
Ok -- I think I personally would want to use it as a paragraph of info, but will keep 72, and see if users are fine with it.

Also FYI I made #1234 to cover the "Edit Site" case because the code isn't set up to make it easy to do these updates the same way.

**Comment by knipec** [comment]
Just merged into main -- should be verifiable in v120

**Comment by DerekCaelin** [comment]
@knipec this meets my expectations from a functional perspective. Thank you! I note that the size of the text for the `Project name must be at most 50 characters` warning is larger than the size of the text for the `Site names must be at most 50 characters` warning, I assume @CourtneyLee333 will weigh in on that in the design review.

**Comment by CourtneyLee333** [comment]
I've sent a bunch of comments to Derek, most of which are outside the small scope of this issue. I've asked him to wrangle them how he sees fit.

**Comment by DerekCaelin** [comment]
@knipec, Great work! @CourtneyLee333 provided the following feedback, I'm interested in sizing out the additional effort required to address this feedback. Please feel free to break these issues into groups to size, if any occur to you. 

### Create Project form:
- This form should be using the new text field component for Project Name and Project description. 
- Input fields should disallow more characters to be entered once the user hits the max.
- The helper and error text should be smaller (12px).
- The Save button should not move as the keyboard opens

#### Create Site form:
-  This form should be using the new text field component for Site Name
- Break out latitude and longitude into separate fields
- If the user inputs text into either the latitude or longitude field, it should stop updating based on the phone GPS.
- The Save button should not move as the keyboard opens. 
- (iOS) - The entire field for Add to Project should be pressable. Currently only the down arrow part is.
- (iOS) (Tablet) - floating keyboard obscures form content.
     1. create a site
     2. type a site name
     3. tap the project dropdown
     4. see issue:  "I moved the keyboard out of the way and the screen content went blank. All I can see is the app bar and the keyboard floating in the middle of the screen. It seems that the content under and beneath the keyboard gets disappeared."

Would you also please resize this updated Data Privacy sheet engineering story? https://github.com/techmatters/terraso-mobile-client/issues

**Comment by DerekCaelin** [comment]
I've filed issues to account for the updates logged above and will close this effort as complete.
