### ISSUE TITLE
Remove Team and Archive Site options from Site Settings

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#535]
Since we're not going to get to either archiving of sites or adding people to individual sites by MVP, let's remove both of those buttons from the site settings page for all users.

![Screenshot_20231114-134040_Terraso LandPKS.jpg](https://github.com/techmatters/terraso-mobile-client/assets/2730009/b6847637-84f6-4987-ac9b-0cef1cb58341)

**Comment by ltseng** [comment]
@CourtneyLee333 does this sound good? Do we need to come up with revised designs as a result?

**Comment by CourtneyLee333** [comment]
That all sounds good to me. I don't think we need a revised design, but I'll get a look when it's built and see if anything needs tweaking.

**Comment by ltseng** [comment]
@paulschreiber I'm also still seeing the archive option and the Team button on the Site settings screen in version 59 on Android
