### ISSUE TITLE
Update Soil ID Tile styling

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#543]
Update the Soil ID Tile, which is used in both the Site and Temporary location Dashboard. See parent tasks for more details. 

## Design
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-14751&mode=design&t=XrTGOkB7lDCSFAHS-0)

![Image](https://github.com/techmatters/terraso-mobile-client/assets/10799815/e02f993f-45ce-4257-b90e-b3517e08c5d6)

## Acceptance Criteria
- [x] Thematic updates (new colors)

**Comment by CourtneyLee333** [comment]
@ltseng Could this be a good first task, the restyling of the tiles part?

**Comment by ltseng** [comment]
Waiting for @paulschreiber to figure out if the existing issues tagged as good first issue are accurate before I add more in.

**Comment by ltseng** [comment]
I don't have an issue for restyling the tiles specifically, did you make one?

**Comment by CourtneyLee333** [comment]
No. I figured since these tasks are still open it means that they cover more than the temporary tiles we made for that demo way back when.

**Comment by ltseng** [comment]
Ok, then I'll modify the description of this task to reference the restyling that needs to be done.

**Comment by CourtneyLee333** [comment]
My QA observations:
- The corners of the tile should be rounded
- Are the font sizes correct? Top Match and Ecological Site Name text looks smaller than Body 1 style. Are the other fonts the right size?
- The button does not use the correct pressed state color

**Comment by DerekCaelin** [comment]
I see https://github.com/techmatters/terraso-mobile-client/pull/1208 will address the comments Courtney made, will review this in May but for now consider the issue closed.
