### ISSUE TITLE
Enforce keyboard types in text input fields

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#560]
The default keyboard should change depending on the type of field. Refer to [this spreadsheet](https://docs.google.com/spreadsheets/d/1HBKCeXsZqp2xPotzanZM4g3f87ETuZCyas-KhXoF_FU/edit#gid=0) for the specifications.

## References 
Followup task from https://github.com/techmatters/terraso-mobile-client/issues/514

**Comment by ltseng** [comment]
@paulschreiber here's the implementation task I promised to create!

**Comment by DerekCaelin** [comment]
A lot of this seems to be addressed already. It seems like the actual task at this stage is to 
- [x] assess priority (Still medium in my opinion)
- [ ] confirm with @CourtneyLee333 that this list is accurate
- [ ] audit the requirements vs implementation
- [ ] revise the issue to reflect what actually needs doing

**Comment by paulschreiber** [comment]
Pretty sure this is done. We might add this is a consideration in https://github.com/techmatters/terraso-mobile-client/issues/1718

**Comment by DerekCaelin** [comment]
This seems done for implemented modules. Closing
