### ISSUE TITLE
Allow searches for one character to go through, and add error message for no search results on Transfer Site page

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#562]
Provide user with an error message a search term is too short in searching sites to transfer to a project, or when it doesn't match any sites.

### Expected behavior
Similar to the Sites tab search:
- Single character search terms should return any matching sites 
- If no sites match: "No sites match the current search term" 

### Additional context

![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/3942080c-c790-4d04-87a0-3fd665814afc)

**Comment by ltseng** [comment]
@CourtneyLee333 for this bug, can we simply reuse the same error message in site or project creation when you try to title the site/project with fewer than 3 characters? Or would you prefer to use a different message?

**Comment by CourtneyLee333** [comment]
Let's say "Enter at least two characters".

**Comment by ltseng** [comment]
Cool, though I think the minimum characters is actually 3 from my testing of this search feature.

**Comment by CourtneyLee333** [comment]
It's definitely 2 for me, on this screen as well as search in other places. We also need a message for when the search yields no results. "No sites match the search term."

**Comment by ltseng** [comment]
Gotcha, I re-tested and am seeing the same thing. I'm all scrambled today in testing this feature!

**Comment by ltseng** [comment]
I modified the description above to account for both cases.

**Comment by ltseng** [comment]
Updated the description again based on the engineering demo

**Comment by DerekCaelin** [comment]
We're ok with how the transfer experience works for now - will wait for a user to flag it
