### ISSUE TITLE
Project title isn't properly truncated on transfer sites screen

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#563]
The full title of this project is "Another transferring sites test," so only the last two characters are being left off. This will probably be a bigger problem for longer titles, of course. This is on an iPhone XS, which is a relatively small-screen device, and would likely show fully on an iPad. Deprioritizing this issue for now, but will probably be something to handle post-MVP

<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/22e84d95-3f2c-4273-b039-78b14f5a054e" width="200">

**Comment by paulschreiber** [comment]
We should solve this more generally with a tail or middle truncation.

**Comment by CourtneyLee333** [comment]
My suggestion:

- 120 characters seems unnecessarily and problematically long for site and project names. Projects, in particular, have the description area for extra description.
- The max number of chars allowed in those titles would be good to display in the field's helper text, and/or just to not allow more chars to be entered when the max has been met.
- It does seem important to show the entire site or project name in the relevant app bars, but maybe a good idea to animate the app bar in and out of view as you scroll. Instagram and Google apps are good examples.
- When transferring sites to projects, I think we should show the whole site name.
- When adding a site to a project during the site creation form, I think we should show the whole project name.

**Comment by knipec** [comment]
If you consider this part of the components library work, can we close this? @tm-ruxandra @CourtneyLee333

**Comment by CourtneyLee333** [comment]
I still agree with my list of suggestions above. We do not yet have an issue for the app bar component, so it seems to me we should create one and include that list in the documentation. Do y'all agree?

**Comment by tm-ruxandra** [comment]
@CourtneyLee333 agreed, we should have component docs for the app bar.

**Comment by DerekCaelin** [comment]
OK, I've added [design](https://github.com/techmatters/terraso-product/issues/946) and [implementation](https://github.com/techmatters/terraso-product/issues/947) tasks to the backlog, and will close this issue out.

**Comment by DerekCaelin** [comment]
OK, I've added [design](https://github.com/techmatters/terraso-product/issues/946) and [implementation](https://github.com/techmatters/terraso-product/issues/947) tasks to the backlog, and will close this issue out.
