### ISSUE TITLE
Viewer can see and click on "Transfer Sites"

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#564]
### App Version

51

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

I shouldn't be able to see or click on the "Transfer Sites" button as a project viewer role.

### Steps to Reproduce

1. Be part of a project as a Viewer
2. Open the project and switch to the Sites tab

### Expected behavior

Transfer Sites button should either be ~disabled or~ hidden. @CourtneyLee333 do you have a preference? This applies to #525 as well.

### Actual behavior

Viewer is able to go through full Transfer Sites experience, stopping short of actually transferring the site.

https://github.com/techmatters/terraso-mobile-client/assets/2730009/4aab7761-c00d-43ed-8333-cd3102058908

**Comment by CourtneyLee333** [comment]
My preference is that the Transfer Sites button be hidden from the Viewer.

**Comment by ltseng** [comment]
I agree. Updated the bug report above!

**Comment by david-code** [comment]
This has been implemented and should be ready for QA

**Comment by ltseng** [comment]
Fixed!
