### ISSUE TITLE
Microsoft SSO: wrong redirect URI error with O365 accounts

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#581]
This happens on Android when I attempt to sign in with my ltseng@olin.edu account.

![Screenshot_20231108-105756_Firefox.jpg](https://github.com/techmatters/terraso-mobile-client/assets/2730009/a5f5a9d4-0edd-43c1-8ca5-2aa04d95660d)

However, I was able to sign in successfully just now with a regular Outlook account on iPad with lillian.tseng@outlook.com

**Comment by paulschreiber** [comment]
Fixed but updating the Azure manifest to add a trailing slash.
