### ISSUE TITLE
Create site: close (X) button intermittently slow to respond

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-mobile-client#594]
### App Version

1.0.0 (57)

### Platforms

- [X] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

On the create site screen, tapping the X to close the screen sometimes results in a delay of several second before the screen goes away.

**Comment by ltseng** [comment]
I think this is related to #352 amd #120
