### ISSUE TITLE
Animation between screens

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#63]
When moving between Sites, Projects and Settings, use a dissolve effect.

**Comment by ltseng** [comment]
Is this still a valid task? Tagging @CourtneyLee333 as well

**Comment by CourtneyLee333** [comment]
Dissolve by default is great. But ideally we'll use more detailed forward/back animation for full screens where appropriate, and open/close for overlay sheets. I've described this in the General Notes for Engineers, and hope it can be addressed when the sheets get implemented and the navigation controls get updated.

**Comment by DerekCaelin** [comment]
As of 7/15/2024, there are animations in sheets and other places, but not between screens. Task is to determine if this is still important.
