### ISSUE TITLE
"Select all" does not select all sites on Transfer sites page

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#672]
### App Version

59

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

Tapping "Select all" should automatically check all the boxes for the contained sites, in this case "A123," "B123," and "C123."

<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/c6976e4a-800b-40b9-86a4-550e1867e453" width="300">

### Steps to Reproduce

1. Create several unaffiliated sites
2. Create a project
3. Click on the Sites tab, and switch to the Transfer Sites screen
4. Under the Unaffiliated section, tap "Select All"

### Expected behavior

The checkboxes next to all unaffiliated sites should be checked, and the "Transfer Sites" button should become selectable

### Actual behavior

The checkboxes are not checked and the button is not selectable

**Comment by ltseng** [comment]
I just tried it again and it seemed to work...I was testing this on iPad where some actions are taking a very long time to complete, so maybe this isn't a real bug?

**Comment by CourtneyLee333** [comment]
@derek this bug no longer exists for me.

**Comment by DerekCaelin** [comment]
This is resolved in 142
