### ISSUE TITLE
Sites List has wrong filter options

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#673]
### App Version

59

### Platforms

- [X] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

The sites list filter menu should not have "Sort projects by" and should have "Filter sites by project." 
The "Filter sites by role" option should stay as-is.

![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/fc5498ce-514f-4d55-936c-ba771dea7a2e)

### Steps to Reproduce

Tap the filter button on the sites list

### Expected behavior

<img width="248" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/65224941-4eb7-462d-b51b-385c6845db9d">

### Actual behavior

![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/cf437794-e4f1-4dc0-bfa5-3879fa21f050)

**Comment by ltseng** [comment]
Can I expect this to be released this week?

**Comment by david-code** [comment]
@ltseng Will release this evening
