### ISSUE TITLE
Reduce max char limit for site and project titles to 50 characters

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#674]
Set the max character length for Site and Project names to 50 characters.

## Acceptance Criteria
- [ ] Site
- [ ] Project

**Comment by CourtneyLee333** [comment]
Yes!

**Comment by ltseng** [comment]
Ok, editing the title and description then. Thanks!

**Comment by DerekCaelin** [comment]
Still issue as of 118. Trimmed the description.

**Comment by DerekCaelin** [comment]
Closing as duplicate of https://github.com/techmatters/terraso-mobile-client/issues/534
