### ISSUE TITLE
Tapping outside of search suggestions list opens location popover 

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#675]
### App Version

59

### Platforms

- [ ] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

When I type a search term into the home screen search field and then tap outside of the list of suggestions, I expect the list of suggestions to close. That is how it worked before. However, the first tap is now opening a location popover and re-centering the map viewport, and it takes yet another tap to actually close the list of suggestions.

### Steps to Reproduce

1. Type a search term into the home screen search field
2. Tap outside of the search box

### Expected behavior

List of search results should close

### Actual behavior

The app opens a location popover at the tapped location on the map and recenters the viewport

**Comment by knipec** [comment]
FYI @DerekCaelin I am not able to reproduce this. If I tap the map with the search results up, it either closes the results, or closes the results and opens a temporary location callout. Closing as "no repro".
