### ISSUE TITLE
App crashes when I attempt to search for sites with non-matching keyword

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#676]
### App Version

59

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

App crashes when I type in a search term that does not match a site or site's notes

### Steps to Reproduce

1. Create a site
2. Open the site and take a note
3. Go back to the sites list and search for the search term
4. Change the search term to something you know doesn't match the site

### Expected behavior

When you type in a search term that is in the site's notes, the site should be returned. When you type in a search term that isn't in the site's notes, the app should tell you there are no matching sites.

### Actual behavior

The matching search term case works fine. The non-matching search term causes the app to crash on both my Android and iPad.

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/1f4c1779-85ce-4fd6-88ac-28f3f22b74c9

**Comment by ltseng** [comment]
This is definitely related to #681. I just tried to replicate it again in my lilly.tseng@gmail.com account now that sites and projects are loading, and was not able to. We should probably still try to fix this, but if we are able to fix #681, then this bug is a lower-priority task.

**Comment by ltseng** [comment]
Still able to reproduce this in build 102. Try scrolling while typing in a non-matching keyword

**Comment by DerekCaelin** [comment]
@tm-ruxandra I can't replicate the error on iOS or Android, this is resolved for me.
