### ISSUE TITLE
Takes two tries for "None" option to show correctly in Projects list once selected

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#689]
### App Version

59

### Platforms

- [X] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

Selecting "None" for the first time fails to clear out previously selected sort/filter criteria, but functions correctly.

### Steps to Reproduce

1. Go to projects tab and select a sort and a filter criteria, i.e. Sort (A to Z) and Manager
2. Click Apply
3. Set Sort projects by to None and Filter projects by to "None"

### Expected behavior

The dropdowns reset to "None"

### Actual behavior

The dropdowns still display their previously-populated data, but clicking Apply works correctly.

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/58cb9919-3d4d-40bf-bf53-284685538652

**Comment by CourtneyLee333** [comment]
@DerekCaelin I do not experience this bug.

**Comment by DerekCaelin** [comment]
Nor me in 128. closing
