### ISSUE TITLE
Change options for projects filter of "sort projects by" and default sort

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#690]
### App Version

136

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

The options for Sort projects by are "None", "Sort (A to Z)" and "Sort (Z to A)." They need to be "Newest", "Oldest", and "Name". The default should be Newest. 

### Actual behavior

![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/fd738a87-d3f9-4778-bd33-5ce9ace96397)

**Comment by PraveenShinde3** [comment]
Can i work on this?

**Comment by ltseng** [comment]
The public is generally welcome to submit PRs, but our team is very small, and we don't have the resources to make any promises about when we can get them merged, or what level of support we can offer you in getting the work done. Thanks for your interest though!
