### ISSUE TITLE
Bottom sheet opens over location popover upon saving site

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#691]
### App Version

59

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

When I create a site, I should be taken back to the home screen map, with the viewport centered on the location popover for the site I just created. I'm seeing that the bottom sheet is opening over the popover though.

### Steps to Reproduce

1. Create a site

### Expected behavior

Be taken back to home screen map, with viewport centered on location popover for site I just created

### Actual behavior

The bottom sheet is opening over the location popover, rendering it unviewable.

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/7f4cecb4-f810-4586-a721-81e739fb6a5f

**Comment by ltseng** [comment]
From discussion with @CourtneyLee333 -

> I wonder if it should be a rule that anytime a location/site popover is opened, the Sites List should be minimized. User could still drag it open if they wanted to. Right now, if you go to the home screen the Sites List is halfway open; when you tap the map you can't see much of the popover because the Sites List covers it.

**Comment by DerekCaelin** [comment]
Resolved in Android and iOS as of 1.0.110.
