### ISSUE TITLE
Update enabled and disabled button styles

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#696]
Pending some exploration into how to style a button as disabled while still allowing it to be accessible to screenreaders, we need to go through the app and make sure to update the component styles for enabled and disabled buttons, as per https://github.com/techmatters/terraso-product/issues/492

**Comment by paulschreiber** [comment]
This will be covered by https://github.com/techmatters/terraso-mobile-client/issues/1856
