### ISSUE TITLE
Make InfoSheet consistent with design

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#697]
The existing InfoOverlaySheet (formerly InfoModal) should be standardized to replace other similar ones, like PrivacyModal and LandPKSInfo. This will make our implementation compliant with the design spec and keep language consistent between design and the code implementing it.

Acceptance criteria:
- [ ] All info sheets are declared consistently in the code
- [ ] All info sheets open to the correct height
- [ ] All info sheets use BigCloseButton and close as expected when the button is pressed (test on both emulator AND actual hardware)

Reference:
[Figma component documentation](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7202-34072&t=jfxN9AWtvF9qgq2d-1)

Double check, but I think this involves: 
- Updating the design for info sheets that already use the InfoOverlaySheet, and just rename it appropriately
- Use it in places that didn't use a standardized info sheet at all:
-- Data Privacy sheet found in [Create Site form](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-14603&t=jfxN9AWtvF9qgq2d-1), [Create Project form](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-12984&t=jfxN9AWtvF9qgq2d-1), [Project Inputs tab](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-12975&t=jfxN9AWtvF9qgq2d-1)
-- LocationScoreInfoSheet  found in [Site Soil info sheet](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7413-9520&t=jfxN9AWtvF9qgq2d-1) and [Temp location Soil info sheet](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7413-9803&t=jfxN9AWtvF9qgq2d-1) 
-- PropertiesScoreInfoSheet  found in [Site Soil ID](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7413-9520&t=jfxN9AWtvF9qgq2d-1)
- Also, make sure [Info sheet on home screen app bar](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-13165&t=jfxN9AWtvF9qgq2d-1) uses BigCloseButton.

**Comment by ltseng** [comment]
@shrouxm to quote a discussion from https://github.com/techmatters/terraso-product/issues/475

> The Sites List is on the only true bottom sheet, and can stay as-is. The other sheets (like Soil Info sheet and various help info content (with the i icon), need to have the styles as listed in this issue's description and to animate in from the bottom. They will all be consistent except some different UI elements to close them. Most of this has been fleshed out in the Figma designs, but I want to officially establish the pattern and take steps to remedy the outdated implementation.

It looks like this task had to do with styling and animation, not content. In light of this, would you consider this work already done?

**Comment by shrouxm** [comment]
@ltseng ohh i see, in that case i think so but am not confident so i'll self-assign this to remember to check and close it out this week

**Comment by shrouxm** [comment]
ok so upon review, there is now a re-usable component that implements the design correctly, but there are still places where we aren't using it. i think it makes sense to group this with the other overlay sheet task carissa has assigned to them right now so i will re-assign and move back to todo

**Comment by CourtneyLee333** [comment]
@knipec @DerekCaelin I've updated the description area to have links to Capri designs, and made notes of my observations. It's not clear to me if this issue is specifically about component styles, so I went ahead and noted content differences.

**Comment by DerekCaelin** [comment]
these changes should be reflected in the issues in outstanding stories.

**Comment by knipec** [comment]
Oh, re-reading Garo's comment above, I'm wondering if this is actually a refactoring task to get a few existing info sheets (I think LandPKSInfo and the Privacy one) to use the InfoModal component instead of their own thing?

**Comment by knipec** [comment]
Re-opening and assigning to @DerekCaelin to move into a post-Capri milestone

**Comment by knipec** [comment]
Oops apparently I forgot to actually reopen this, doing that now

**Comment by tm-ruxandra** [comment]
Updated title and description based on conversation had with @knipec and @CourtneyLee333 regarding future design-engineering coordination.

**Comment by CourtneyLee333** [comment]
I added more detail to the description including Figma references and places around the app where the issues are found (there might be more places, and I will update this issue as I find them.) @DerekCaelin Just FYI this could be a P1 issue for users who don't realize they can swipe the sheet down to close it - the close button not working would be a blocker in that case.

**Comment by knipec** [comment]
Sounds like this might be about some user-facing behavior, not purely a refactor / tech debt item -- if that's confirmed it'd just be nice to update the title or something to reflect that :)

**Comment by knipec** [comment]
Passing off to @tm-ruxandra who says "yeah that's mine and yes pass it to me :)"

**Comment by tm-ruxandra** [comment]
@DerekCaelin I'm fine with this not being a P1 if that's your opinion. Agree that 1 point isn't accurate here; I would size it at 2 or 3.

**Comment by CourtneyLee333** [comment]
Looks great to me!
