### ISSUE TITLE
Bug: filter sometimes returns undefined when it doesn't match project

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#706]
Reproduce:

- In Home Screen, select a the project filter of a project where you have sites
- Switch the filter to another project where the site will be removed
- Notice that the site in the store is now undefined
- I can't reproduce this consistently, so it seems like maybe something is missing - maybe this is caused by inconsistent state in the redux store during development?

**Comment by shrouxm** [comment]
i can't reproduce this

**Comment by shrouxm** [comment]
i can't reproduce this
