### ISSUE TITLE
Edit this issue: Redo design updates

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#708]
### Derek: Define acceptance criteria for each of these issues, validate their status, pull into relevant tasks as needed.

[Courtney's full list of feedback](https://docs.google.com/document/d/1IwLjAjOss07z1ush6X2gPh-NgAbQF1x3G0ZSsesSJS4/edit).

There were a number of requested changes that weren't implemented as part of the design update work from the usability study in September. This is not urgent, but should be completed before release. 

## Acceptance Criteria

Site Creation form
- https://github.com/techmatters/terraso-product/issues/862
- [x] Update text for Add to Project tooltip
  - [x] When you add a site to a project, it will use the data settings and team members from the project.

Create Project form
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1318
- [x] Data privacy info icon is using wrong color
- [x] Default project privacy should be set to **public**

Project settings tab 
- [x] Change "Imperial" to "English"
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/688
- [x] Change name of "Submit" button to "Save"
- [x] Save button should be disabled until a change is made

Form inputs 
- [x] All form inputs need to be restyled according to the design patterns we have agreed upon. This decision has been documented in the [Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4300-25272&mode=design&t=Q79RyARYraQJYKhg-0) (see Forms section of General Notes for Engineers)

**Comment by DerekCaelin** [comment]
Edited this, closing the issue since the outstanding comments are reflected in other open issues.
