### ISSUE TITLE
Project contributor/viewer can see and click on "Add Team Members"

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#710]
### App Version

66

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

Project contributors and viewers can see and click on "Add Team Members" on the Project Team tab

### Steps to Reproduce

As a project contributor or viewer, click on the Project Team tab

### Expected behavior

The "Add Team Members" button is not visible

### Actual behavior

The contributor/viewer is able to click on Add Team Members and go through the full process of searching for another user, changing the role, and clicking "Save," only to fail silently.

**Comment by david-code** [comment]
This should be ready for QA as well.

**Comment by ltseng** [comment]
Works on Android! Waiting for Build 79 to be made available on iOS so I can verify this on that platform as well.

**Comment by ltseng** [comment]
Confirmed on iPhone!
