### ISSUE TITLE
Notes sometimes load in wrong site

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#712]
### App Version

66

### Platforms

- [ ] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

I'm noticing that when I log in and open up a random site, it will load notes for a different site. It's hard to replicate, and usually requires a relaunch of the app, but I've seen it a couple times now

### Steps to Reproduce

1. Launch the app and immediately open a random site from the sites list

### Expected behavior

Should see notes for that site, if any

### Actual behavior

Notes for a different site will load

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/12f2d6d1-9a46-49ef-9b11-fdf6fc1d399d

**Comment by shrouxm** [comment]
@ltseng i can't reproduce this, have you seen it recently?
