### ISSUE TITLE
Update link style of app bar info sheet

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#715]
Update the style of links in the LandPKS info sheet, using the component developed in  https://github.com/techmatters/terraso-mobile-client/issues/954. 

## Design

[App bar info sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2066%3A93125&mode=design&t=dndvQF8yefLoHf3X-1)

## Steps to find the screen:

1. Open the LandPKS app
2. Log in
3. On the home screen, tap the (i) button in the top right corner.

## Acceptance criteria
-

**Comment by paulschreiber** [comment]
This was addressed by https://github.com/techmatters/terraso-mobile-client/pull/1781 and https://github.com/techmatters/terraso-mobile-client/pull/1778
