### ISSUE TITLE
Add lat/long, GPS accuracy, to temporary location popovers

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#720]
Add lat/long coordinates to temporary location popovers, with location accuracy if the user has selected their own location as a popover.

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=3747%3A20777&t=wTWiGhdjDSIMSUKp-1)
<img width="631" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/10799815/64fd4b9b-fe08-4805-99ed-1e369463ac00">

## Acceptance Criteria
- [ ] All temporary locations - show latitude, longitude at the top of the popover
- [ ] My location - also show "Your Location" and updating GPS accuracy when the user has selected their own location on the map.

**Comment by CourtneyLee333** [comment]
@DerekCaelin There should also be an issue for adding lat/long to the non- +Your Location" popover [as seen here](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=3747%3A20777&t=wTWiGhdjDSIMSUKp-1).

**Comment by DerekCaelin** [comment]
@CourtneyLee333 I re-wrote the issue to reflect both all "Temporary Location" and "My Location" scenarios

**Comment by DerekCaelin** [comment]
This meets functional review. @CourtneyLee333 over to you for design review.

**Comment by CourtneyLee333** [comment]
@DerekCaelin This meets my functional review as well. Some design notes:
- When I tap my location, the CloseButton on the popover is too low, seemingly beneath the "Your location" line of text. Ideally the CloseButton should stay in its correct place. 
- The labels on the popover should be in mixed case (Soil ID Top Match, Ecological Site Top Match, Elevation), rather than all caps. This note might belong on a different issue.

**Comment by DerekCaelin** [comment]
> The labels on the popover should be in mixed case (Soil ID Top Match, Ecological Site Top Match, Elevation), rather than all caps. This note might belong on a different issue.
I have added an issue here: https://github.com/techmatters/terraso-mobile-client/issues/1445

**Comment by DerekCaelin** [comment]
Will make a separate task for:
> When I tap my location, the CloseButton on the popover is too low, seemingly beneath the "Your location" line of text. Ideally the CloseButton should stay in its correct place.
