### ISSUE TITLE
Add Team Members won't accept comma-separated list of users

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#733]
### App Version

68

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

The Add Team members screen directs me to "Enter single or multiple Terraso email addresses in the field below." I typed in a comma-separated list of two email addresses for accounts that I know are in the system, but received an error message. I think that the code isn't splitting the text field input by delimiter, but rather searching for the entire screen.

### Steps to Reproduce

1. Open a project where you are a Manager, switch to the Team Tab, and tap "Add Team Member."
2.  Type in a comma-separated list of at least two emails. Click Save.

### Expected behavior

1. Each email is properly recognized and processed by the app. Each email address turns into a separate card with the ability to toggle the role of the invited user,

### Actual behavior

1. I see an error message with the text "User courtney@techmatters.org, lilly.tseng@gmail.com is not a Terraso user, unable to add to project."

### Additional context

<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/7661a05c-3b40-47b1-a095-d2b20b3349d7" width=300>

**Comment by ltseng** [comment]
@CourtneyLee333 double check me here - this is supposed to work, right?

**Comment by CourtneyLee333** [comment]
Yes. It should accept a comma and a space to separate email addresses. @paulschreiber said this was possible.

**Comment by paulschreiber** [comment]
We should make this a multi-line field and accept comma-, space- and newline-separated lists.

**Comment by ltseng** [comment]
@paulschreiber I did notice that this keyboard, at least on Android, did not allow me to press the "enter" key. Is that because this is a single-line field?

**Comment by paulschreiber** [comment]
@ltseng what does "did not allow" mean? is the enter key disabled or not present?

**Comment by ltseng** [comment]
It was not present
