### ISSUE TITLE
Enable Bridgeless mode for React Native

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-mobile-client#734]
## Description
Enable Bridgeless mode for React Native

See notes at https://github.com/reactwg/react-native-new-architecture/discussions/154

**Comment by shrouxm** [comment]
Note: [the 0.73 release blog](https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#new-architecture-updates) states "As with the rest of the New Architecture, Bridgeless Mode is initially experimental." so not sure if this should be considered high prio yet, but if someone wants to try it and it Just Works then we might as well.
