### ISSUE TITLE
Styling and Icons Updates for Pinned and Site Notes

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#750]
The following styling changes are needed for the Notes section. 

[pinned note design for project management](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-12975&t=WTfNwf9zLOAzz9W4-1)
[pinned note design for Site](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-12772&t=WTfNwf9zLOAzz9W4-1)

## Acceptance Criteria

- [x] Project Management screen - button label should be "Note" and needs pushpin icon. 
- [x] Site Notes tab - Site Instructions should be "Pinned Note" and needs pushpin icon.
- [x] Open pinned note in Site - Heading should be Pinned Note.
- [x] Site Note card needs date time format: 9/4/23 14:24. 
- [x] Site Note card needs meta data in pBody2 italic. 
- [ ] Confirmation dialog should be grey #EEEEEE, with drop shadow. Background should not be dimmed.

**Comment by Kenny4297** [comment]
Hi @ltseng, I believe I may be able to help with this issue. Would you mind assigning me to it?

**Comment by paulschreiber** [comment]
@CourtneyLee333 can this be closed?

**Comment by CourtneyLee333** [comment]
Looks good.
