### ISSUE TITLE
Close bottom sheet halfway when user searches Sites List

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#753]
## Current behavior

When a search is entered in the Sites List search bar, the bottom sheet and map stay unchanged, i.e. the bottom sheet stays exactly as open as it was when the search was initiated, and the map viewport is not adjusted.

## Desired behavior

When a search is entered in the Sites List search bar and the user clicks "Done" or some other keyboard submit button, the bottom sheet should close half way and the map should re-orient to show the relevant sites in the viewport - to make it obvious that the map and site markers are affected by the search in the Sites List.

**Comment by CourtneyLee333** [comment]
Yes definitely. On the ipad I see the "return" key which closes the keyboard. And on Android I see a checkmark which closes the keyboard.

**Comment by ltseng** [comment]
Laura logged this as a bug for the following test case:

> *Action*
> Using the search bar at the top of the screen, type in a keyword that matches a location you have in mind.
> *Expected outcome*
> A dropdown list of search suggestions should appear below the search bar. Selecting one of them should close the list of search suggestions, re-center the map's viewport on the selected location, and drop a pin with a "location popover" open below it.


> The first time I did this, the location popover did not appear (IMG_0045, IMG_0046). Upon retrying this, the location popover did appear (IMG_0047).

<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/c773522a-7993-418e-ad27-71ec80536559" width="300px">
<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/f2e8c15c-1570-48e6-b067-f420b450163e" width="300px">
<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/17a038ac-7053-4b4b-b5c2-1f5e3c877b3a" width="300px">

I think part of the reason why they thought this was a bug was that the sites list bottom sheet covers up the location popover, which we might want to address either in this issue or a related one. I'm not sure how to explain the second image, though.

**Comment by CourtneyLee333** [comment]
@ltseng I think this last feedback is on the wrong bug report. This bug report is about searching the sites list, but the feedback from Laura is about searching the map.

**Comment by ltseng** [comment]
Good point, I'll open a new issue for this.

**Comment by DerekCaelin** [comment]
Addressed in 142 (behavior is that the sheet collapses as user types in search)
