### ISSUE TITLE
Styling feedback for Projects list

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#754]
<img width="158" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/e5c19244-0dee-4707-91a6-aa47eca78d50">

- [x] Empty state content needs to be updated
- [ ] Remove tooltip icon in app bar

<img width="159" alt="image" src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/53876834-a594-4ba6-9ce6-98fd9be921cd">

- [ ] Completion status needs to be in chip
- [ ] Last modified needs correct date format - MM/DD/YYYY.

**Comment by ltseng** [comment]
@CourtneyLee333 can you specify what the correct date format should be here too?

**Comment by CourtneyLee333** [comment]
MM/DD/YYYY

**Comment by paulschreiber** [comment]
@CourtneyLee333 can this be closed?

**Comment by CourtneyLee333** [comment]
I can't tell the background color. If it's grey/300 (#E0E0E0) this can be closed.

**Comment by paulschreiber** [comment]
Background colors were covered in https://github.com/techmatters/terraso-mobile-client/issues/1506

Closing
