### ISSUE TITLE
Project Inputs - use pushpin icon on notes button and make background white

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#756]
- [x] Pinned Site Note heading should be changed to Pinned Note
- [ ] Pinned Site Note button should use pushpin icon (currently uses pencil icon)
- [ ] Entire screen body should be white. (currently appears to be pale gray)

**Comment by paulschreiber** [comment]
@CourtneyLee333 is this done?

**Comment by CourtneyLee333** [comment]
It appears so on iOS. I can't check Android but assume it's consistent.
