### ISSUE TITLE
Build manual Soil ID/Ecological Site ID menu

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#762]
Accessible from the main page for Soil ID. Allows users to manually type in the soil name and/or ecological site ID and/or ecological site name if known. Ideally, would use https://github.com/techmatters/terraso-backend/issues/1097 to auto-complete whatever users type in to manual entry fields.

Designs are still evolving. Please check for the [most recent design release](https://www.figma.com/files/project/87085153/LandPKS?fuid=1209917626938630763)

**Comment by DerekCaelin** [comment]
Now a duplicate of: https://github.com/techmatters/terraso-product/issues/634
