### ISSUE TITLE
bug: slope meter screen does not lock to landscape orientation on iOS

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#763]
### App Version

72

### Platforms

- [X] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

The slope meter screen should be in a landscape orientation. On my iPhone 8 on app version 72 it is in portrait orientation.

### Steps to Reproduce

1. Navigate to a site.
2. Navigate to the slope tab.
3. Navigate to the steepness data input.
4. Navigate to the slope meter.

### Expected behavior

The screen is in landscape orientation.

### Actual behavior

The screen is in portrait orientation.

**Comment by shrouxm** [comment]
lillian reported this is still a bug in a new build including #767

**Comment by DerekCaelin** [comment]
Closed in 128
