### ISSUE TITLE
Enormous pin icons on home screen map

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#764]
January 9, 2024- Observed in Build 18 on Android and 72 on iOS, and earlier builds, but not logged until now.

The pin icons for sites and temporary locations are comically large, and even more so when selected.

<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/eaa51385-c40c-4b4c-b80d-301701f002a7" width="300">

**Comment by ltseng** [comment]
@shrouxm hopefully this is a quick fix? I recall you saying something about this in a demo...

**Comment by shrouxm** [comment]
well it was fixed at some point, no idea why it is broken again :weary: possibly due to a version upgrade with mapbox dependency. will try to look when i have time

**Comment by ltseng** [comment]
Cool, no worries or rush, just tracking this for future reference. Thanks!

**Comment by shrouxm** [comment]
@ltseng this should :crossed_fingers: be fixed next release!

**Comment by ltseng** [comment]
Awesome!
