### ISSUE TITLE
Clearing out steepness/shape data

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#766]
We need the ability to clear out previously-taken slope data for sites. The manual entry steepness inputs can be cleared out by tapping into the text fields for steepness/percentage and hitting backspace. The image selections for steepness and slope shape, however, can't be easily cleared.

Proposal: When a slope steepness/shape image is already selected, tapping it should unselect the image.

**Comment by ltseng** [comment]
@CourtneyLee333 is this what you were picturing?

**Comment by CourtneyLee333** [comment]
Yes, though I don't think a confirmation dialog is necessary. They'd have to tap the image to unselect, and the unselected state will be obvious, then tap the Done button.

**Comment by ltseng** [comment]
Even in the case where data exists already, and the user is clearing it out?

**Comment by CourtneyLee333** [comment]
Garo and I had a discussion about this which you can see in the comment on that dialog. The gist is: if there is an existing manual entry or a slope meter entry, tapping an image should trigger the Change Slope dialog.

**Comment by CourtneyLee333** [comment]
I think it will be common for users to tap on different images much more frequently than they would manually enter or use the slope meter. Showing the dialog every time they tap an image, in addition to having to tap the Done button, would be annoying.

**Comment by ltseng** [comment]
This makes sense, thanks for explaining it to me! Modifying the description now.
