### ISSUE TITLE
Update this issue Styling feedback for Adding Users to Projects

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#769]
![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/34ea098d-1a13-4c0d-8e8a-5e2caaab83ee)

THESE DETAILS NEED UPDATING BEFORE THIS TASK IS STARTED.

- The body of the screen should be white, slider is grey. This is an issue throughout the app, and makes grey elements on the body disappear. It’s hard for me to tell which screens/elements have incorrect grey colors on my phone but the lack of contrast is apparent. 
- Leave Project button  - the grey background should be visible. Please check hex value. 
- Need Manage Team heading [(see Figma)](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=221%3A19771&mode=design&t=YV2iWg8wKJJZUKWY-1) , with correct font size
- Leave Project dialog needs updated verbiage

![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/fd6257fd-759e-4daa-bfe5-33779152c205)

- “Add Team Members” Heading needs tooltip and correct font size
- Remove “Enter single or multiple..” paragraph. 
- Error text and placement is wrong. Email field error should be for valid email address and alert if a user is already a team member, not Terraso account validation. Terrasso account validation gets displayed below. [See Figma.](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4059%3A32554&mode=design&t=YV2iWg8wKJJZUKWY-1)

![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/7eb99d37-d8d9-4f6a-99c0-50927de145c1)

- Placeholder in the field is incorrect. Should be “Email addresses”. [See figma. ](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=4059%3A32573&mode=design&t=v3g8jVNDH5esPVlN-1)Though the text field component and style is going to change when the implement the agreed upon updates.

**Comment by DerekCaelin** [comment]
![Image](https://github.com/techmatters/terraso-mobile-client/assets/10799815/3e36826b-3eb8-46bd-94dd-e4e43d5d1101)

Courtney: [4/24/2024](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN?type=design&node-id=5800-13057&mode=design#781953262)
I updated this design to have the paragraph text under the heading rather than in a tooltip.

**Comment by DerekCaelin** [comment]
Closing this issue out since we are tackling specific Capri updates to this experience with https://github.com/techmatters/terraso-product/issues/835
