### ISSUE TITLE
Changing user roles screen needs heading

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#770]
Needs Manage Team Member heading. [See figma.](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=232%3A21387&mode=design&t=v3g8jVNDH5esPVlN-1) Use correct font size.

**Comment by CourtneyLee333** [comment]
Completed in another issue.
