### ISSUE TITLE
When searching for lat/long coordinates, map should pan/zoom only after user presses "enter"

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#772]
### App Version

70

### Platforms

- [X] iOS
- [x] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description
When entering latitude, longitude coordinates into the search bar, the map will move the moment there is a viable lat/long entered, and will continue moving to a new spot for each character entered. It's a jarring experience to have such a small screen map moving around while still entering your details.

### Steps to Reproduce

1. Type "45, 160" into the search bar

### Expected behavior

The map waits until the user presses enter, then moves to the entered location. 

### Actual behavior

The map starts panning and zooming once any valid (even incomplete) lat/long coordinates have been entered, eg:
- "45, 1"
- "45, 16"
- "45, 160"

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/d06d6031-3759-42ac-97b7-3d8720afe435

**Comment by ltseng** [comment]
@CourtneyLee333 this was an issue that Dee ran into during her user testing, just tagging you to keep you in the loop.

**Comment by CourtneyLee333** [comment]
I've seen that issue as well.

**Comment by ltseng** [comment]
Laura has noted this issue as well:

> Unsure if this is a bug or just a UX concern; the feature worked, but the map started rezooming immediately after the first digit of the longitude was typed. Given that most longitude numbers are at least 2 digits, it would make more sense to have this happen on "Enter" or after a second delay to allow the user to finish typing. It felt confusing / disruptive as the user to have it start moving before I was done typing.

**Comment by paulschreiber** [comment]
This was addressed with https://github.com/techmatters/terraso-mobile-client/pull/1848
