### ISSUE TITLE
bug: Fix NativeBase checkbox selection

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#82]
It seems like the NativeBase has a [checkbox component bug](https://github.com/GeekyAnts/NativeBase/issues/5098). This means that we can't reliably use the NativeBase checkbox as it currently stands. This issue will be to consider two options:

1. Submit a PR to NativeBase fixing the issue.
2. Find a replace component and see if we can use [NativeBase factory](https://docs.nativebase.io/nativebase-factory) to fix it. Note that there is no built in component in React Native, so it would need to be a separate third-party library.

My preference would be to submit the PR ourselves, as we are aiming to help contribute to other open source projects as well. So I think the first task would be to get an idea of how difficult the bug would be to fix. If it's more complicated than we have time for, we'll select a third-party library. If not, we can try submitting a PR to fix it.

Some notes about the bug itself:
- Explained pretty well in a [comment](https://github.com/GeekyAnts/NativeBase/issues/5098#issuecomment-1579910908) in the above issue.
- However, the issue is not solved in the current release. The commit upgrading the library that's causing the bug was reverted as it seems to have broke things.
- The fix seems like it will be trying to upgrade the library `@react-stately/checkbox` and making sure things to break.
- Should we consider using [gluestack-ui](https://ui.gluestack.io/)?

**Comment by shrouxm** [comment]
yes, we're already not using the NativeBase checkbox
