### ISSUE TITLE
Slope steepness images are displaying in 1-column format in iOS

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#822]
### App Version

77

### Platforms

- [X] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

Slope steepness images should be displaying in two-column format, but instead are showing in 1-column

### Additional context

<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/eaa68238-6be0-4e2d-be37-ae2614dcd70f" width="300px">

**Comment by paulschreiber** [comment]
@ltseng Which device is this on?

**Comment by ltseng** [comment]
iPhone XS, I think? The only iPhone I have. Should be in the testing sheet.

**Comment by ltseng** [comment]
Still observed on iOS in build 79

**Comment by CourtneyLee333** [comment]
Noting that this is not the case on my iPad.

**Comment by DerekCaelin** [comment]
Not happening in 127
