### ISSUE TITLE
bug: bottom sheets do not work when user has reduced motion accessibility setting enabled

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#825]
### App Version

78

### Platforms

- [X] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

On release builds, when the user has reduce motion enabled in their iOS device's accessibility settings, none of the app's bottom sheets will appear

### Additional context

this is a known issue with our bottom sheet library, discussed at length [here](https://github.com/gorhom/react-native-bottom-sheet/issues/1560). there are some workarounds discussed in the thread, but hopefully it will get fixed upstream by the time we have capacity to look into this. i would say it's fairly high priority as while it does only affect a small fraction of users, a lot of core app functionality is completely broken for those users

**Comment by DerekCaelin** [comment]
This appears addressed in 142
