### ISSUE TITLE
Clearing text fields for slope steepness percentage and degrees doesn't fully clear out the other

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#841]
### App Version

79

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

When I type in a number to either the percentage or degrees text field, and then hit backspace, the other value doesn't completely clear out.

### Steps to Reproduce

1. Open the slope steepness data input for a site
2. Tap the manual button
3. Select either the percentage or degrees text input and type any positive integer. You should see the other, unselected text field, update as well.
4. Hit backspace on the keyboard to completely delete the number you just typed.

### Expected behavior

The opposite text field should completely clear as well

### Actual behavior

The opposite text field will continue to display a numeric value that doesn't match the current value of the active numeric input.

Example - I had typed 45 into percentage, which correlates to 24 degrees. When I erase 45, since 4 is the last-displayed number, 2 continues to display for degrees. When I click save at that point, slope steepness is saved as 2 degrees.

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/56c04e4b-d58b-4133-874d-1231ba86c587

**Comment by DerekCaelin** [comment]
This is still an issue as of now... removing the `stale` tag, but keeping the `needs triage` and will plan to discuss it

**Comment by DerekCaelin** [comment]
This is resolved.
