### ISSUE TITLE
App crashes when opening site 

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#845]
### App Version

79

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

I added a site to a project where I had the manager role on the Site Creation form. I was able to save the site successfully, but when I tried to open it up from the location popover, the app crashed. When I next launched the app, the site I had just created was gone.

### Steps to Reproduce

1. Tap a location on the map to create a site and click "Create Site" from the location popover
2. Name the site and add it to a project where you have the manager role. Click save to be taken back to the home screen map, where the location popover for the newly-created site should be open.
3. Tap the location popover to open the site dashboard, or drag up the Sites List drawer and open the site from that list.

### Expected behavior

The site dashboard opens

### Actual behavior

The app crashes. When it is launched again, the site is not saved.

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/79b8b96e-6a37-4f6a-ab3b-ddb2a321e779

**Comment by ltseng** [comment]
@paulschreiber or @CourtneyLee333 are you able to replicate this bug? I recorded a demo for ISRIC and BLM and couldn't get around this one.

**Comment by CourtneyLee333** [comment]
On my Android the new site will not save. After I fill out the site creation form, I tap the save button. I see the color of the button change, but nothing else happens. When I tap the X button to go back to the map, the site has not been created. I do not experience this issue if I don't add the site to a project. 

On my iPad I have a different experience. On the site creation form I add a name, then choose a project. As soon as I tap the project on the list, the content of the screen goes blank and I only see the app bar and the save button. I can tap save and am taken to the home screen with the newly created site visible and the popover open. The details appear correct - name, project,  When I tap the popover the app crashes. When I open the app again, I can successfully tap the site pin and open the site from the popover.

**Comment by ltseng** [comment]
Confirmed fixed on Android and iOS
