### ISSUE TITLE
Styling feedback for slope data input

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#848]
- [x] The modal for "enter steepness percentage or degree" should show error text when user enters a degree number outside the range. I think turning the helper text red would suffice.
<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/92cdb953-a6ef-4b0d-b327-61abcf5842fb" width="300px">

- [x] Limit manual input for percentage to 999%, and degrees field input to 99 degrees (i.e. 2 digit numeric input). See discussion below for more context.
<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/84c9e5eb-4867-41b0-8280-f022dabd9f89" width="300px">

- [ ] I'm concerned that the grey font is too light in the field placeholders, so I'm hoping that gets updated when they update the form styles in general.
- [x] Hide the Done button on the slope data input screens from project/site viewers
- [x] Hide the manual and slope meter buttons on the slope steepness screens for project/site viewers.
- [x] On iPads, the "or" in the "Enter steepness or percentage degree" headline for the manual slope steepness entry modal is omitted

<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/13cef606-b71f-4ecf-a041-894efe68336f">

**Comment by ltseng** [comment]
@CourtneyLee333 to respond to your point about maximum steepness percentage, I've seen a couple references saying that anything over 60 degrees is basically a rock face. The iPhone's accelerometer seems to go up to 5729% or 89 degrees. I'd be happy to set the maximum at somewhere in between 😂 .

**Comment by CourtneyLee333** [comment]
We could limit that field to 3 numbers. Would that solve the problem? Will people actually need to enter something over 999%? 

We might also want to limit the degrees field to two numbers, since 89 is the max allowed.

**Comment by ltseng** [comment]
I think 999% would be a safe maximum for percentage :) I'll update the issue description now.
