### ISSUE TITLE
Add "none" option to soil texture list

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#859]
### App Version

110

### Platforms

- [x] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

No "None" option appears in Soil Texture dropdown

### Steps to Reproduce

1. Enter a random site texture
2. Return to dropdown list
3. see issue

### Expected behavior

User should see at the top a "None" field equivalent (value equivalent to blank)

### Actual behavior

User sees a blank field at the top of the dropdown, when they should see the word "None" - no adequate signifier to revert the selection

**Comment by CourtneyLee333** [comment]
@DerekCaelin This issue seems resolved to me.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 I still see this issue in Android on 128

**Comment by CourtneyLee333** [comment]
@DerekCaelin It is there, as the default blank entry. The real issue here is that the FormOverlaySheet needs to be brought into design compliance. 
![Screenshot_20240522-155816](https://github.com/techmatters/terraso-mobile-client/assets/8915145/9303e928-c695-496e-a225-00a8bc166623)

**Comment by DerekCaelin** [comment]
Are there any other aspects of FormOverlaySheet that need to be updated? If not we can preserve this issue.

**Comment by CourtneyLee333** [comment]
Yes. This is part of the component work, and engineers plan to bring them into compliance. I'm not sure if that is captured yet in a backlog task, but if not it will be.

**Comment by CourtneyLee333** [comment]
This work was complete in another issue.
