### ISSUE TITLE
Missing "Done" button on texture and rock fragments screen

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#860]
- [ ] Add a "Done" button to the soil texture screen.

![Image](https://github.com/techmatters/terraso-mobile-client/assets/10799815/373c2145-f8ea-4073-8f38-c977c685729f)

## Resolved, clean this
- [X] The images for rock frag seem blurry, and they have a transparent background so that the green shows through when you select one. At the minimum those images need a white background, and ideally they will be crisp. I'm glad to rework the images according to what the engineers need.
  - We may be using the images that have "sm" in [this folder](https://drive.google.com/drive/folders/1d43Jy-Dj4dI6UlQzHAbG3lS_xROGHXL0). as opposed to the ones without, which seem higher-quality. Let's change these images to the ones in [this folder](https://drive.google.com/drive/folders/16H8uazS6cdaG2cJuqnuZlya8eEDavWgc), which Courtney has produced to have a white background.
<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/7f71a599-8a1b-48ac-831e-f6dfc829dea1" width="400">

**Comment by ltseng** [comment]
@CourtneyLee333 the images in the Google Drive folder (linked above) all have transparent backgrounds. Would you mind reworking them before I try to tackle this with @paulschreiber?

**Comment by CourtneyLee333** [comment]
The "sm" versions of the pngs are definitely much too small. I've added white backgrounds and trimmed the edges of the larger versions and uploaded them to [this folder](https://drive.google.com/drive/folders/16H8uazS6cdaG2cJuqnuZlya8eEDavWgc?usp=drive_link). This work had the effect of reducing the file sizes in half.

**Comment by ltseng** [comment]
@CourtneyLee333 can you resize all of these images to be the same size (they currently have different dimensions) and 350x350 px? Also, if you're using Photoshop or another Adobe product, Paul is requesting that you "save them for web" to remove additional data, and then we'll further shrink them using TinyPNG.

**Comment by CourtneyLee333** [comment]
@ltseng I've resized them and replaced them in the folder. All of them were the same size except two of them had one pixel difference in width. And I had saved them all for web in photoshop. So I'm not sure if I'm missing something that Paul is looking for.

**Comment by ltseng** [comment]
I think this is perfect, thank you.

**Comment by CourtneyLee333** [comment]
The button is present, and it works. It does not have proper behavior regarding enabled/disabled states, but my understanding is we will clean it up soon along with the new Done button component work.
