### ISSUE TITLE
Use new logo on app icon

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#866]
```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/542
```

**Comment by ltseng** [comment]
@CourtneyLee333 can you post a link here to the file we should use for the app icon?

Also making a note here of Steve's suggestion that we place it on the splash screen somewhere, but I will likely make that a different issue.

**Comment by CourtneyLee333** [comment]
@ltseng I haven't created the app icon yet but it's on my list in [this issue](https://github.com/techmatters/terraso-product/issues/542). 

Splash screen - we don't have a splash screen. I don't think one can be added until later in the process, but I could be wrong about that. My intention is to use just the logo on a background for the splash screen, following best practices. 

We do need to add the logo to the login screen, which is also listed in that issue above. I will likely rework some of the verbiage as well.

**Comment by ltseng** [comment]
Right now, with the bug #435, I think that adding a splash screen would have a seizure-inducing effect 😅 so maybe let's pause on that for now. I'll link your issue in a tasklist above.

**Comment by ltseng** [comment]
The app icon is ready to be updated. @paulschreiber would you be able to make this update?
