### ISSUE TITLE
Tapping on a specific search list result causes app to show black screen

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#868]
### App Version

79

### Platforms

- [X] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

I noticed this when attempting to replicate a bug that Laura found. When I type "Denver International Airport" into the map search bar, and tap the option without the airport code, the app goes to a black screen.

### Steps to Reproduce

1. Type "Denver International Airport" into the home screen search bar
2. Select the result labeled "Denver Airport," which does not have the keyword "DEN"

### Expected behavior

Map pans/zooms over to that location with the location popover open

### Actual behavior

App shows black screen and I have to close and relaunch the app to make it usable again.

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/0fdf4426-5a30-44f2-8855-2aecfb88dd14

**Comment by ltseng** [comment]
Mapbox shows unexpected behavior when I try to replicate this in their [Search Playground](https://docs.mapbox.com/playground/search-box/) as well. We are probably not handling this case appropriately @paulschreiber 

![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/900c9678-3c8c-4207-bcb0-6d0270cca120)

**Comment by ltseng** [comment]
Although this is an edge case, I'm labelling this as medium-priority because we don't know how often this might happen with the Mapbox API and we should handle this error better.

**Comment by DerekCaelin** [comment]
I can't reproduce this in version 125
