### ISSUE TITLE
Mismatched units for GPS accuracy

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#869]
### App Version

79

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

Site Creation form shows GPS accuracy in meters, while Site Dashboard shows Location accuracy in feet. They ideally would show both in the same units, which would match whatever units are chosen by the user.

**Comment by DerekCaelin** [comment]
Does not occur in v142 (no location accuracy displayed)
