### ISSUE TITLE
Close bottom sheet when selecting search suggestion from home screen map search

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#871]
Laura logged this as a bug for the following test case:

> *Action*
> Using the search bar at the top of the screen, type in a keyword that matches a location you have in mind.
> *Expected outcome*
> A dropdown list of search suggestions should appear below the search bar. Selecting one of them should close the list of search suggestions, re-center the map's viewport on the selected location, and drop a pin with a "location popover" open below it.

> The first time I did this, the location popover did not appear (IMG_0045, IMG_0046). Upon retrying this, the location popover did appear (IMG_0047).

<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/c773522a-7993-418e-ad27-71ec80536559" width="300px">
<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/f2e8c15c-1570-48e6-b067-f420b450163e" width="300px">
<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/17a038ac-7053-4b4b-b5c2-1f5e3c877b3a" width="300px">

I think part of the reason why they thought this was a bug was that the sites list bottom sheet covers up the location popover, which we might want to address either in this issue or a related one. I'm not sure how to explain the second image, but let's do the following to help solve this problem:

Desired outcome:

When a user selects an option from the list of search suggestions, close the bottom sheet fully at the same time that the map viewport is reorienting around the chosen suggestion.

**Comment by CourtneyLee333** [comment]
This work was completed in another issue.

**Comment by paulschreiber** [comment]
Fixed via https://github.com/techmatters/terraso-mobile-client/pull/1509
