### ISSUE TITLE
Can't add site to project from site settings

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#881]
### App Version

79

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

The list of projects that opens up when I try to add a site to a project from the site settings page is populated, but selecting a project does nothing. I am the manager of the site, and I have several projects in the account I used where I am either a project manager or contributor, so permissions are not an issue here.

### Steps to Reproduce

1. Open the site settings for an unaffiliated site.
2. Click on the selection menu under "Transfer to Project"

### Expected behavior

Bottom/select sheet opens populated with list of projects where I have manager or contributor access.

### Actual behavior

Bottom/select sheet opens, but it's empty.

### Additional context
![image](https://github.com/techmatters/terraso-mobile-client/assets/2730009/4838d988-e9b2-4b2e-ba0f-76feb8e7c82d)

**Comment by DerekCaelin** [comment]
We realized this is less of a bug and more of an unimplemented feature: https://github.com/techmatters/terraso-product/issues/668
