### ISSUE TITLE
Update select form style

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#915]
Select list form fields need to be styled correctly throughout the app. Form styles and expected behaviors are outlined in Notes for Engineers:

[Notes for Engineers: Form Styles](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2647%3A10445&mode=design&t=ZSMVryxmVDtcwJvi-1)

Edit: outstanding issues:

```[tasklist]
### Tasks
- [ ] LandPKS Data Privacy sheet should have square, rather than rounded corners
```

**Comment by CourtneyLee333** [comment]
@ltseng Do we need to list all the locations in the app where this needs to be fixed?

**Comment by ltseng** [comment]
I really hope not 😂

**Comment by ltseng** [comment]
Work is mostly done, ended up touching a couple other things, so there's more tech debt refactoring work that will be included here.

Bringing in React Native Paper library to handle the appropriate text field label/placeholder behavior.

**Comment by ltseng** [comment]
Looks good on Android, waiting for iOS build to be fixed before I can finish testing it.

**Comment by DerekCaelin** [comment]
We are closing this issue and will file new bugs as needed.
