### ISSUE TITLE
Styling feedback for Team Members UI

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#918]
[Team Members screens in Figma start here](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=221%3A19771&mode=design&t=vJjFzKbLvlL4v8uR-1)

- Leave Project button needs correct styling (or the background of the screen needs to be white so the grey button is visible. I'm not sure which or if both are the problem.)
- Each team member row should span the width of the layout, rather than the less wide length it is now. So the pill should be to the right edge.
- The line under the team member is too heavy and dark. 
- Add Team Members screens need to have properly styled heading, properly styled form field, no paragraph text, and proper error messages.
- in the Add Team Member workflow, the select fields for role need to be properly styled, and the trashcan icon should be the correct color. 

![Image](https://github.com/techmatters/terraso-mobile-client/assets/8915145/6544897a-536c-46b2-a0aa-b0af734b1b1d)

![Image](https://github.com/techmatters/terraso-mobile-client/assets/8915145/4b35c529-a80e-47be-8943-e70be65917a9)

![Image](https://github.com/techmatters/terraso-mobile-client/assets/8915145/54ae8deb-7828-4117-bcf1-a4b9116c4efd)

**Comment by DerekCaelin** [comment]
We've done a different experience for capri
