### ISSUE TITLE
Implement splash screen

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#928]
Update splash screens on iOS and Android to meet the new design.

## Designs
[[Figma](https://www.figma.com/design/h4xdqfTq1c84YEn6AZcfHf/Splash-Screen-to-Log-In-Animation?node-id=500-224&t=M7dBBfuHzcd3Muzo-0)

## Acceptance Criteria
- [x] Updated splash screen designs for iOS and Android

**Comment by CourtneyLee333** [comment]
Engineers, the animation is not priority for our skinny MVP. Just the logo will be fine until we have more time.

**Comment by CourtneyLee333** [comment]
@DerekCaelin Will you please update this to be part of Capri? At least a minimal splash screen is necessary to publish the app to the stores.

**Comment by CourtneyLee333** [comment]
@DerekCaelin I think splash screens are already implemented, though they are different on each platform and neither matches the design. That's fine for Capri, but let's have a backlog design debt issue to fix those.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 this has a user story now and is in the backlog: https://github.com/techmatters/terraso-product/issues/744

**Comment by CourtneyLee333** [comment]
@paulschreiber iOS still has the wrong splash screen. It should be just the logo symbol.

**Comment by paulschreiber** [comment]
It's just the logo in v158. I'll release that build to you.

**Comment by CourtneyLee333** [comment]
I'm on v158 and I see the full logo - symbol and wordmark. Should be just the symbol.

**Comment by paulschreiber** [comment]
Confirmed this is fixed on 159 by checking a different iPad.
