### ISSUE TITLE
Project-selection dropdown for adding sites to projects does not consider user permissions

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#944]
### App Version

94

### Platforms

- [X] iOS
- [ ] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

I see the option on the Create Site form to add a site to a project where I'm a project viewer. The Save button fails silently when I attempt to save the site, but this project should not even appear in the list of available projects

### Steps to Reproduce

1. Be a viewer in a project
2. Open the Create Site form from the map
3. Open the "Add to Project" dropdown menu

### Expected behavior

Projects where I am a viewer should not display in the list

### Actual behavior

Projects where I am a viewer do display in the list

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/abc94e58-8957-4f11-aee0-618e7b79db1c

**Comment by DerekCaelin** [comment]
Since this is still "to do" as Ruxandra goes on vacation, I'm pulling this issue into the June sprint with the expectation that we may need to reshuffle once she returns.

**Comment by CourtneyLee333** [comment]
Works great!
