### ISSUE TITLE
Create link component for LandPKS

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#954]
Create a component for displaying links in the LandPKS app, both internal and external links. See the Links section of General Notes for Engineers in [the Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2647-10445&mode=design&t=jBK21hv7NtkZ5I6v-0)

Relevant for:
- Home info screen (External link style)
- Soils Info screen (Internal link style -- only do this if it exists somewhere already; otherwise do it when we actually implement one of these links in the app)

```[tasklist]
### Requirements
- [x] Create Internal link component --> Use `Button variant="link"` (see ColorGuideScreen's go_back button)
- [x] Create External link component --> Use `LinkNewWindowIcon`
```

## Acceptance Criteria
- [ ] External links
   - [ ] a Button
   - [ ] Size 15 Roboto, all caps, interactive green
   - [ ] external link icon
- [ ] Internal links (see styling in Figma under "notes for engineers")

**Comment by knipec** [comment]
This should be verifiable when v119 is made

**Comment by DerekCaelin** [comment]
@knipec Thanks for this! I'm going mark this task as complete and move the QA into May.
