### ISSUE TITLE
Scrolling sites list sometimes causes app to crash

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#963]
### App Version

102

### Platforms

- [ ] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

Sometimes scrolling through the sites list will cause the app to crash

Possibly related to  #961, as I encountered this in attempting a variation of the behavior listed there

### Steps to Reproduce

1. Make sure you have more than fifteen sites created so that the sites list doesn't automatically load all of  the sites at once.
2. Open the sites list bottom sheet and type a keyword in that you know matches some of the sites
3. Scroll through the list and make sure a couple more sites load than initially
4. Clear out the search term
5. Scroll to the bottom of the sites list sheet

### Expected behavior

Sites list allows you to continue scrolling to the bottom

### Actual behavior

App crashes

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/2730009/9fe036ab-d437-4f07-9483-33a8af7c8aeb

**Comment by tm-ruxandra** [comment]
Fixed as part of work done for PR [1098](https://github.com/techmatters/terraso-mobile-client/pull/1098).
