### ISSUE TITLE
feat: finish soil color

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#974]
soil color is almost done! the algorithm runs fast, and returns reasonably accurate results under ideal conditions. the following work remains to close out this feature:

```[tasklist]
### Remaining work
- [x] The cropping UX is not ideal. Currently, if you exit out of a crop screen, you will lose the progress of both crops. And if you re-enter a crop screen, you lose progress on the crop. I think it would also be nice to show a dimmed outline around the crop area instead of the crop area going directly to the edge of the frame, but that's not so crucial.
- [x] The color algorithm currently fails silently if a color is returned outside of what we consider a valid munsell soil color. We should instead show a modal displaying the computed color and informing the user what has happened, and offer them the choice to either proceed with the algorithm's value anyway, or offer them the closest valid munsell soil color to the color the algorithm returned.
- [x] We currently take a very broad view of what is considered a valid munsell soil color. We'd like to consider exactly the set of colors in the munsell soil color book to be valid. There's a mostly complete table here: https://docs.google.com/spreadsheets/d/1mW6sCFKyu3FrorivCB-PfQcLxs3uq_s-/edit#gid=1464184837, so we just need to cross-reference that with the book to implement this feature.
- [x] We always display a hue, even for very low chroma values. It's standard practice to abbreviate munsell colors with low chroma values with the `N` hue, so we should do this when displaying color strings
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1063
```

**Comment by CourtneyLee333** [comment]
@shrouxm Is there any design work you want me to do for the first item? If so, let's discuss because I don't quite follow. Otherwise, I trust you to build what you're thinking and I can review it. 

I think the only other piece in the list for me is the second item, for which I have created ticket #593.

**Comment by shrouxm** [comment]
@CourtneyLee333 re first item: nope! I just hadn't implemented the natural assumptions for how navigating between the screens would behave in the versions so far.

oh i think i see the confusion, i should've written "The cropping UX _as currently implemented_ is not ideal.", the designs don't specifically say anything about the way it works right now because no one would assume it should be implemented the way it works right now :upside_down_face:

**Comment by DerekCaelin** [comment]
@shrouxm I did some testing of the photo processing tool, results are [here.](https://docs.google.com/spreadsheets/d/1XuqQspff4TptXOuG5UHs-i6RkRuqhrcrMqCltyqYLGo/edit#gid=2004954072)

For this test, I took photos from the [Munsell color book
](https://drive.google.com/drive/folders/1gIYC6yxpHXJ962QkFPx2TuqFG9Z20GWU). 
<google-sheets-html-origin><style type="text/css"></style>
Expected result | Actual result
-- | --
Return 2.5YR 5/5 | Unexpected. Suggestion 5YR 4/6, Your result: 5YR 4/8
Return 5Y 5/2 | Unexpected soil color. Suggestion 7.5YR 4/1, Your reseult 5YR 4/1
Return 7.5YR 3/1 | Unexpected soil color: Suggestion 10YR 2/1, your result N 2/
Return 10YR 7/4 | 5YR 7/8

**Comment by DerekCaelin** [comment]
@shrouxm and I agreed that we should close this issue for April and I will file bugs emerging from QA in May. Follow the [parent user story](https://github.com/techmatters/terraso-product/issues/160) to find outstanding issues.

**Comment by shrouxm** [comment]
@DerekCaelin thoughts on those results:
- for the first one, i don't believe there's a 5 value for chroma, the columns on most of the sheets go 1 2 3 4 6 8, so i think it should be 2.5YR 5/6. and 5YR 4/6 is only one away in hue and value so i think this is a good result
- for the second one, 7.5YR 4/1 is only one away in value/chroma from 5Y 5/2, but the hue is way different. but it's very hard to distinguish hue at low chroma values. this might be something to check in with the scientists about
- for the third, 10YR 2/1 is close enough to 7.5YR 3/1
- the 4th seems like a bad result, i will experiment with that example as well

more generally:
- it is seeming like the tolerance for "unexpected" is a bit tight. in all 3 of those cases, the suggested result is pretty close to the "actual" result and i think not showing the modal warning would've been a better UX
- is it onerous to also run the color algorithm from the old app on the same test cases? i guess we could consider the bar for capri to be "as good or better than the old app's color algorithm", and then try to polish it to our own standards if we have time

**Comment by DerekCaelin** [comment]
> for the first one, i don't believe there's a 5 value for chroma
That makes sense, my test photo obscures the column numbers!
![image](https://github.com/techmatters/terraso-mobile-client/assets/10799815/2ee77e6c-d9ce-4c3f-9e21-dd957de4a02d)
