### ISSUE TITLE
feat: fix remaining bugs and implement new designs for depth intervals

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-mobile-client#975]
```[tasklist]
### remaining work
- [x] fix crash when updating existing interval in non-project site (update still goes through, but app crashes for some reason)
- [x] make sure everything works with roles
- [x] make sure data collected at matching depths is still visible when transferring site
```

**Comment by ltseng** [comment]
@shrouxm it looks like the app is no longer crashing for either Derek or me when we modify depth intervals at the site level. Yay!

**Comment by shrouxm** [comment]
weird, i didn't change anything!

**Comment by shrouxm** [comment]
maybe it was a sneakily a role-related bug and ruxandra's backend changes resolved it :thinking:

**Comment by DerekCaelin** [comment]
Confirmed I don't see this as an issue. I'm checking off the requirement on this issue.

**Comment by CourtneyLee333** [comment]
@shrouxm I don't want to belabor a point we've talked about a lot, but this verbiage worries me: 
"make sure everything works with roles - contributors can't create depth intervals"

because contributors can create depth intervals sometimes, but they can't edit depth interval requirements.

**Comment by DerekCaelin** [comment]
I confirmed that the last, unchecked element was addressed (I transfered a site with data in custom depths, and for the depths that aligned with the parent project, they were visible. )
