### ISSUE TITLE
Project manager can't update name of project

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#977]
### App Version

104

### Platforms

- [ ] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

I can't update the name of an existing project even when I'm a manager.

### Steps to Reproduce

1. Open an existing project and go to the settings tab
2. Change the name and click Done

### Expected behavior

Changes are saved immediately

### Actual behavior

Changes are not saved

### Additional context

https://github.com/techmatters/terraso-backend/assets/2730009/dba1d436-b3d5-4333-9271-bbed8d317dab

**Comment by ltseng** [comment]
Seems to be fixed on Android! Obviously haven't tested it on iOS quite yet though.

**Comment by DerekCaelin** [comment]
This is resolved on android. Thank you!

- [x] renamed project
- [ ] quit app, reopened, project remained renamed.
